horizontalsystems/unstoppable-wallet-android

- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/bitcoin/wallet/viewHelpers/DateHelper.kt
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/values/styles.xml
- Update design in Transactions cells
- Add padding to top tabs
- Fix crash when user resumes app with BottomTransactionInfo opened
Close #118
> Update design in Transactions Screen #118

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
- app/src/main/res/layout/view_holder_coin.xml
- app/src/test/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatterTest.kt
- Fix exchange rate move on rate update in Coin Wallets
- Disable default animation on item binding for Coin Wallets
Partially fix #473
> Balance collapse fixes

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LockManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractorTest.kt
Close #145
- Show confirmation dialog on Backup words validation if user hasn't backup them before
- Show PIN unlock when user taps on Backup wallet words in Settings
> Confirmation dialog updates

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreWrapper.kt
> Increase the PIN timeout for android secure storage access to 24 hours

- app/src/main/res/values/styles.xml
When using a device in landscape mode, alerts width are very small.
Example below, on a 8" tablet
Before
After this fix
> Fix AlertDialog width for landscape

- app/src/main/java/io/horizontalsystems/bankwallet/SingleLiveEvent.kt
Restore code in SingleLiveEvent class falsely removed during migration to AndroidX #821
> Restore SingleLiveEvent correct functionality

- app/build.gradle
- Update binance-chain-kit dependency version to (8b24d51 commit)
> Update binance-chain-kit dependency version.

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/res/layout/view_holder_full_transaction_link.xml
In FullTransactionInfo hide link that opens transaction info for providers that don't support this 
Close #1083
> Hide link that opens transaction info in external source for EOS

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/AlertDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/BackupAlertDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/BalanceSortDialogFragment.kt
- app/src/main/res/layout/fragment_bottom_backup_alert.xml
- app/src/main/res/values/strings.xml
- Update account state BackedUp in Balance page
- Fix deletion of enabled wallets when their account becomes Backed Up
- Move AlertDialog and BalanceSortDialog to ui/dialogs package
- Show Backup Alert as bottom dialog
- Open directly Backup activity when user clicks on BackupButton in BackupAlertDialog shown in Balance page
Close #1167, #1023
> Backup alert improvements and bug fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
The problem was in the concurrent execution of methods. It starts to update wallets list in one thread. Then it updates the balance for newly enabled coin in the second thread before the updating wallet list is finished. Since the wallet list doesn't contain the enabled coin it doesn't find it and crashes.
Close #1187
> Fix the issue with crashing when enabling coin

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- for BTC, BCH and DASH don't show from address field
- add from addresses to TransactionRecord in BitcoinBaseAdapter because setting it to empty list breaks correctness of function isSentToSelf() in TransactionViewItemFactory
Close #1234
> Add showFromAddress flag to TransactionViewItem

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/KeyStoreChangeListener.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStorePresenter.kt
- Do not remove key when "keystore module" opened for authentication
- Delete accounts and clear kits on app reset in "keystore module"
- Remove unused methods from IKeyStoreManager interface
Closes #1342
> Keystore bug fixes & enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/AnimationHelper.kt
-  Added an action that runs when animation is expected to complete and hides the view it wasn't already hidden.
Close #1323
> In Balance tab hide view when collapse animation doesn't end properly

- app/build.gradle
- BitcoinKit had bug with restarting sync when network becomes available
- EthereumKit wasn't restarting sync at all when network becomes available
targeting #1391
> Update BitcoinKit and EthereumKit to get bug fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoViewModel.kt
- use postValue for liveData assignments
- when bottom sheet changes state to expanded show background dim
targeting #1490
> Fix transactionInfo bottom sheet bug

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/XRateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- make presenter layer async in background thread
- synchronize interactor delegate methods
- in IViewDelegate pass viewItem instead of position
- fix multi-threading issues in AdapterManager
- WalletManager: replace wallets updated signal with observable<Wallets>
ref #1400
> Refactor balance module

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
Ref: #1578
- Rename IDEX,Ripple,Bancor,Binance tokens 
- Remove support for Zilliqa, WAX
> Rename and remove support for some tokens

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/Pool.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionStatusWithTimeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
- app/src/main/res/drawable/ic_attention_12.xml
- app/src/main/res/layout/view_transaction_info_status.xml
- app/src/main/res/layout/view_transaction_status.xml
- app/src/main/res/values/strings.xml
ref #1017 
- add field "failed"  to TransactionRecord
- add Failed item to TransactionStatus
- handle showing failed transactions in transactions tab and transaction info view
- add field "uid" which uniquely identifies TransactionRecord, change TransactionRecord equals and hashCode methods accordingly
- request transactions by passing from TransactionRecord instead of  pair<hash, interTransactionIndex>
> Failed transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/res/layout/view_cell.xml
- app/src/main/res/values/strings.xml
- Fix text for Receive alert when coin not backed up yet
- Show filters in Transactions in Alphabetical order
- Fix alert icon right padding in Settings
- Rename Volume to Volume (24h) in Rate Chart Info
ref #1772, #1774, #1775 , #1766
> Minor fixes

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/receive/ReceivePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelperTest.kt
Ref #1799
- Round the hour part of locked-date info for Locked transactions in tx-info tab.
> Round locked-date info for Locked transactions in tx-info tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CoinItemsAdapter.kt
- app/src/main/res/layout/view_holder_coin_manage_item.xml
- make switch clickable and set click listener
ref #1837
> In coin manager don't highlight whole coin cell when clicking on switch

- app/build.gradle
- app/src/main/res/values/strings.xml
Ref #1899 
- Upgrade btc-kit dependencies with BCH restore API url fixed.
> Upgrade btc-kit dependencies with BCH restore API url fixed.

- app/build.gradle
- Upgrade btc-kit dependencies with dep. conflicts fix. (okHttp3 to 4.0.1).
> Upgrade btc-kit dependencies with dep. conflicts fix. (okHttp3).

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/CashexplorerBitcoinCashProvider.kt
Ref #1956 
- Replace BitcoinCash Coin.space-API with Cashexplorer.bitcoin.com in Full TxInfo
- Implement custom SSL-certificate trust utility to connect to hosts with Self signed and not verified certs.
> Replace BitcoinCash Coin.space-API with Cashexplorer.bitcoin.com  in Full TxInfo

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BinanceChainProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockchairProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BtcComProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/CashexplorerBitcoinCashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosGreymassProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/InsightDashProvider.kt
Ref #1956 
- Fix BitcoinCash api provider status. 
- Apply SSL trust utility for cashexplorer.bitcoin.com provider.
> Fix BitcoinCash api provider status. 

- app/src/main/res/xml/network_security_config.xml
Ref #1961 
- Add Non-SSL btc-testnet.horizontalsystems.xyz url to cleartext-permit list. (Allow non-https url traffic)
> Add Non-SSL btc-testnet.horizontalsystems.xyz url to cleartext-permit list

- app/build.gradle
- Upgrade xrates-kit dependencies (Return last CLOSE value  instead of average)
> Upgrade xrates-kit dependencies with rates value parsing fix.

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
> Use shuffled ordering for bitcoin-kit transaction inputs and outputs

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- add method refreshAdapters to AdapterManager, for partially refreshing adapters
- in PrivacySettingsInteractor include Erc20 wallets when updating settings for CoinType.Ethereum
ref #2058
> Refactor method for refreshing adapters after blockchain settings change

- app/build.gradle
Ref #2132 
- Downgrade android.material dependencies to 1.2.0-alpha05 (To resolve BottomSheetBehavior bug)
> Downgrade android.material dependencies to 1.2.0-alpha05 (to fix BottomSheetBehavior bug).

- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CoinItemsAdapter.kt
Ref #2162 
- in Coin list view , Remove 'isPressed' event checking inside switch button 'onChange' listener.
> Fix bug with switch button in Coin List view

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/res/layout/activity_rate_chart.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/values-night/themes.xml
- components/views/src/main/res/values/themes.xml
- Replace ripple effect for RateDiff in Rate Chart
- Don't set click for RateDifference when notifications are disabled
- Override global ripple color with Steel color
- Fix push message text
ref #2349
> Add small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/res/layout/view_holder_guide_preview.xml
- components/views/src/main/res/values-night/themes.xml
- components/views/src/main/res/values/attrs.xml
- components/views/src/main/res/values/themes.xml
- Make Guides image height 180dp
- Add background to Guides image view
- Fix Guides losing bottom padding on theme switch
ref #2487, #2495
> Make ui fixes to Guide Image preview

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroViewPagerAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysDialog.kt
- Use empty constructor in IntroFragment.kt
- Use empty constructor in ManageWalletsDialog.kt
- Use empty constructor in ManageKeysDialog.kt
- Remove unused enum in ManageKeysDialog.kt
ref #2512
> Fix Fragment InstantiationException

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundStateChangeListener.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/KeyStoreChangeListener.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchPresenter.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/BaseKeyStoreActivity.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreInteractor.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreModule.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
- core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt
- Close app when user press Back key on Keystore Error Activity
- Make single call to KeyStore validation on app start/resume
- Serialize actions done on EnteringForeground
- Move LockScreen opening code from PinComponent.kt to app
ref #2500
> Optimize Keystore error validation

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ZcashBirthdayProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsService.kt
- save user entered block height instead of actual checkpoint got from zcash sdk
> Zcash wallet birthday height improvements

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
Adding the latest SDK uses a newer checkpoints (mainnet: 1047000, testnet: 1170000).
Technically, no changes are required beyond updating the version number. However, the intention of the SDK changes are to enable developers to use the Initializer with a Config object. This will help in the near future, when switching SDKs can be done programmatically rather than through build flavors.
So this PR suggests a way to simplify the Initializer setup a bit that deletes more code than it adds. 
The underlying changes in the SDK now allow for these improvements:
1. **Ignore Sapling details**
Developers should not need to worry about the [sapling activation height](https://github.com/horizontalsystems/unstoppable-wallet-android/compare/master...gmale:task/update-sdk#diff-ff2ca67def8ca0191010d4ceb64 …
> Add latest Zcash SDK and simplify initialization

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
After more testing, I discovered a minor regression while restoring Zcash without specifying a birthday height. The wallet was syncing from the latest checkpoint rather than the oldest. So we iterated on the last round of SDK changes and added a way to restore that was simple yet fixed this problem without requiring the wallets to keep track of sapling details like the activation height.
---- 
1. On a fresh install, restore a Zcash wallet
2. Do not provide a birthday height
3. Observe: the wallet syncs from the latest checkpoint (block 1047000), meaning it will skip most user's transactions
4. Expected: the wallet syncs from sapling activation height whenever no birthday is provided during restore
---- 
After applying this PR, the wallet behaves as expected for restoring with a birthday, …
> Fix Zcash restore without birthday height

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
- app/src/main/res/layout/view_card_swap.xml
- app/src/main/res/navigation/main_graph.xml
- don't reset amount to null after switch for not estimated amount
- set correct style for secondary amount
- set opening animation for advanced settings page
ref #2817
> Minor bug fixes in swap

- app/src/main/res/layout/view_input_address.xml
- app/src/main/res/layout/view_input_with_buttons.xml
- components/chartview/src/main/res/layout/chart_indicator_view.xml
- components/chartview/src/main/res/layout/view_chart.xml
- components/views/src/main/res/layout/view_key_input.xml
- components/views/src/main/res/layout/view_manage_account_view.xml
- components/views/src/main/res/layout/view_multiple_input_edit_text.xml
- components/views/src/main/res/layout/view_text_input.xml
As far as I know, only ConstraintLayouts should not be nested because they are made to have a flat hierarchy, so I have optimized only the custom views which extend from ConstrantLayout.
> eleminate nested ConstraintLayout in custom views

- app/build.gradle
Ref #3169 
Removed dublicates for Holo, Bidao, Thorchain and BTC-Alpha tokens
> Upgrade xrate-kit dependencies with duplicate coins fixes

- core/src/main/java/io/horizontalsystems/core/SingleLiveEvent.kt
The postValue method calls the setValue at the end. State was reset in both methods. Sometimes it might trigger the observer twice. Left resetting state only in setValue.
#3292
> Fix the issue with SingleLiveEvent triggering twice

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
To get equal diffs for the 24h type of chart and latest rate, added the following logic:
- When the type chart is 24h we add the point to the begging of the chart. The value of this point calculated based on the value and priceDiff24h of the last point. And the timestamp is `last point timestamp - 24h`
#3458
> Show the rate diff calculated from the chart points

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewPagerAdapter.kt
Set the default balance page type to Balance instead of NoAccounts. When turning back to MainFragment it creates a new instance of MainViewPagerAdapter. So initializing the adapter with the BalanceFragment uses the prev instance of BalanceFragment.
#3864
> Do not recreate the BalanceFragment when opening it from backstack

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransactionsProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountCleaner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ZcashBirthdayProvider.kt
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
Changes to update to the latest Android SDK. This adds quite a lot of [changes and fixes since version 1.2.1-beta04](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/CHANGELOG.md#version-121-beta04-2021-01-05), including migrating to Maven Central from JCenter (this also adds t-addr support and autoshielding support, under the hood)
Tasks to complete before converting this from a DRAFT to a PR:
> Zcash/update sdk 1.3.0 beta16

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectSendEthereumTransactionRequestFragment.kt
- app/src/main/res/values/strings.xml
- change the title from 'Request' to 'Contract Call' if (unknown). for cases Sign, Swap, Approve show title as Sign / Swap / Approve
- on ALL WalletConnect confirmation screens change the button text from ' Approve' to 'Confirm'
#4059
> WC confirmation screen text fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
When liveData observed as state for composable it emits initial value and then the value of liveData itself. It's true also for case when restoring the view. It results in scrolling to the start and then scrolling to the last position. To prevent this behavior filterCoinsLiveData observed without default value.
#3999
> Prevent scrolling back and forth when restoring state of filter coin tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
It seems that, before app theme switching and language change were not reflected because of fragment's state restoring. But now it is not the case anymore.
#4408
> Allow fragments to be restored from savedInstanceState

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundStateChangeListener.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/LockManager.kt
- core/src/main/java/io/horizontalsystems/core/BackgroundManager.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
#4741
- prevent bypassing app passcode
- make LockManager.isLocked true by default
#4730
- synchronize additions/removals to list in BackgroundManager
> Handle WalletConnect deeplinks in LauncherActivity

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt
Adjust the UI view parameters so that very long wallet names (i.e. those long enough to get truncated) don't result in the dropdown icon being pushed off the screen.
> Fix formatting for long wallet names

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
Starting tor kit in background resolves it. The tor kit chooses port not in use before starting. It checks if port in use by connecting to it. It can be done only in background thread.
#3959
> Fix tor starting if the default port 9050 is already in use

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
It is to fix the issue with an empty formatter when retrieving it concurrently.
#5454
> Make number formatters thread safe

- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
The crash error mentioned in #5515 is fixed under this pr
I attached the screenshot as below
> Fix invalidated keystore dialog crash

- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
Hello,
I have a new finding which probably relates to issue #5515 and #4163.
I figured out the reason why it stops working after 1 day is that keystore needs user authentication by either biometric or pattern defined under [#1](https://github.com/horizontalsystems/unstoppable-wallet-android/blob/58fad2e8dd5a2d1b61dcb37e14ad66bcd0a81eb5/core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt#L28) and [#2](https://github.com/horizontalsystems/unstoppable-wallet-android/blob/58fad2e8dd5a2d1b61dcb37e14ad66bcd0a81eb5/core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt#L99). Next time launch will try to prompt user authentication (in my case, it uses biometric), otherwise it will validate keystore, resulting in throwing user authentication exception. …
> Fix biometric prompt window crash

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
Long click on balance tab bottom navigation item stops working when markets tab is disabled. Fixed by setting action for long click to all items.
#5721
> Fix long click on balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/CexWithdrawAddressService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexScreen.kt
> Add address validation to WithdrawCex module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
> Move Contact, Tell Friends, Rate Us to Main Settings page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/SetDuressPinIntroFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/SetDuressPinSelectAccountsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinConfirm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinSetView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinTopBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinUnlockView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinConfirmViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TorBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/InfoText.kt
> Duress pin additions2

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/About.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/DescriptionMarkdown.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/type.xml
- Remove Read More
- Show heading 1 bigger
- Add Ai generated info text
#6565
> Make changes to Coin description

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
> Replace Random/Regular buttons with Random toggle

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyViewModel.kt
> Fix private key validation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt
> Make UI changes to hide amount

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/SessionRequestFilterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt
> Handle custom WC pending requests topics

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesMenuService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetState.kt
- app/src/main/res/drawable/ic_sort_h2l_20.xml
- app/src/main/res/drawable/ic_sort_l2h_20.xml
> Add periods to Watchlist

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/memo/HSMemoInput.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
> Add memo field for Ton sending and receiving

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
#6843
There is a case when the app process is killed and restored by Android OS. When the app is restored it tries to restore all fragments. But the navController is not getting restored and it contains single back stack entry, which is mainFragment.
So if user was in the page like TokenBalanceFragment or TransactionInfoFragment, those fragments are restored. Since they do not get expected data, they call `navController.popBackStack()`. It results in popping off the single mainFragment of the back stack. And the MainFragment tries to create TransactionsViewModel using the mainFragment back stack entry. But the nav controller back stack is empty. That is why it crashes app.
Fixed issue by ensuring that those fragments closes themselves if needed.
> Fix the issue with crash on process restore

- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/EvmKitWrapperHoldingViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCSendEthScreen.kt
> Clean code

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAdapterRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TextImportant.kt
- app/src/main/res/values/strings.xml
> Show Tron inactive address warning in Token Balance

- app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCSendEthereumTransactionRequestViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectTransaction.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signtransaction/WCSignEthereumTransactionRequestViewModel.kt
> Wc initial nonce and gas price

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewMetrics.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartModule.kt
- app/src/main/res/values/strings.xml
> Switch global market data to new endpoint

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostService.kt
- Fix sync error on Loading Market News
- Fix Metrics icons
- Fix ETF icons
#7284
> Make small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/AppBar.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonPrimary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
> Implement button style updates

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseTokenManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt
> Remove conversion token changer from settings

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/asset/CexAssetViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt
- app/src/main/res/values/strings.xml
> Add option to customize price change display on coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ui/CoinScreenTitle.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
> Add circular clipping for coin images

- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartIndicatorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
> Fix sort menu icon on Balance page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/TopCoins.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsViewModel.kt
- Fix scroll to top
- Remove extra divider in Pairs
#7532
> Make fixes in Markets

- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetState.kt
> Set fallback coin image for widget

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filtersresult/MarketFiltersResultViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformCoinsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/TopCoins.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListOrderable.kt
> Show Mcap as subtitle in TopCoins and Watchlist

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
> Show rate 0 change in grey color

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt
> Make fixes to Market Etf

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7542#issuecomment-2178570970
> Fix WalletConnect no Account error

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SuggestionsBar.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabButton.kt
> Make small UI fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt
- app/src/main/res/drawable/ic_uwt2_24.xml
- app/src/main/res/values/strings.xml
> Add link to BeUnstoppable mini-app

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt
- app/src/main/res/values/strings.xml
> Add info for ZCash pending balance

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonModule.kt
> Handle sending max available TON

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Header.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/cell/CellUniversal.kt
- app/src/main/res/drawable/crown_yellow_16.xml
- app/src/main/res/values/strings.xml
> Group some filter options under Premium border

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fee/FeeCell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fee/HSFeeInput.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonViewModel.kt
* Add 1 sec debounce for fee estimation
* Add loading fee state in Ton send
#7721, #7812
> Handle exception on ton fee estimation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/processing/SendEvmProcessingFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/processing/SendEvmProcessingViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
- app/src/main/res/drawable/ic_checkmark_48.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Implement UI for SendEvmProcessing page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivityViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tonconnect/TonConnectNewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tonconnect/TonConnectSendRequestScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tonconnect/TonConnectSendRequestViewModel.kt
> Make small fixes to TonConnect

- app/src/main/java/io/horizontalsystems/bankwallet/core/address/AddressCheckType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
- app/src/main/res/values/strings.xml
> Fix swap info

- app/src/main/java/io/horizontalsystems/bankwallet/modules/basecurrency/BaseCurrencySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filtersresult/MarketFiltersResultsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/language/LanguageSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/SelectSubscriptionScreen.kt
Adds navigation bar padding to multiple screens for better UI on devices with navigation bars.
- AppearanceFragment
- TvlFragment
- EtfFragment
- SelectSubscriptionScreen
- Composables
- BaseCurrencySettingsFragment
- PrivacySettingsFragment
- MarketPlatformFragment
- MarketFiltersResultsFragment
- GuidesFragment
- LanguageSettingsFragment
- MarkdownFragment
- MarketCategoryFragment
- FaqFragment
- BlockchainSettingsFragment
- MetricsPageFragment
- MarketSearchFragment
- CoinFragment
> Fix bottom navigation bar overlapping view
