- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
- Fix IllegalStateException crash in BalanceFragment
- Fix crash on entering decimal point in SwapModule
ref #2699
> Fix IllegalStateException crash in  BalanceFragment

- app/src/main/AndroidManifest.xml
> Disable Google analytics data collection

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapFragment.kt
> Handling BackPress in fragments

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
> Enable web socket mode for EthereumKit

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
> Show Zcash transactions with 0 value

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
> Fix sliding to first page in Main page on pressing back button

- app/build.gradle
> Upgrade TorKit dependencies (with service lifecycle fixes)

- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_holder_transaction.xml
> Refactor transaction views to show long texts correctly

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectSessionStore.kt
- app/src/main/res/layout/activity_wallet_connect.xml
> Wallet Connect: handle account delete

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/CustomPriorityUnit.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/TextHelper.kt
> Add custom fee selector to Ethereum

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/CustomPriorityUnit.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
> Fix custom fee preselection with Recommended value

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/PicassoRoundedImageView.kt
- app/src/main/res/drawable/rounded_image_background_16dp.xml
- app/src/main/res/layout/fragment_wallet_connect_main.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Wallet Connect small UI fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
> Full tx screen fixes

- app/src/main/res/layout/partial_transaction_info.xml
- components/views/src/main/res/layout/view_settings_item.xml
- components/views/src/main/res/layout/view_settings_value_text.xml
> Add background to WalletConnect amount view

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
- components/snackbar/src/main/res/layout/view_custom_snackbar.xml
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Show approving snackbar in swap

- app/src/main/res/layout/fragment_swap.xml
- app/src/main/res/layout/fragment_swap_settings.xml
- app/src/main/res/menu/swap_menu.xml
- app/src/main/res/menu/swap_settings_menu.xml
- components/views/src/main/res/color/background_pressed_lawrence.xml
- components/views/src/main/res/drawable/lawrence_rectangle.xml
> Minor ui changes in swap

- app/src/main/res/layout/view_holder_balance_item.xml
> Increase buttons bottom padding in Balance wallet item

- app/build.gradle
- build.gradle
- components/chartview/build.gradle
- components/currencyswitcher/build.gradle
- components/icons/build.gradle
- components/keystore/build.gradle
- components/languageswitcher/build.gradle
- components/pin/build.gradle
- components/seekbar/build.gradle
- components/snackbar/build.gradle
- components/views/build.gradle
- core/build.gradle
- core/src/main/java/io/horizontalsystems/core/BackgroundManager.kt
- Refactor gradle versions
- Increase compile SDK version to 30
ref #2758
> Refactor modules gradle dependencies

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/Erc20ContractInfoProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addErc20token/AddErc20TokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addErc20token/AddErc20TokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addErc20token/AddErc20TokenViewModel.kt
- app/src/main/res/values/strings.xml
> Handle API limit exceeded error in AddErc20TokenFragment

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
> Integrate Uniswap-graph xrates provider

- app/build.gradle
> Update Bitcoin Kit to fix ConcurrentModificationException

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/eos/BackupEosFragment.kt
- app/src/main/res/layout/fragment_backup_eos.xml
> Fix Close button design in Eos words backup screen

- app/build.gradle
> Update bitcoin-kit with bitcoin-cash's ASERT algorithm

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/StatusInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionDetailsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/res/layout/fragment_status_info.xml
- app/src/main/res/layout/view_transaction_info_item.xml
- app/src/main/res/menu/status_info_menu.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/values/styles.xml
> Implement status information screen in Transaction Info

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
> Add CryptoCompare api-key for use in dev. builds

- app/build.gradle
> Update HDWalletKit to include Mnemonic checksum validation

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateAppManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutViewModel.kt
> Show Rate Us with 40 days interval

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosFragment.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapterTest.kt
> Fix Eos account name validation

- app/build.gradle
Ref https://github.com/horizontalsystems/Unstoppable-Wallet-Website/issues/24
> Change FAQ resource url

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
> Optimize UniswapGraphProvider implementation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsService.kt
- app/src/main/res/values/strings.xml
> Show Invalid Checksum error

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapFragment.kt
- app/src/main/res/layout/fragment_swap.xml
> Fix top padding in Swap Screen

- app/build.gradle
> Upgrade xrate-kit dependencies with coinCodes char. cases fix

- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumFeeViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationModule.kt
- app/src/main/res/layout/fragment_swap.xml
- app/src/main/res/values/strings.xml
- fix bug in swap confirmation
ref #2817
> Refactor swap action buttons & fee view states

- app/src/main/res/layout/view_transaction_info_item.xml
> Fix decorated text constraints in TransactionInfo

- app/build.gradle
> Upgrade xrate-kit dependencies with ignored tokens with zero xrates

- app/src/main/res/layout/view_hodler_input.xml
- app/src/main/res/layout/view_send_fee.xml
- app/src/main/res/layout/view_transaction_status.xml
- components/views/src/main/res/values/styles.xml
> Update some icons sizes

- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
> Fix Pin back press handling

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapTradeService.kt
- app/src/main/res/layout/view_holder_swap_confirmation_additional_info_item.xml
- Sync trade state after tradeoptions change
- Fix confirmation detail cell contraints
ref #2817
> Make swap fixes

- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
> Handle Back button click in Set Pin

- app/src/main/res/layout/fragment_settings_security.xml
Constrained horizontally two widgets.
> Widget constraint horizontally

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
> Remove unused strings

- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapAllowanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapAllowanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapPendingAllowanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/repositories/UniswapRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapSlippageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsViewModel.kt
> Update swap trade data on new mined block in Ethereum 

- components/pin/src/main/java/io/horizontalsystems/pin/PinView.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/Interfaces.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/LockoutUntilDateFactory.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/UptimeProvider.kt
> Handle phone reboot during pin lockout time calculation

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionDetailViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionDetailsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/res/values/strings.xml
> Show memo for for Binance, Eos and Zcash

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TermsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/terms/TermsFragment.kt
- app/src/main/res/layout/fragment_terms_settings.xml
- app/src/main/res/values/strings.xml
Added the new pin term
Ref #2973
> add pin checkbox in terms

- app/src/main/res/layout/fragment_transaction_info.xml
> Fix showing coin value without fiat value in Transaction info

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumRpcModeSettingsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Fix wrong Ethereum communication mode enabling by Tor switch

- app/src/main/res/values/strings.xml
> Change text on swap screen

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestViewModel.kt
- app/src/main/res/values/strings.xml
> Handle EthereumKit insufficient balance error

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/UnstoppableDomainsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/ISwapTradeOptionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/RecipientAddressViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapDeadlineViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapSlippageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AddressInputView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputWithButtonsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/View.kt
- app/src/main/res/layout/fragment_swap_settings.xml
- app/src/main/res/layout/view_input_address.xml
- app/src/main/res/layout/view_input_with_buttons.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/drawable/input_background_stateful.xml
> Add unstoppable domains support in Swap

- components/pin/src/main/java/io/horizontalsystems/pin/core/LockoutUntilDateFactory.kt
> Handle case when lockout time is equal to uptime in Pin

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/res/layout/view_amount_input.xml
- app/src/main/res/layout/view_card_swap.xml
@TalgatNurdinov Please check this one so I can go further with the other layouts which need the same redesign.
> Amounts inputs redesign

- components/pin/src/main/java/io/horizontalsystems/pin/core/NumPadItemsAdapter.kt
> Show pin buttons enabled from start

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/IMarketListDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- gradle/wrapper/gradle-wrapper.properties
> Integrate/Apply xrate-kit changes

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketTabsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketListDefiDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketListFavoritesDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/IMarketListDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketListTopDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
> Market global defi

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/FeeInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/res/layout/fragment_fee_info.xml
- app/src/main/res/layout/view_send_fee.xml
- app/src/main/res/menu/fee_info_menu.xml
- app/src/main/res/values/strings.xml
> Add fee info page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/res/layout/view_send_fee.xml
> Don't hide fee slider on fee error in Send screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapService.kt
> Show coin balance as approval amount in Swap

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketListDefiDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketListFavoritesDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/IMarketListDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketListTopDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopViewModel.kt
- app/src/main/res/values/strings.xml
> Market tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/RootUtil.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LauncherActivity.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/BaseKeyStoreActivity.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreModule.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStorePresenter.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreViewModel.kt
- components/keystore/src/main/res/layout/activity_keystore.xml
- components/keystore/src/main/res/values/strings.xml
> Implement Rooted Device check

- components/views/src/main/res/values-night/themes.xml
- components/views/src/main/res/values/themes.xml
> Disable forced dark mode

- app/build.gradle
> Update zcash-sdk and binance-kit

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/bep2/AddBep2TokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/erc20/AddErc20TokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchPresenter.kt
- core/src/main/java/io/horizontalsystems/core/CoreActivity.kt
- core/src/main/java/io/horizontalsystems/core/CoreApp.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Skip root check in Debug and Testnet builds

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestViewModel.kt
- app/src/main/res/values/strings.xml
> Handle Insufficient balance error in SwapApprove

- app/src/main/res/layout/view_settings_item_arrow.xml
> Fix long value in Settings View

- app/build.gradle
> Merge master into v19

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricLargeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricSmallView.kt
- app/src/main/res/layout/view_holder_market_totals.xml
- app/src/main/res/layout/view_market_metric_large.xml
- app/src/main/res/layout/view_market_metric_small.xml
> Market metrics stuff

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketListDefiDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketListFavoritesDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/IMarketListDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketListTopDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- docker/build-apk.sh
> Upgrade and integrate xrate-kit dependencies

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/Pool.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestService.kt
> Ethereum-kit refactoring integration and bug fix

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
> Add separate states for IBalanceAdapter & ITransactionsAdapter

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/AddressParser.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/AddressData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/RecipientAddressViewModel.kt
> Correctly convert Double to BigDecimal

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt
- update ethereum-kit
- compare Account objects only by id
ref #3027
> Add account check in EthereumKitManager and BinanceKitManager

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
> Open Transactions page when switching language

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/noaccount/NoAccountDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/noaccount/NoAccountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/noaccount/NoAccountService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/noaccount/NoAccountViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
> Enabling coin on restore

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AddressInputView.kt
- app/src/main/res/layout/fragment_add_token.xml
- components/views/src/main/res/drawable/input_background_stateful.xml
> Refactoring the AddToken module to use new input field

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
> Open transaction full info in inapp browser

- app/src/main/java/io/horizontalsystems/bankwallet/modules/lockscreen/LockScreenFragment.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
> Fix fingerprint scanner workflow when App is restored

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketFavoritesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/MarketFavoritesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketListFavoritesDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top100/MarketTop100Fragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateTopListFragment.kt
> Markets tab favorites

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
> Simplify code by converting CoinMarket to TopMarketRanked in interactor

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/dash/SendDashHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZcashHandler.kt
> Correctly show send button's error state

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Fix migration

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AmountInputView.kt
- app/src/main/res/layout/view_input_amount.xml
> Set AmountInputView secondary text as Bran color

- app/src/main/res/layout/view_transaction_info_item.xml
> Make multiline memo

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/defi/MarketDefiModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketLoadingAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top100/MarketTop100Fragment.kt
- app/src/main/res/layout/view_holder_market_loading.xml
> Show loading and error states in market tabs

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
> Disable viewpager swipe

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketInternalNavigationViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/top/MarketTopViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/AppLayoutHelper.kt
- components/icons/src/main/res/drawable/coin_placeholder.xml
> Market overview

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/FeeRateState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/FeeRateAdjustmentHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/FeeSelectorView.kt
> Fix Max amount with smart fee in Send page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep2Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsErc20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsViewModel.kt
- app/src/main/res/layout/fragment_enable_coins.xml
- app/src/main/res/values/strings.xml
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Enable coin

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewSectionHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ViewHolderMarketOverviewItem.kt
- app/src/main/res/layout/fragment_overview.xml
- app/src/main/res/layout/view_holder_market_overview_item.xml
- app/src/main/res/layout/view_holder_market_totals.xml
- app/src/main/res/layout/view_holder_overview_list_section_header.xml
- components/views/src/main/res/color/stateful_transparent_section_header_background_color.xml
- components/views/src/main/res/drawable-hdpi/overview_item_background_bottom.xml
- components/views/src/main/res/drawable-hdpi/overview_item_background_middle.xml
- components/views/src/main/res/drawable-hdpi/overview_item_background_top.xml
- components/views/src/main/res/drawable/transparent_section_header_clickable_background.xml
> Market overview items redesign

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketListFavoritesDataSource.kt
> Upgrade xrate-kit dependencies with changes to accept CoinCodes in markets methods

- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsDialog.kt
> Enabling coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ItemWithCheckmark.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/SettingItemWithCheckmark.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListAdapter.kt
- app/src/main/res/layout/constraint_layout_with_header.xml
- app/src/main/res/layout/fragment_bottom_selector.xml
- app/src/main/res/layout/view_holder_coin_manage_item.xml
- app/src/main/res/layout/view_holder_faq_item.xml
- app/src/main/res/layout/view_holder_setting_with_checkmark_wrapper.xml
- app/src/main/res/layout/view_item_with_checkmark.xml
- app/src/main/res/layout/view_settings_item_with_checkmark.xml
- components/currencyswitcher/src/main/java/io/horizontalsystems/currencyswitcher/CurrencySwitcherFragment.kt
- components/currencyswitcher/src/main/java/io/horizontalsystems/currencyswitcher/CurrencySwitcherModule.kt
- components/currencyswitcher/src/main/java/io/horizontalsystems/currencyswitcher/CurrencySwitcherPresenter.kt
- components/languageswitcher/src/main/java/io/horizontalsystems/languageswitcher/LanguageSwitcherFragment.kt
- components/languageswitcher/src/main/java/io/horizontalsystems/languageswitcher/LanguageSwitcherModule.kt
- components/languageswitcher/src/main/java/io/horizontalsystems/languageswitcher/LanguageSwitcherPresenter.kt
- components/views/src/main/java/io/horizontalsystems/views/SettingsViewBase.kt
- components/views/src/main/res/layout/view_holder_item_with_checkmark.xml
> Use rounded corner background CoinList, AddressFormat, FAQ, CurrencySwitch, LanguageSwitch pages

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
> Set the number of items to 250 in markets tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/EmptyListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/PoweredByAdapter.kt
- app/src/main/res/layout/view_holder_empty_favorites_list.xml
- app/src/main/res/values/strings.xml
> Show empty list text in Watchlist tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
> Clear items before fetching them when the category is changed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt
> Scroll list to top on changing sorting in Market tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewSectionHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/res/layout/view_holder_market_totals.xml
> Add loading state to the MarketOverview page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricLargeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricSmallView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/PriceGradientView.kt
> Market metrics small view na state

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
> Markets tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
> Set zcash transaction fee wrt block height

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewSectionHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
> Subscribe and observe on IO thread to all Rx items in Market modules

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewSectionHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
> Fix showing/hiding section headers

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/TopListSortType.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
- Rename Top Winners to Top Gainers
- Make currency as private in Market Services
ref #2912
> Market small refactoring

- components/views/src/main/res/values-night/themes.xml
- components/views/src/main/res/values/themes.xml
> Fix bottom fullscreen indicator background color

- app/build.gradle
> Upgrade xrate-kit dependencies with dublicate coins fixes

- app/src/main/assets/coin_categories.json
update coin_categories.json file
> Update categorization JSON file

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/CoinInfoMap.kt
- components/icons/src/main/res/drawable/coin_rgt.xml
> Add new erc20 tokens

- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumFeeViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/FeeSelectorView.kt
- app/src/main/res/layout/view_fee_selector.xml
- app/src/main/res/values/strings.xml
> Increase gas limit

- app/src/main/res/layout/activity_main.xml
> Toolbar spacing

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketCategoriesAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/res/layout/view_market_category.xml
> Market categories fixes

- docker/build-apk.sh
> Switch to Horizontalsystems Docker image

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
- app/src/main/res/layout/fragment_market.xml
- app/src/main/res/layout/fragment_market_search.xml
- app/src/main/res/menu/market_menu.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Search by title and code in markets

- app/src/main/res/layout/fragment_bottom_notification_menu.xml
- app/src/main/res/layout/view_holder_privacy_settings_section_description.xml
- app/src/main/res/layout/view_holder_privacy_settings_section_title.xml
- app/src/main/res/layout/view_holder_setting_item_with_switch.xml
- app/src/main/res/layout/view_holder_setting_with_dropdown.xml
- app/src/main/res/layout/view_settings_item_arrow.xml
> Get rid off FrameLayout in single child view layouts

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/FeeRateProviderFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeCoinProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
> Add fee rate provider for "Binance Smart Chain"

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapFragment.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_swap.xml
- app/src/main/res/layout/fragment_swap_settings.xml
> Fix bottom padding in Swap screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/FeeInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/FeeSelectorView.kt
- app/src/main/res/navigation/main_graph.xml
> Show fee speed info in FeeSelectorView

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListViewModel.kt
> Show default market field as Price in MarketsDiscovery

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
> Add blank space between number and its letter in Market tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
- app/src/main/res/layout/fragment_status_info.xml
- app/src/main/res/values/strings.xml
> Fix showing correctly transaction status

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
> Replace Zcash explorer

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
> Refresh Market data on page resume

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/erc20/AddErc20TokenResolver.kt
> Fix Add Erc20 token testnet Url

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceSmartChainKitManager.kt
> Upgrade EthereumKit (with implemented shared OkHttp client)

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricLargeView.kt
> Change the total-market-cap's gradient 3x faster

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
> Market data refresh on app foreground

- components/views/src/main/java/io/horizontalsystems/views/SettingsViewDropdown.kt
- components/views/src/main/java/io/horizontalsystems/views/SettingsViewSwitch.kt
> Fix the opening of Security Center screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ViewHolderMarketOverviewItem.kt
- app/src/main/res/layout/view_holder_market_overview_item.xml
> Fix item border in Market tab

- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/TextHelper.kt
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values/strings.xml
> Text changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
> WalletConnect: if chainId is NULL - fallback to Ethereum MainNet

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/InitialSyncSettingsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/bep2/AddBep2TokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/bep20/AddBep20TokenResolver.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/erc20/AddErc20TokenResolver.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/tradeoptions/SwapTradeOptionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
> Refactor Coinkit integration

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/TextHelper.kt
- app/src/main/res/layout/view_fee_selector.xml
- app/src/main/res/layout/view_holder_item_selector.xml
- app/src/main/res/layout/view_send_fee.xml
> Remove Medium fee speed, use Recommended instead

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestViewModel.kt
> Refactor balance error handling for EVM kits and modules

- app/src/main/res/values/strings.xml
> Change text

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsErc20Provider.kt
> Fix enabling Erc20 tokens with no balance

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchModule.kt
- app/src/main/res/layout/fragment_market_search_filter.xml
- app/src/main/res/values/strings.xml
> Market search

- app/build.gradle
> Upgrade xrate-kit dependencies (with added provider fallback for chart data)

- app/src/main/res/values/strings.xml
> Enabling tokens: change text

- app/build.gradle
> Upgrade xrate-kit dependencies (with fixed parsing errors)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapService.kt
> Enable selected tokens after success swap if they weren't enabled yet

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/bep2/AddBep2TokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep2Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsErc20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
> Auto activate users erc20/bep2/bep20 tokens

- app/src/main/res/layout/view_send_fee.xml
> Fix seekbar hint in Send page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/selector/ViewItemWrapper.kt
- app/src/main/res/layout/fragment_market_search_filter.xml
- app/src/main/res/menu/market_advanced_search_menu.xml
- app/src/main/res/values/strings.xml
> Market advanced search

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusService.kt
> Fix the issue with App Status page crash

- app/src/main/res/layout/view_fee_selector.xml
- app/src/main/res/layout/view_holder_market_overview_item.xml
> Fix long text layout

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
Ref #3260 #2962 #3356 #3006  #3242 
- Upgrade xrate-kit dependencies
- Integrate xrate-kit with implemented CoinGecko as Main provider for Charts, Histo and latest rates
> Upgrade and integrate xrate-kit (with provider impl. changes)

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchResultsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
> Use the App base currency for markets

- app/build.gradle
> Upgrade xrate-kit dependencies(with handled exceptions)

- app/build.gradle
> Update xrates-kit (requests with okhttp)

- app/build.gradle
> Update fee-rate-kit (requests with okhttp)

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/InitialSyncSettingsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt
> Update sorting logic in Coin pages

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
> Update ethereum-kit (bouncycastle provider registration fix)

- app/build.gradle
> Upgrade xrate-kit dependencies(with added funds data)

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationSubscriptionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/SubscriptionJobDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/SubscriptionJob.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationMenu.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationsMenuViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/NotificationBottomMenuModule.kt
> Make Price alerts work with new Coin model

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ViewHolderMarketOverviewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/CoinDataItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/noaccount/NoAccountDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListBaseFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/AppLayoutHelper.kt
> Use the coin type id for coin icon instead of coin code

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmAdapter.kt
> Show addresses in EIP55 format for eth

- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/AmountTypeSwitchServiceSendEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatServiceSendEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/AmountInputViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
> Fix validation of decimal count in AmountInputViewModel

- components/views/src/main/res/drawable-xhdpi/background_important_text.xml
- ui/src/main/res/values/colors.xml
> Set important text bg to yellow20

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapFragment.kt
- app/src/main/res/layout/fragment_swap.xml
> Add "Powered by" footer to Swap module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coininvestors/CoinInvestorCategoryAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coininvestors/CoinInvestorsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchResultsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/TextHelper.kt
- app/src/main/res/layout/coin_market_details.xml
- app/src/main/res/layout/fragment_coin.xml
- app/src/main/res/layout/fragment_coin_investors.xml
- app/src/main/res/layout/view_holder_coin_fund_item.xml
- app/src/main/res/layout/view_holder_coin_investors_section_header.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/drawable/tab_rounded_background.xml
- components/views/src/main/res/values/styles.xml
- Implement Coin Investors page
- Update Chart tabs layout
ref #3210
> Add Investors page to Coin page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- add extra spaces in AmountData formatting
- show full amount data with fiat value in send confirmation
> Minor enhancements in send module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketItemAdapter.kt
- app/src/main/res/drawable/rounded_image_background_4dp.xml
- app/src/main/res/layout/view_holder_market_item.xml
> Set the default icon for exchange in coin markets screen

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectSendEthereumTransactionRequestFragment.kt
> Add AppLogger to send-evm module

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/res/layout/view_holder_market_item.xml
> Coin screen update

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/res/values/strings.xml
> Add Fully Diluted Market Cap to Coin Page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/res/layout/fragment_coin.xml
- app/src/main/res/layout/fragment_guides.xml
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/layout/view_holder_filter.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartGridTimeline.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartIndicator.kt
- components/chartview/src/main/res/layout/view_chart.xml
- components/views/src/main/res/color/stateful_tab_text_color.xml
- components/views/src/main/res/values/styles.xml
> Coin page small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/res/navigation/main_graph.xml
> Open coin's guide page by CoinType

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketCategoriesAdapter.kt
- for old android versions setting translationY doesn't work without delay
#3346
> Fix market category animation

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
> Fetch latest rate and diff via separate method

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/CoinInfoItemView.kt
- add title and order to CoinPlatformType
- make decorated coin info item value copyable on click
#3210
> Minor changes in coin page

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationMenu.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationsMenuViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/NotificationBottomMenuModule.kt
> Fix bugs with PriceAlerts

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/res/layout/coin_market_details.xml
- app/src/main/res/values/strings.xml
> Coin page enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListBaseFragment.kt
> Fix BTC and BCH restore

- app/build.gradle
> Update xrates-kit (filter out tickers with zero rate or volume)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
> Fix category item background in coin page

- app/src/main/res/layout/view_holder_market_item.xml
> Handle long strings in CoinMarket sub fields

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinPerformanceView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/res/layout/view_coin_performance.xml
- hide btc and eth for respective coin's performance view
#3210
> Use app base currency in coin performance view

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketItemAdapter.kt
- app/src/main/res/layout/view_holder_market_ticker.xml
> Make separate layout for coin market item with squared icon

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ActivateCoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
- create ActivateCoinManager for activating coin by coin type
#3109
> Activate coin out after Swap

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- take transaction data from state
> Fix bug in SendEvmTransactionService

- app/build.gradle
> Update xrates-kit (ignore empty links for coin)

- app/src/main/java/io/horizontalsystems/bankwallet/entities/EthereumRpcMode.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Add BSC info in Privacy settings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketCategoriesAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
> Reset market category when opened from overview tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/res/layout/fragment_coin.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/views/src/main/res/color/button_third_bg.xml
- components/views/src/main/res/color/button_third_text.xml
> Coin chart small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/res/layout/coin_market_details.xml
- Show 'about' section text after lineCount computed, it is needed to prevent expanding and collapsing when returning to coin page
#3418
> Update categories section UI in coin page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
> Fix chart flicker on period change

- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep2Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsErc20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
- from providers return token smart contract addresses for Erc20/Bep20, and token symbol for Bep2
- enable only those coins that exist in coin-kit
#3433
> Enable coins module changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
> Make About text expandable when the lines count more than 10

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
> Update xrate-kit, add debounce to market search

- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsBep2Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsErc20Provider.kt
> Return distinct addresses/symbols form enable coin providers

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
> Fix the issue with drawing chart twice

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coininvestors/CoinInvestorsFragment.kt
- app/src/main/res/values/strings.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartBottomLabel.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartGridRange.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartGridTimeline.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- components/views/src/main/res/values/styles.xml
- Rename to Funds Invested in CoinPage
- Cancel previous request when fetching ChartInfo
- Show Chart Rsi number labels on the right side
ref #3421
> Small fixes for CoinPage and Chart

- app/build.gradle
> Upgrade tor-kit dependencies(with tor process fixes)

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
> Fix PriceAlert notification topic subscription

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AmountInputView.kt
- Open send screen from bottom
> Show keyboard in AmountInputView.setFocus()

- app/src/main/res/layout/fragment_market_favorites.xml
> Fix tabs bottom padding in Market WatchList

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmFragment.kt
> Open keyboard with delay in SendEvmFragment

- components/views/src/main/res/values/themes.xml
> Use Tyler color for splash screen background

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListViewModel.kt
> Open QR scanner when opening WalletConnect with empty list

- app/build.gradle
> Update xrates-kit (fix BNB exchange rate)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
> Fix notification coin duplicates in Settings

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationSubscriptionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/notifications/NotificationNetworkWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/SubscriptionJob.kt
> Fix Notification subscription process

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/notifications/NotificationNetworkWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/notifications/NotificationWorker.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
> Make fixes in notification worker

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketFilterSwitchView.kt
- app/src/main/res/layout/fragment_market_search_filter.xml
- app/src/main/res/layout/view_market_filter_switch.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
> Add filters to Markets Advanced Search

- app/build.gradle
> Upgrade xrate-kit dependencies(with GlobalMarket provider changes)

- app/build.gradle
> Upgrade xrate-kit dependencies(with methods for GlobalMarkets charts)

- app/src/main/res/drawable/bottom_button_top_fading.xml
- app/src/main/res/layout/fragment_market_search_filter.xml
- components/views/src/main/res/values/themes.xml
- ui/src/main/res/values-night/colors.xml
- ui/src/main/res/values/colors.xml
> Add fading background to button in Market Advanced Search

- app/build.gradle
> Upgrade xrate-kit dependencies(with DefiMarkets provider changes)

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppVersionManager.kt
> Store app version only on App init

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricSmallView.kt
- app/src/main/res/layout/fragment_coin.xml
- app/src/main/res/layout/view_holder_market_totals.xml
- app/src/main/res/layout/view_market_metric_small.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartGradient.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartMinimal.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/PointConverter.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- components/chartview/src/main/res/layout/view_chart_minimal.xml
- components/chartview/src/main/res/values/attrs.xml
> Add small chart to Overview Metrics

- app/build.gradle
> Upgrade xrate-kit dependencies(with provided TVL, defi data)

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceSmartChainKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/ConfiguredCoin.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountService.kt
> Bug fix in adapter 'unlinking'

- app/build.gradle
> Upgrade xrate-kit dependencies and remove GMS plugin

- app/src/main/res/layout/fragment_balance.xml
- app/src/main/res/layout/fragment_manage_account.xml
- app/src/main/res/layout/fragment_manage_accounts.xml
- app/src/main/res/layout/view_holder_manage_account_action.xml
> Manage accounts minor UI fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt
> Do not require backup on wallet unlink

- app/src/main/res/layout/fragment_theme_switcher.xml
- app/src/main/res/layout/fragment_wallet_connect_list.xml
- components/currencyswitcher/src/main/res/layout/fragment_currency_switcher.xml
> Fix toolbar title font style in settings pages

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusService.kt
> Show statuses for all coin settings variants in AppStatus module

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RestoreSettingsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSettingsService.kt
> Show Zcash birthday height dialog in ManageWallets module

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_31_32.kt
> Add migration to convert wallet into multiwallet

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainModule.kt
> Show Settings when user cancels WalletConnect QR scan

- app/src/main/java/io/horizontalsystems/bankwallet/core/SearchViewHelper.kt
> Hide magnifier icon in the beginning of hint of the search box

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/res/values/strings.xml
> Remove company social media links

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Fix showing the selected tab

- app/src/main/res/layout/view_holder_market_totals.xml
> Make Total Market Cap circle smaller

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownBlockViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownContentAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/guides/GuidesViewModel.kt
> Fix markdown url parsing in FAQ pages

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/res/values/strings.xml
> Add TVL rank and M.cap ratio to Coin page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketItemAdapter.kt
- app/src/main/res/layout/view_holder_market_ticker.xml
- app/src/main/res/values/strings.xml
> Add Launch date to CoinPage  and load icons in Coin Market page

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MnemonicPhraseView.kt
- app/src/main/res/layout/view_mnemonic_phrase.xml
> Group mnemonic phrase by 3 for 12-words and by 4 for 24-words

- app/build.gradle
- app/src/main/res/layout/fragment_confirmation_send_evm.xml
- app/src/main/res/layout/fragment_confirmation_swap.xml
> Ui fixes and version name incrementing

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchViewModel.kt
> Set default values for recently added parameters on reset click

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PassphraseValidator.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupconfirmkey/BackupConfirmKeyFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoremnemonic/RestoreMnemonicFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoremnemonic/RestoreMnemonicModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoremnemonic/RestoreMnemonicService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoremnemonic/RestoreMnemonicViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputView.kt
- app/src/main/res/values/strings.xml
> Add passphrase validation to create/restore account modules

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/RootUtil.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/rooteddevice/RootedDeviceActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/rooteddevice/RootedDeviceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/rooteddevice/RootedDeviceViewModel.kt
- app/src/main/res/layout/activity_rooted_device.xml
- app/src/main/res/values/strings.xml
- components/keystore/src/main/java/io/horizontalsystems/keystore/BaseKeyStoreActivity.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreInteractor.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreModule.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStorePresenter.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreViewModel.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Allow user to ignore RootedDevice warning

- app/src/main/res/values/strings.xml
> Make Text Changes

- app/src/main/res/values/strings.xml
- components/keystore/src/main/res/values/strings.xml
> Change alert text

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Upgrade xrate-kit dependencies(with updated json files)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeView.kt
- app/src/main/res/layout/view_send_fee.xml
- app/src/main/res/values/strings.xml
> Show low fee warning in send module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
- app/src/main/res/layout/activity_qr_scanner.xml
- app/src/main/res/values/strings.xml
> Fix permission handling in QR scanner activity

- app/build.gradle
> Update bitcoin-kit (handle failed transactions)

- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumFeeViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/FeeSelectorView.kt
- app/src/main/res/layout/view_fee_selector.xml
> Show low fee warning in EthereumFeeViewModel

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/CoinInfoItemView.kt
- app/src/main/res/layout/view_coin_info_item.xml
- app/src/main/res/values/strings.xml
> Rename Coin Market to Trading Volume

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeCoinProvider.kt
> Fix bep2 fee coin

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Update the logic for rounding coin values

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/CoinDataItemsAdapter.kt
> Correct search result list display ordering

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> Update xrates-kit (with updated schedulers)

- app/src/main/java/io/horizontalsystems/bankwallet/core/BaseFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/ShowBackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyMainFragment.kt
- core/src/main/java/io/horizontalsystems/core/CoreActivity.kt
> Disallow screenshot only in show key screens

- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatServiceSendEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/AmountInputViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AmountInputView.kt
- app/src/main/res/layout/view_input_amount.xml
> Show fiat as yellow in amount inputs

- app/build.gradle
> Upgrade xrate-kit dependencies(with JSON files updated)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> Subscribe the fee coins along with wallet coins for xrates

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CurrencyManager.kt
> Set the default currency to "USD"

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceSmartChainKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
> Update ethereum-kit and integrate new tx sync logic

- app/src/main/java/io/horizontalsystems/bankwallet/entities/CurrencyValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinViewHolder.kt
- app/src/main/res/layout/view_holder_swap_coin_select.xml
- core/src/main/java/io/horizontalsystems/core/entities/Currency.kt
> Show fiat balances in swap token selector

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartFragment.kt
- core/src/main/AndroidManifest.xml
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Add vibration for tap on charts and hide show balance

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartFragment.kt
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Use predefined vibration effect for API level >= 29

- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartFactory.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
> Handle no changes in values for Charts

- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsDialog.kt
> Fix icon in Add token dialog

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
> Remove coin icon tinting

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketMetricSmallView.kt
- app/src/main/res/layout/view_market_metric_small.xml
- set background using separate View
#3672
> Fix dark mode background not setting in MarketMetricSmallView

- build.gradle
> Fix a memory leak in fragments caused by mFocusedView

- app/build.gradle
> Upgrade xrate-kit dependencies(with adjusted Chart points)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metrics/MarketMetricsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostService.kt
- Fetch Market Posts on refresh click and onForeground
- Show error toast once per error in Market Overview
ref #3681
> Market overview error toast fix

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
> Parse 2 types of coin description - html and markdown

- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsFragment.kt
- app/src/main/res/layout/fragment_manage_accounts.xml
- app/src/main/res/layout/view_holder_manage_accounts_hint.xml
- app/src/main/res/values/strings.xml
> Add hint to manage wallets screen

- app/src/main/res/layout/fragment_create_account.xml
- app/src/main/res/layout/fragment_restore_mnemonic.xml
- app/src/main/res/values/strings.xml
> Change passphrase hint text in wallet restore screen

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
> Coin about markdown

- app/build.gradle
> Update bitcoin-kit (checkpoints)

- app/build.gradle
> Update xrates-kit (fix parsing of CoinGecko response)

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletConnectInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectRequest.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectSendEthereumTransactionRequestFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectSendEthereumTransactionRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectSendEthereumTransactionRequestViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectDisplayTypedMessageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestViewModel.kt
- app/src/main/res/layout/fragment_wallet_connect_display_typed_message.xml
- app/src/main/res/layout/fragment_wallet_connect_sign_message_request.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
Add support for personal_sign, eth_sign, eth_signTypedData
#3537
> Wallet Connect: add ability to sign message

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
> Trim whitespace from url

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ViewHolderMarketOverviewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/CoinDataItemsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/AppLayoutHelper.kt
> Use corresponding coin placeholder icons

- app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroViewPagerAdapter.kt
- app/src/main/res/values/strings.xml
> Update Intro screen texts

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
> Hide chart spinner on "No data" error

- build.gradle
> Gradually migrate from jcenter to mavenCentral

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectRequestManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/res/layout/fragment_wallet_connect_list.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/navigation/wallet_connect_graph.xml
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/LockManager.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Handle walletconnect deeplinks

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_32_33.kt
> Set default values for BTC, LTC and BCH settings

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
> Update bitcoin-kit (with increased timeout for sending tx)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
> Revert modifications

- app/build.gradle
> Set appropriate version code and name

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
> Set state of tx tab selector based on data right from DB not cached

- app/src/main/res/layout/view_holder_balance_item.xml
> Make ui fixes in Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
> Balance preserve viewmodel state

- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsFragment.kt
> Fix extra margins in ManageWallets page when wallets are empty

- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/AppLayoutHelper.kt
> Use icon placeholder for coins with unknown coin type

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
> Change the categorization order

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
> Remove number of words limitation check for Dash

- app/build.gradle
> Set version code and name

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
> Show coin codes in Uppercase in Market search page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinChartAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinInfoErrorAdapter.kt
- app/src/main/res/layout/view_holder_coin_error.xml
- app/src/main/res/values/strings.xml
- components/chartview/src/main/res/layout/view_chart.xml
> Handle no data error in Coin page

- app/build.gradle
> Update xrates-kit (with updated coin-kit)

- components/snackbar/src/main/java/io/horizontalsystems/snackbar/CustomSnackbar.kt
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Fix crash with CustomSnackbar in Market pages

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinChartAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinSubtitleAdapter.kt
- app/src/main/res/layout/view_holder_coin_subtitle.xml
> Coin page chart fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
- app/src/main/res/layout/view_holder_balance_item.xml
> Show coin codes instead of coin names in Balance tab

- app/src/main/res/values/strings.xml
> Change the text "Launch Date"

- app/build.gradle
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
- Fix trading volume chart
- Fix chart not vibrating continuously when user moves finger
ref #3639
> Implement fixes for chart in coin page

- app/src/main/res/layout/fragment_receive.xml
- app/src/main/res/menu/receive_menu.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/drawable/rounded_8.xml
> Receive screen enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceSmartChainKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/networksettings/NetworkSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/networksettings/NetworkSettingsViewModel.kt
- app/src/main/res/layout/view_holder_balance_item.xml
- components/icons/src/main/res/drawable/testnet.xml
> Testnet badge

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PassphraseValidator.kt
> Update passphrase symbols

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinLinksAdapter.kt
- app/src/main/res/layout/fragment_market_global.xml
- app/src/main/res/values/strings.xml
- Show powered by DefiLlama in Metric charts
- Show twitter account name and web link in Coin Page
ref #3639
> Implement changes to Coin page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsViewModel.kt
- app/src/main/res/layout/view_holder_balance_item.xml
- app/src/main/res/layout/view_holder_privacy_settings_section_description.xml
- app/src/main/res/layout/view_holder_privacy_settings_section_title.xml
- app/src/main/res/values/strings.xml
- Remove communication mode in Privacy Settings, ref #3835
- Fix diff rate padding in Balance coin card, ref #3840
> Remove communication mode

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketItemAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchResultsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/EmptyListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketListHeaderView.kt
- app/src/main/res/layout/fragment_coin_markets.xml
- app/src/main/res/layout/view_holder_market_ticker.xml
- app/src/main/res/layout/view_market_list_header.xml
> Implement sorting in Coin markets page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Use literal value for VersionCode in gradle.build

- app/build.gradle
> Fix VersionCode for AppCenter in gradle.build

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Update  fix of VersionCode setting for AppCenter in gradle.build

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/ApiError.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddBep2TokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt
- app/src/main/res/values/strings.xml
> Refactor code in AddToken module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/TestnetDisclaimerDialog.kt
- app/src/main/res/layout/fragment_disclaimer.xml
- app/src/main/res/values/strings.xml
> Show disclaimer when user selects testnet network

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CurrencyManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EnabledWalletsCacheDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EnabledWalletsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_34_35.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/EnabledWallet.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/EnabledWalletCache.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Wallet.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAdapterRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCache.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService2.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceXRateRepository.kt
> Balance module optimization

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restoremnemonic/RestoreMnemonicFragment.kt
> Restore toggle button's state when entering passphrase

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AmountInputView.kt
- app/src/main/res/drawable/ic_coin_placeholder.xml
- app/src/main/res/layout/view_card_swap.xml
- app/src/main/res/layout/view_input_amount.xml
> Swap improvements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListViewModel.kt
> Fix sorting coin markets

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FaqManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Faq.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/faq/FaqViewModel.kt
- app/src/main/res/layout/fragment_faq_list.xml
- app/src/main/res/layout/view_holder_faq_section.xml
> Fetch and display FAQ with sections

- app/build.gradle
- build.gradle
- components/chartview/build.gradle
- components/icons/build.gradle
- components/keystore/build.gradle
- components/languageswitcher/build.gradle
- components/pin/build.gradle
- components/seekbar/build.gradle
- components/snackbar/build.gradle
- components/views/build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- ui/build.gradle
- Remove buildToolsVersion
- Set gradle version to 6.7.1
ref #3800
> Fix gradle to solve issue with jcenter libraries error

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/providerselect/SelectSwapProviderDialogFragment.kt
- app/src/main/res/layout/fragment_confirmation_approve_swap.xml
- app/src/main/res/layout/fragment_swap_select_token.xml
- app/src/main/res/layout/view_holder_title_value_hex.xml
> UI improvements and bug fixes in Swap module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapAllowanceStepsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapAllowanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapPendingAllowanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- app/src/main/res/drawable/swap_approve_steps_background.xml
- app/src/main/res/layout/fragment_1inch.xml
- app/src/main/res/layout/fragment_uniswap.xml
- app/src/main/res/layout/view_swap_approve_steps.xml
> Add approve steps to swap

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankItemAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankLoadingAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/TvlRankListHeaderView.kt
- app/src/main/res/layout/fragment_tvl_rank.xml
- app/src/main/res/layout/view_holder_market_ticker.xml
- app/src/main/res/layout/view_holder_tvlrank_loading.xml
- app/src/main/res/layout/view_tvlrank_list_header.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Implement coin TVL Rank page

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSwapSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapModule.kt
- add testnet support check for swap providers
#3880
> Handle testnet in swap module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapTradeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- do not hide approve action and steps on tradeService.Loading state
> Sync swap trade service on new block

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
> Fix OutOfMemory exception in Transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketCategory.kt
- app/src/main/res/drawable/ic_data_storage.xml
- app/src/main/res/drawable/ic_decentralized_identity.xml
- app/src/main/res/values/strings.xml
> Add new categories

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ZcashBirthdayProvider.kt
> Zcash and swap fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
> Reset "you pay" amount when coin is changed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt
- app/src/main/res/values/strings.xml
> Show hud messages when adding/deleting wallet/watchlist

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/discovery/MarketDiscoveryService.kt
> Add missing market categories and apply order from coins.json

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/SwapDeadlineViewModel.kt
> Do not set initial value as null in SwapDeadlineViewModel

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoAddressMapper.kt
> Migrate to PancakeSwap V2

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/BaseSwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
- app/src/main/res/layout/fragment_confirmation_approve_swap.xml
- app/src/main/res/layout/fragment_confirmation_send_evm.xml
- app/src/main/res/layout/fragment_confirmation_swap.xml
- app/src/main/res/navigation/main_graph.xml
> Change navigations in swap and send-evm modules

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
> Remove 'vs BNB' from ROI list

- Gemfile.lock
> Update "addressable" gem to version 2.8.0

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapFromCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapToCoinCardService.kt
- app/src/main/res/layout/fragment_swap_select_token.xml
- app/src/main/res/values/strings.xml
- remove unused parameters in SwapCoinProvider
- change select coin screen title
> Minor changes in coin card module

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsViewModel.kt
> Sorting coin markets by volume and switching volume's currency

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/WalletConnectSessionDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/WalletConnectSessionStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectSessionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListViewModel.kt
> Add support for Ethereum testnets in Wallet Connect

- app/src/main/res/values/strings.xml
> Change text for tx status info

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletConnectInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainViewModel.kt
- app/src/main/res/layout/fragment_wallet_connect_main.xml
> Wallet connect failures handling

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/SwapTransactionRecord.kt
> Add 1inch decorations

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinIncomingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinOutgoingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ApproveTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCreationTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmIncomingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmOutgoingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/SwapTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/layout/view_holder_transaction_info_item.xml
- app/src/main/res/layout/view_transaction_info_status.xml
- app/src/main/res/values/strings.xml
- Move TransactionType creation from TransactionRecord classes to TransactionsViewItemFactor
- Add "foreignRecipient" parameter to SwapTransactionRecord to be able to show the return value in grey color
- Add "foreignTransaction" parameter to EvmTransactionRecord to have "fee" row for all own EVM transactions
ref #3678
> Bitcoin transactions info page

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/PoweredByAdapter.kt
- app/src/main/res/layout/view_holder_market_powered_by.xml
- app/src/main/res/values/strings.xml
> Apply filtering by chain in Defi TVL list view

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/RecyclerSectionItemDecoration.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSectionHeader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/recycler_section_header.xml
> Show date for transactions as section header

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSectionHeader.kt
- core/src/main/res/values/strings.xml
> Use TODAY, YESTERDAY strings in formatting date in transactions tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/res/layout/view_holder_coin_audit_item.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Display coin audits in security params section

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/res/values/strings.xml
> Change text for tx status info and change order for Security Parameters-Privacy

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewPagerAdapter.kt
> Enhancements

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinServiceFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewItemHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
> Integrate 1inch transaction decorations into sendevm module

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseEvmAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsEip20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/Pool.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/PoolRepo.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionMetadataDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- Use filters for getting transactions from Kits
- Remove unused logs
ref #3678
> Use EvmTransactionsAdapter in Transactions module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/res/values/strings.xml
> Transaction tab fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- Activate both coins after swap
#3678
> Fix swap transaction confirmation page 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsService.kt
> Ignore words number when auto enabling tokens

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersPieAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/SemiCircleView.kt
- app/src/main/res/layout/view_holder_coin_major_holders_pie.xml
- app/src/main/res/values/strings.xml
> Implement SemiCircleView for MajorHolders pie chart

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/binancechain/BinanceChainIncomingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/binancechain/BinanceChainOutgoingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/binancechain/BinanceChainTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinIncomingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinOutgoingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Implement BinanceChain transaction decorations

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
> Update transfer fee for Binance setting it to 0.000075

- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/res/values/strings.xml
> Add service cell for Swap transactions in transactions info

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
> Handle failed and reverted cases for swap transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/InfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/res/layout/fragment_info.xml
- app/src/main/res/layout/view_transaction_info_item.xml
> Update design for DoubleSpend info page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSectionHeader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/view_holder_transaction_info_item.xml
- app/src/main/res/values/strings.xml
> Transaction small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSectionHeader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
> Fix small bugs in transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coininvestors/CoinInvestorsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/releasenotes/ReleaseNotesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/info/SwapInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/LinkHelper.kt
> Open links in App browser

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
> Implement partial update of transactions list

- app/build.gradle
> Update EthereumKit to get fix for transaction logs

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateAppManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutViewModel.kt
- Fix opening Play Store via RateAppManager
- Fix bugs in Rate Us showing logic
ref #3988
> Fixes for Rate Us

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
> Disable Restore done button when coins auto enabler is working

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/memo/SendMemoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/memo/SendMemoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/memo/SendMemoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/memo/SendMemoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZcashHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZcashInteractor.kt
- app/src/main/res/layout/view_send_memo.xml
> Show Memo field only for Shielded ZCash addresses in Send

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceItemViewHolder.kt
> Fix hidden sync text on Expanded wallet

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsViewModel.kt
- app/src/main/res/values/strings.xml
> Fetch coins audits only when visiting CoinAudits page

- app/build.gradle
> Update x-rates-kit with error handling of empty coin-audits

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransaction.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
> Fix ZCash empty memo field in Transaction Info module

- app/build.gradle
> Update eth-kit (checking pending txs on each block)

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/res/values/strings.xml
> Handle Infura Lower than Base Gas Limit fee error

- app/build.gradle
> Update EthereumKit dependency

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
> Fix confirmation screen items for sending ETH/BNB

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/res/values/strings.xml
> Handle "cannot estimate" 1inch error

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/views/SyncErrorDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/basecurrency/BaseCurrencyDisclaimerDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/TestnetDisclaimerDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/BaseSwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionSpeedUpCancelFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectErrorFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Button.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ConfirmationDialog.kt
- app/src/main/res/layout/fragment_1inch.xml
- app/src/main/res/layout/fragment_confirmation_approve_swap.xml
- app/src/main/res/layout/fragment_confirmation_swap.xml
- app/src/main/res/layout/fragment_disclaimer.xml
- app/src/main/res/layout/fragment_swap_approve.xml
- app/src/main/res/layout/fragment_swap_settings_1inch.xml
- app/src/main/res/layout/fragment_swap_settings_uniswap.xml
- app/src/main/res/layout/fragment_transaction_speedup_cancel.xml
- app/src/main/res/layout/fragment_uniswap.xml
> Replace primary buttons with Compose buttons 

- app/build.gradle
> Update bitcoin kit (fixes syncing)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchTransactionFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchKitHelper.kt
- app/src/main/res/values/strings.xml
> Add retry for 1inch confirmation module

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionAdapterWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/res/layout/fragment_transactions.xml
> Type filtering eth

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletConnectInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectSessionKillManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainViewModel.kt
- app/src/main/res/layout/fragment_wallet_connect_main.xml
- app/src/main/res/values/strings.xml
> WalletConnect: add new states, handle errors properly

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionAdapterWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSectionHeader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
> Transactions improvements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
> Fix restoring of selected tab state in filter tx type tabs

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/main/WalletConnectMainViewModel.kt
- app/src/main/res/values/strings.xml
> WalletConnect enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationFragment.kt
> AppLogger minor fixes

- app/src/main/res/values/strings.xml
> Add description texts for tx speedUp/cancel screens

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
> Implement filtering txs by type in binance chain

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EthereumFeeViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmTransactionFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchTransactionFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionSpeedUpCancelViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
- app/src/main/res/values/strings.xml
> Handle swap errors

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
> Display fiat price in swap transaction info

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupconfirmkey/BackupConfirmKeyFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/BaseSwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionSpeedUpCancelFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WalletConnectSendEthereumTransactionRequestFragment.kt
- app/src/main/res/values/strings.xml
- components/views/src/main/res/anim/slide_from_left.xml
- components/views/src/main/res/anim/slide_from_right.xml
- components/views/src/main/res/anim/slide_to_left.xml
- components/views/src/main/res/anim/slide_to_right.xml
> Change the animation speed time and rename "snackbar"

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
> Implement filtering txs by type in bitcoin

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransaction.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransactionsProvider.kt
> Txs filtering

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionAdapterWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt
> Preserve selected filter type when switching accounts or adding coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/guides/GuidesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabRow.kt
> Use generic items as parameters for composable tabs

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinSubtitleAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonCircle.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputView.kt
- app/src/main/res/layout/fragment_create_account.xml
- app/src/main/res/layout/view_holder_coin_subtitle.xml
- app/src/main/res/layout/view_input.xml
- components/views/src/main/res/values/styles.xml
> Replace remaining Secondary Image buttons with compose

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/tabs/ShowPrivateKeyTab.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ConfirmationDialog.kt
- app/src/main/res/values/strings.xml
> Show warning dialog when copying "private key"

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAdapterRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt
- for Zcash progress can be known while lastBlockDate is not. So that for such cases show just progress percentage without "synced until" text
#4099
> Make AdapterState.Syncing progress field optional

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RotatingCircleProgressView.kt
> Fix syncing progress in balance view item

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/res/layout/view_holder_transaction_info_explorer.xml
> Transaction info updates

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketListHeaderView.kt
- use Box to set modifiers externally
> Remove row modifier from ButtonSecondaryTransparent

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tvlrank/TvlRankFragment.kt
> Fix showing list from top on sorting change in TVL Rank

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
> Make small refactoring in Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionSyncStateRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
> Extract handling selected coin and type into TransactionFilterService

- app/src/main/res/layout/view_holder_transaction.xml
> Limit the amount text width in transaction cell

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinPlatformsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinsettings/CoinSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BaseBottomSheetDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultipleDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListBaseFragment.kt
- app/src/main/res/values/strings.xml
> Bug fixes and UI changes

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListAdapter.kt
> Update market kit

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabRow.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MarketListHeaderView.kt
- app/src/main/res/layout/fragment_market_advanced_search_results.xml
> Market UI fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
> Sort by coin code for Name

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsViewModel.kt
> Scroll coin list to top on sorting and top market change in MarketTopCoinsFragment

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryViewModel.kt
> Implement list scroll to top in MarketCategoryFragment

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/LaunchPage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/launch/LaunchPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/launch/LaunchPageModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/launch/LaunchPageService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/launch/LaunchPageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/AppBar.kt
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
- components/icons/src/main/res/drawable/ic_market_20.xml
- components/icons/src/main/res/drawable/ic_screen_20.xml
- components/icons/src/main/res/drawable/ic_settings_20.xml
> Implement selectable Launch Screen

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RestoreCustomTokenWorker.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/AppBar.kt
> Restore custom token worker

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CardTabs.kt
> Make UI fixes in Transactions coin filter box

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/DataState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/ViewState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/Tweet.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/TweetsPageResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/TweetsProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/TwitterUser.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Colors.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CellTweet.kt
- app/src/main/res/values/strings.xml
- components/icons/src/main/res/drawable/play_48.xml
> Coin tweets

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/res/layout/fragment_market_search_filter.xml
- app/src/main/res/values/strings.xml
- Show sort by balance as default sorting #4256,
- Rename market Advanced Search to Filters #4252
> Make small fixes in Balance sorting

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListBaseFragment.kt
> Scroll to top after auto-enabling coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Show circular progress on balance using Android custom view

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchMenuService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchResultsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchResultsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesMenuService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/IMarketListMenu.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/list/MarketListViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageListViewModel.kt
> Watchlist preserve menu selection

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
> Fix empty balance screen issue

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/InitialSyncSettingsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/CustomTokenDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/CustomTokenStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/ISwapCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapFromCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapToCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinViewModel.kt
- components/views/src/main/res/values/styles.xml
> Apply correct limit and filtering logic to coin list in Swap

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/CoinOverviewScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ui/CoinScreenTitle.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/HSSwipeRefresh.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Coin page UI

- app/build.gradle
> Fix Market ticker rates

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostsViewModel.kt
- app/src/main/res/layout/fragment_market_favorites.xml
- app/src/main/res/layout/fragment_market_posts.xml
> Show standard sync error page in MarketPosts and MarketFavorites modules

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Scroll to top on balance page after sorting has changed

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt
> Fetch data based on currency

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CellTweet.kt
- app/src/main/res/values/strings.xml
> Update tweet reference style

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
> UI bug fixes

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Tab.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabButton.kt
- app/src/main/res/layout/coin_chart.xml
- app/src/main/res/layout/fragment_market_global.xml
- Fix Secondary button height
- Show top border when user touches chart
- Change powered by source
#4136
> Fix UI bugs in CoinPage

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/theme/ThemeSwitchViewModel.kt
- Fix app showing Market tab first then Balance tab
#4237
> Relaunch app on Settings tab when user changes theme or language

- app/src/main/java/io/horizontalsystems/bankwallet/modules/basecurrency/BaseCurrencyDisclaimerDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/TestnetDisclaimerDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/BackupRequiredDialog.kt
> Fix crash on currency change from secondary list

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmNetworkManager.kt
> Temporarily disable Ethereum test networks

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
> Show coin full rate on Coin page and Balance page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsFragment.kt
- app/src/main/res/values/strings.xml
> Rename Show more to See on Twitter in CoinPage

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/ISwapCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapToCoinCardService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Color.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Colors.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TextImportant.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/AmountInputView.kt
- app/src/main/res/layout/view_input_amount.xml
- app/src/main/res/values/strings.xml
> Swap price impact updates

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/entities/ViewState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/res/values/strings.xml
> Coin details main page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/SwapSlippageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputWithButtonsView.kt
- app/src/main/res/values/strings.xml
> Show price slippage warning on swap settings screen

- app/build.gradle
> Update market-kit (with caching)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/marketglobal/MarketGlobalFetcher.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartModule.kt
- app/src/main/res/layout/coin_chart.xml
- app/src/main/res/values/strings.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartDataFactory.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/Indicator.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/PointConverter.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/PointInfo.kt
> Add BTC dominance line to Total Market Cap chart

- app/build.gradle
> Update MarketKit with updated database dump

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/AppBar.kt
- app/src/main/res/layout/fragment_recyclerview.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Coin details subpages: major holders, tvl, treasuries, investments

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatServiceSendEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CustomToken.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService2.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
> Do not request latest rates for custom coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsViewModel.kt
> Do not allow setting slippage to 0 in swap settings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
- app/src/main/res/values/strings.xml
> Show charts in Coin Overview -> Details

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt
> Update search and syncing logic for coins

- app/src/main/java/io/horizontalsystems/bankwallet/entities/DataState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/ViewState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/CoinOverviewScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/reports/CoinReportsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/reports/CoinReportsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt
- app/src/main/res/values/strings.xml
> Show appropriate message for twitter account missing in coin screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/EmptyListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/res/layout/fragment_market_favorites.xml
> Fix coin favorites list scrolled to bottom on initial load

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonPrimary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabButton.kt
> Use dark text color in yellow buttons

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsViewModel.kt
> Preserve list position in MarketTopCoins, Category pages

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonPrimary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabButton.kt
> Set text color to dark for yellow buttons

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchKitHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt
- app/src/main/res/values/strings.xml
> Handle new errors for 1inch

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoAddressMapper.kt
> Update 1inch Router API to v4

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
> On BalanceFragment error click open NetworkSettings

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/res/values/strings.xml
> Update icon urls, sort audits by date

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
> Set production api base url for markets

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
> Fix null capRank label showed in coin list

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsViewModel.kt
> Update market-kit, minor bug fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/adapters/CoinChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTvlFetcher.kt
> Tabs enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchViewModel.kt
- app/src/main/res/values/strings.xml
> Set ranges based on currency

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/About.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/DescriptionMarkdown.kt
> Parse markdown in About section of Coin Overview

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinServiceFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsRateRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
> Use historical rates from MarketKit

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
> Show Market Overview after Onboarding screen

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsViewModel.kt
> Show amount for Funds Invested in USD currency

- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTradingVolumeFetcher.kt
> Filter chart points earlier that startTimestamp

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/LinkHelper.kt
- app/src/main/res/values/strings.xml
> Make fixes in coin investment page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketMetricsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartFragment.kt
> Update tvl chart according to selected chain, update market kit urls

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
> Pass 'hsApiKey' to market-kit

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionAdapterManager.kt
> Fix stopping of evm kit by fixing its usage counter

- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsEip20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
> Skip key for enable coins request to apply IP based limitation

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt
Eip20Kit starts automatically after EthereumKit becomes synced
#4418
> Do not start eip20Kit manually

- app/build.gradle
> Upgrade Marketkit with updated CoinPriceResponse

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/EvmNetwork.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkViewModel.kt
- app/src/main/res/layout/view_holder_description.xml
- app/src/main/res/values/strings.xml
> Show all RPC hosts for BSC

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsModule.kt
- Set version code to 55
- Set version name to 0.23.1
> Handle optional Coin Audit Report links

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/AddressResolutionProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/AddressResolutionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSwapSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsModule.kt
> Update unstoppable domains

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/UnknownSwapTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Handle 1Inch V4 contract methods

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
> Fix 'from' field in EvmIncomingTransactionRecord

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Make transactions scroll to the bottom smoother

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseEvmAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WalletConnectRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WalletConnectSignMessageRequestService.kt
> Integrate updated EthereumKit and Signer structure

- app/build.gradle
- build.gradle
After small changes in code AndroidStudio gives error when trying to build 
` IllegalStateException: Symbol for kotlin.collections/mutableMapOf...`
> Degrade kotlin and kotlinCompilerExtension

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AutoEnableTokensService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletActivator.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EnabledWalletsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EnabledWalletsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EvmAccountStateDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_36_37.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/EvmAccountState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoins/EnableCoinsEip20Provider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
> Auto enable tokens

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/res/values/strings.xml
> Make transaction type names translatable

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetMarketSearchFilterSelectMultipleDialog.kt
- app/src/main/res/layout/fragment_market_search_filter.xml
- app/src/main/res/values/strings.xml
> Add Blockchains filter to MarketAdvancedSearch module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/SendEvmViewModel.kt
- app/src/main/res/values/strings.xml
> Show warning when all ETH/BNB balance amount is being sent

- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/BackupRequiredDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectErrorNoAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectErrorWatchAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TextImportant.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultipleDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ConfirmationDialog.kt
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Wallet connect account handler

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSwapProviderSelectDialog.kt
- app/src/main/res/values/strings.xml
> Change title and subtitle in Swap Provider dialog

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsModule.kt
> Fix Binance logo in Restore screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/UnlinkConfirmationDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetWalletSelectDialog.kt
- app/src/main/res/values/strings.xml
> Change unlink confirmation popup for Watch account

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartNumberFormatterShortened.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartNumberFormatterSignificant.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlChartViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartTvlModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartVolumeModule.kt
> Show correct TVL Data when filtered by blockchain

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ReleaseNotesManager.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/VersionTest.kt
> Show release notes with app version without patch number

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsModule.kt
> Show labels for tokens on single chain in Manage Coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/BackupRequiredDialog.kt
- app/src/main/res/values/strings.xml
> Change BackupRequired description text

- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchFeeService.kt
> Evm fee settings & swap confirmation changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/ShowBackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyMainFragment.kt
> Disallow screenshot in ShowBackupWords and ShowKeyMain fragments

- app/src/main/res/values/strings.xml
> Apply new text

- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559GasPriceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt
- add 'minGasPrice','initialGasPrice' params
#4606
> Refactor Eip1559GasPriceService params

- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevm/confirmation/SendEvmConfirmationModule.kt
surcharge gasLimit for Erc20/Bep20
> Do not surcharge gasLimit when sending ETH/BNB

- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftAssetItemsPricedRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftAssetItemsPricedWithCurrencyRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftAssetItemsRepository.kt
> Avoid empty initial values with SharedFlow

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
> Add warning style error in FormsInput

- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/INftApiProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt
- app/src/main/res/values/strings.xml
> Add 'sale' and 'order' information in NftAsset page

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftAssetRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftCollectionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftPreview.kt
> Nft Asset Page enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
- app/src/main/res/values/strings.xml
> Change texts on "Add Token" and "Coin search" input placeholders

- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartMinimal.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/CurveAnimator.kt
> Set chart curve top padding to 0 for ChartMinimal

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Wallet.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartPointsWrapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinPerformanceRowView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Roi.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/advancedsearch/MarketAdvancedSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketMetricsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTradingVolumeChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTvlChartService.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/GridHelper.kt
- Add new coin type Polygon
- Update Chart data to use HsProvider in MarketKit 
#4581
> Make changes by updated Marketkit 

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
> Fix ZEC amount convertion bug

- app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/PointConverter.kt
> Unstoppable domains multichain address

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
There was a case when recycling back to chart it was empty. Fix by drawing chart only after it has been layed out
#4559
> Fix chart drawing in LazyColumn item

- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/tabs/ShowPrivateKeyTab.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
> Show primary key in 2 lines

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
> Use Tor without foreground service

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
> Handle transactions for coin category description

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
> Fix chart drawing in MiniChartCard

- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
> Show BTC dominance value on point holding

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/audits/CoinAuditsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/investments/CoinInvestmentsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/CoinOverviewScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/reports/CoinReportsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/tweets/CoinTweetsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/posts/MarketPostsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionsFragment.kt
> Show screen content with animation

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartVolume.kt
> Chart enhancements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTradingVolumeChartService.kt
> Total volume chart fix

- app/src/main/java/io/horizontalsystems/bankwallet/entities/FullCoin.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/EnableCoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinPlatformsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinPlatformsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsService.kt
> Filter out unsupported platforms on manage coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
> Fix coin adding to wallet from CoinPage

- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftAssetRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftCollectionRecord.kt
> Apply NFT API changes; Delete NFT records on AccountRecord delete

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/requestlist/WC2RequestListViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt
> Fix WalletConnect eip1559 fee 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionCell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionList.kt
> Implement swipe to disable in Balance

- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SelectorDialogCompose.kt
- app/src/main/res/values/strings.xml
> Implement Nft 'Share' and 'Save' actions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/DraggableCell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionList.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Swipe to reveal fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftAssetItemsPricedRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftPreview.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftsCollectionSection.kt
> Nft UI bug fixes

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt
- app/src/main/res/navigation/wallet_connect_graph.xml
> Fix WalletConnect deeplinks handling

- app/build.gradle
> Update SplashScreen API

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
> Fix crash during fragment restore in TransactionInfo

- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncerror/SyncErrorDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncerror/SyncErrorViewModel.kt
> Fix crash in SyncErrorDialog

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
> Update Zcash SDK

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/CustomTokenStorage.kt
> Update market-kit, fix filtering custom tokens

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- replace rx observable with coroutines flow
- pass items in a flow
#4738
> Fix synchronization issues in Balance module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- service should emit every time new copy of items list
#4738
> Fix bug in BalanceService

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_41_42.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/tor/SecurityTorSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorStatusInteractor.kt
> Write Tor state to App Status

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/ShowBackupWordsFragment.kt
> Fix crash caused by ViewModel restore

- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyIntroFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyMainFragment.kt
> Fix ViewModel restore crash in ShowKeyMainFragment

- app/build.gradle
> Update MarketKit to implement fixed coin sync logic

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/btcblockchainsettings/BtcBlockchainSettingsFragment.kt
- build.gradle
> Pass settings title to BlockchainSettingSection

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/res/values/strings.xml
> Show market data in Discovery List

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/CoinCategoryMarketDataChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Add MarketCap chart to coin category page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/nft/collection/TopNftCollectionsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/INftApiProvider.kt
- app/src/main/res/values/strings.xml
> Add 'Top NFTs' section to Overview

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
- app/src/main/res/drawable/ic_top_nfts.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Implement Top NFT Collections page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Make small fixes to QR Scanner and favorite/unfavorite UX

- app/build.gradle
> Add new Binance Smart Chain RPC provider

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt
> Add blockchain field to ISendBitcoinAdapter

- app/src/main/java/io/horizontalsystems/bankwallet/modules/unlinkaccount/UnlinkAccountDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/unlinkaccount/UnlinkAccountViewModel.kt
- app/src/main/res/values/strings.xml
> Change Watch account Unlink button text

- app/src/main/java/io/horizontalsystems/bankwallet/modules/availablebalance/AvailableBalance.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinAmountService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HSCircularProgressIndicator.kt
> Loading available balance state

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt
> Handle legacy eth_sign WalletConnect request

- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/CoinOverviewScreen.kt
> Force refresh chart data via resubscribing for updates

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
> Fix app crash when opening market search with no internet

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmIncomingTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/SwapTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/UnknownSwapTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoAddressMapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
- app/src/main/res/values/strings.xml
> Refactor representation of transactions on the list and on info page

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmContractMethodParser.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoAddressMapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Show predefined labels to EVM transactions by method id

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/ui/SignScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WCSignMessageRequestFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2SignMessageRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/requestlist/WC2RequestListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/requestlist/WC2RequestListViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/requestlist/ui/RequestListScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version1/WC1Service.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt
- app/src/main/res/values/strings.xml
> Add Legacy Sign elements to WalletConnect Request page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/INftApiProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/activity/NftCollectionItemsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/items/NftCollectionActivityFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftAssetItemsPricedRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftAssetItemsPricedWithCurrencyRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftAssetItemsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/CellLink.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftPreview.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftsCollectionSection.kt
- app/src/main/res/layout/fragment_collection.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> NFT Collection Overview

- app/build.gradle
> Update MarketKit to fix historical coin price caching

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FillWalletInfoWorker.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
> Add worker to fill code, name, decimals to existing wallets

- components/pin/src/main/java/io/horizontalsystems/pin/ManagePinPresenter.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinInteractor.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinModule.kt
> Keep app unlocked after initial PIN set

- app/build.gradle
> Update EthereumKit to remove connection reset on App resume

- app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/fiat/FiatServiceSendEvm.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/allowance/SwapAllowanceService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
> Simplify `CoinValue` by removing property `kind`

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CellTweet.kt
- Revert cell to rounded background
- Use Laguna color for Polls
#4837
> Make UI changes to CellTweet

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinValue.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/DoubleText.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Balance card update

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/res/drawable/ic_arrow_down_left_12.xml
- app/src/main/res/drawable/ic_arrow_up_right_12.xml
- app/src/main/res/layout/view_holder_transaction_info_item.xml
> Change icons and text colors in TransactionInfo

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopPlatforms.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Badge.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
- app/src/main/res/drawable/ic_platform_placeholder_24.xml
- app/src/main/res/drawable/ic_platforms.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Implement Top platforms

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
> Update coinValue color in BalanceCard

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/res/layout/view_holder_transaction_info_item.xml
- app/src/main/res/values/strings.xml
- use ImageView for coin icon, to prevent 'blinking'
- show 'sentToSelf' section
#4851
> Fix UI bugs in TransactionInfo

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmAccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/HSProFeaturesAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/ProFeaturesAuthorizationManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/ProNft.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/storage/ProFeaturesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/storage/ProFeaturesSessionKey.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/storage/ProFeaturesStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProFeaturesBanner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProUsersActivateDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProUsersInfoDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/YakAuthorizationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/YakAuthorizationService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/YakAuthorizationViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
- app/src/main/res/drawable/ic_pro_user.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
> Pro features

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_42_43.kt
> Add 42 -> 43 migration

- app/build.gradle
> Fix sync error on app resume

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ZcashBirthdayProvider.kt
> Update ZCash SDK to 1.4.0-beta01

- app/src/main/java/io/horizontalsystems/bankwallet/modules/hsnft/HsNftModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/INftApiProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsViewModel.kt
- app/src/main/res/values/strings.xml
> Update Nft Collection event types

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/AppLogger.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreInteractor.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStoreModule.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/KeyStorePresenter.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
- core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt
> Log key invalidation causes to App Log

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
Fix location of address component 
#4862
> Show empty historical rate if not available in tx info

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/adapters/TransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
> Add "Contract Creation" label on contract creation transactions info page

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
> Disable click effect for TopPlatforms when onClick is null

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProFeaturesBanner.kt
- app/src/main/res/drawable/ic_pro_nft_banner.xml
> Apply design to PRO NFT banner

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Snackbar.kt
> Discovery page fixes

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
> Fix ZCash new wallet initial sync

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
- components/keystore/src/main/res/drawable/ic_top_nft_collections_20.xml
> Change icons for TopPlatforms, TopNft in Overview page

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmLabelManager.kt
> TryCatch network exception in EvmLabelManager

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Fix account transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Show platform icon for contract call EVM tx records

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProFeaturesBanner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BaseComposableBottomSheetFragment.kt
- Fix setting highlight area
- Fix Coin details boxes highlight area
- Fix BottomSheet close icon padding
#4861, #4911
> Apply small UI fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionService.kt
> Show current account name in WalletConnect session page

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AccountFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
- app/src/main/res/layout/fragment_restore_mnemonic.xml
- app/src/main/res/values/strings.xml
> Implement account name in Restore and Address Watch

- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
> Filter out external EVM transactions not containing any known coin 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceNoAccount.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Color.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Colors.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Theme.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonPrimary.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Screen message with actions changes

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt
> Disable temporarily Arbitrum One and Optimism chains

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt
> Send swap fraction digits

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt
> Add BSC RPC sync source

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/v1/WCSendEthereumTransactionRequestFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/ui/SignScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2SignMessageRequestService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/ui/RequestCells.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Request.kt
> Show dApp name in WalletConnect screens

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsService.kt
> Limit top nft collections to 100 items

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559FeeSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/SwapDeadlineViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionViewModel.kt
> Fix memory leaks caused by not cleared disposables

- app/src/main/res/drawable/ic_pro_nft_banner.xml
- app/src/main/res/values/strings.xml
> Fix texts and change Pro Nft banner image

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/ProFeaturesBanner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/profeatures/yakauthorization/YakAuthorizationViewModel.kt
> Disable PRO charts authentication

- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/binancechain/BinanceChainOutgoingTransactionRecord.kt
> Negate amount for outgoing binance chain transaction

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalService.kt
> Total switch

- app/src/main/java/io/horizontalsystems/bankwallet/modules/hodler/HSHodlerInput.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/ui/RequestCells.kt
- app/src/main/res/layout/view_holder_amount_multi.xml
- app/src/main/res/layout/view_holder_evm_confirmation_subhead.xml
> Apply updated design to cells in Confirmation screens

- app/build.gradle
> Update ZCash SDK to version 1.5.0-beta01

- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
> Fix bep2 syncing

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/ui/RequestCells.kt
- app/src/main/res/layout/view_holder_amount_multi.xml
> Implement Confirmation cell fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/PasscodeBlock.kt
> Show alert icon when Pin not set

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacyFragment.kt
- app/src/main/res/drawable/ic_user_20.xml
- app/src/main/res/navigation/main_graph.xml
- app/src/main/res/values/strings.xml
> Add Privacy page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
> Replace 'record' in TransactionItem on update

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
> Show 'speed-up' and 'cancel' only for outgoing EVM txs

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftPreview.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/ui/NftsCollectionSection.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionCell.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Theme.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CellTweet.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
> Fix Compose preview by updating Coil library

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsViewModel.kt
- Open trade url on market click
#4962
> Fix coin markets parsing

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
> Disable vertical scrolling when chart point is held

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
> Minimize app on back press in Main Fragment

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
> Fix coin icon size

- app/build.gradle
Hotfix: Fix bitcoin and bitcoin-cash sync
> Update bitcoin kit

- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TabRow.kt
> Fix tab paddings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/res/layout/view_chart.xml
> Chart split indicator line

- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version1/WC1Service.kt
> Handle WalletConnect requests from mobile browser

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/restoresettings/RestoreSettingsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/restoresettings/RestoreSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ZCashBirthdayHeightDialog.kt
- app/src/main/res/layout/fragment_dialog_zcash_bday_height.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/color/stateful_edittext_background_color.xml
> Add option to restore ZCash wallet from latest blockheight

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt
> Implement ENS address parsing via separate lib

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/PredefinedBlockchainSettingsProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountService.kt
> Implement predefined setting for new Zcash wallet

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/PasscodeBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyIntroFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
- core/src/main/java/io/horizontalsystems/core/Extensions.kt
> Fix getting Pin fragment results

- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyService.kt
- drop extra byte added for sign bit
#5052
> Fix conversion of privateKey to hex string

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseCoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/BottomSheets.kt
- app/src/main/res/values/strings.xml
> Appearance additions

- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Aggregate transaction values on transactions list tab

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyViewModel.kt
- app/src/main/res/values/strings.xml
> Implement public keys for bitcoin based blockchains

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewBoards.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopPlatforms.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopSectors.kt
> Make market overview section titles clickable

- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartHistogram.kt
> Adjust macd bar width depending on point intervals

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt
> Fix the toolbar action icon on Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
> Use Leah color for zero crypto value instead of grey

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
> Search coin by contract address in manage coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewBoards.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopSectors.kt
> Remove highlight market overview section headers press
