horizontalsystems/unstoppable-wallet-android

- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
added empty list placeholder for Transactions screen,
small ui changes
> Transaction empty list placeholder

- app/src/main/res/values/strings.xml
> renamed app to Bank

- app/src/main/res/layout/activity_unlock.xml
for pin screen updated layout to be responsive to fit in small screen too,
moved Receive button above numpad
> for pin screen updated layout

- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/view_holder_transaction.xml
- wallet-kit/build.gradle
ui fixes in transactions view,
commented slf4j library since its failing build
> Transaction small UI fix

- wallet-kit/src/main/java/bitcoin/walllet/kit/network/message/GetDataMessage.java
- wallet-kit/src/main/java/bitcoin/walllet/kit/network/message/InvMessage.java
- wallet-kit/src/main/kotlin/bitcoin/wallet/kit/network/Peer.kt
- wallet-kit/src/main/kotlin/bitcoin/wallet/kit/network/PeerGroup.kt
- wallet-kit/src/test/kotlin/bitcoin/wallet/kit/network/PeerTest.kt
- request only required
- request merkle block when inv has a new block
> Handle inv message in peers:

- wallet-kit/src/main/java/bitcoin/walllet/kit/constant/BitcoinConstants.java
- wallet-kit/src/main/kotlin/bitcoin/wallet/kit/messages/VersionMessage.kt
- wallet-kit/src/main/kotlin/bitcoin/wallet/kit/network/Peer.kt
- wallet-kit/src/main/kotlin/bitcoin/wallet/kit/network/PeerConnection.kt
- wallet-kit/src/test/kotlin/bitcoin/wallet/kit/network/PeerTest.kt
check peer by VersionMessage on having fullNode, and support of Bloom… filter
> check peer by VersionMessage

- app/src/main/java/bitcoin/wallet/modules/send/SendFragment.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendModule.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendPresenter.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletFragment.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletModule.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletPresenter.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletViewModel.kt
- app/src/main/res/drawable/border_red.xml
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/test/java/bitcoin/wallet/modules/send/SendInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendPresenterTest.kt
changed places of Amount and Address inputs
> adapter Send Module to be like in iOs project,

- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/bitcoin/wallet/modules/receive/ReceiveModule.kt
- app/src/main/java/bitcoin/wallet/modules/receive/ReceivePresenter.kt
- app/src/main/java/bitcoin/wallet/modules/receive/ReceiveViewModel.kt
- app/src/main/res/layout/fragment_bottom_sheet_receive.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/bitcoin/wallet/modules/receive/ReceivePresenterTest.kt
> Make design changes in Receive bottom sheet dialog

- app/src/main/res/layout/fragment_wallet.xml
> Add top and bottom paddings to Coin Wallets

- app/src/main/res/values/colors.xml
> Switch colors in project for yellow and crypto yellow

- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/layout/fragment_bottom_sheet_receive.xml
> Change background color in Send/Receive dialogs

- app/src/main/java/bitcoin/wallet/core/managers/WordsManager.kt
- app/src/main/java/bitcoin/wallet/modules/backup/BackupInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/main/MainActivity.kt
- app/src/main/java/bitcoin/wallet/modules/main/MainViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/settings/SecuritySettingsActivity.kt
- app/src/main/java/bitcoin/wallet/modules/settings/SecuritySettingsViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/settings/SettingsFragment.kt
- app/src/main/java/bitcoin/wallet/modules/settings/SettingsViewModel.kt
> Fix settings badge removal when user backups word list

- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/res/layout/view_transaction_info_item.xml
- app/src/main/res/values/attrs.xml
> Correct the show of transaction currency amount in TransactionInfo views

- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/core/ExchangeRateManager.kt
- app/src/main/java/bitcoin/wallet/core/IAdapter.kt
- app/src/main/java/bitcoin/wallet/core/Interfaces.kt
- app/src/main/java/bitcoin/wallet/core/NetworkManager.kt
- app/src/main/java/bitcoin/wallet/entities/TransactionRecord.kt
- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionRecordViewItem.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletInteractor.kt
- app/src/main/java/bitcoin/wallet/viewHelpers/DateHelper.kt
- app/src/test/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactions/TransactionsInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/wallet/WalletInteractorTest.kt
> Exchange rates from ipfs

- app/src/main/java/bitcoin/wallet/modules/send/SendFragment.kt
> Show the numpad on opening Send dialog (#161)

- app/src/main/res/values/styles.xml
> Change background color on transaction tab to white

- app/src/main/java/bitcoin/wallet/core/NetworkManager.kt
- app/src/main/java/bitcoin/wallet/core/managers/PreferencesManager.kt
- app/src/main/java/bitcoin/wallet/entities/Currency.kt
- app/src/main/java/bitcoin/wallet/modules/currencyswitcher/CurrencySwitcherActivity.kt
- app/src/main/java/bitcoin/wallet/modules/currencyswitcher/CurrencySwitcherInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionRecordViewItem.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletFragment.kt
- app/src/test/java/bitcoin/wallet/modules/currencyswitcher/CurrencySwitcherInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/currencyswitcher/CurrencySwitcherPresenterTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendPresenterTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactions/TransactionsInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/wallet/WalletInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/wallet/WalletPresenterTest.kt
> Fetch currencies as list of objects from IPFS

- app/src/main/java/bitcoin/wallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendFragment.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendPresenter.kt
- app/src/main/res/layout/fragment_confirmation.xml
- app/src/main/res/values/strings.xml
> Implement Send Confirmation controller

- app/src/main/java/bitcoin/wallet/BaseActivity.kt
- app/src/main/java/bitcoin/wallet/LauncherActivity.kt
- app/src/main/java/bitcoin/wallet/core/App.kt
- app/src/main/java/bitcoin/wallet/core/Interfaces.kt
- app/src/main/java/bitcoin/wallet/core/managers/BackgroundManager.kt
- app/src/main/java/bitcoin/wallet/core/managers/PreferencesManager.kt
- app/src/main/java/bitcoin/wallet/core/managers/WordsManager.kt
- Close #79 
- Check for timeout to prompt PIN unlock (#79)
- Fixed Launcher activity redirect logic
> Enhance Pin Unlock Logic

- app/src/main/java/bitcoin/wallet/core/managers/WordsManager.kt
- build.gradle
- Fix CI build by updating WalletKit import path
- Increased Gradle version to 3.2.1
> Update walletKit dependency in WordsManager

- app/build.gradle
- app/src/main/java/bitcoin/wallet/BaseActivity.kt
- app/src/main/java/bitcoin/wallet/core/App.kt
> Add LeakCanary to catch Memory leaks

- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletFragment.kt
> Fix Wallet and Transactions fragments loaded as empty 

- app/build.gradle
- app/src/main/java/bitcoin/wallet/core/AdapterManager.kt
- app/src/main/java/bitcoin/wallet/core/App.kt
- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/core/EthereumAdapter.kt
- app/src/main/java/bitcoin/wallet/core/IAdapter.kt
- app/src/main/java/bitcoin/wallet/entities/TransactionRecord.kt
- app/src/main/java/bitcoin/wallet/entities/coins/ethereum/Ethereum.kt
- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/send/SendInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionRecordViewItem.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/bitcoin/wallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/bitcoin/wallet/viewHelpers/NumberFormatHelper.kt
- app/src/test/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoPresenterTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactionInfo/TransactionInfoInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactions/TransactionsInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactions/TransactionsPresenterTest.kt
> Add Ethereum support

- app/src/main/AndroidManifest.xml
- app/src/main/java/bitcoin/wallet/BaseActivity.kt
- app/src/main/java/bitcoin/wallet/modules/settings/AboutSettingsActivity.kt
- app/src/main/java/bitcoin/wallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/res/layout/activity_about_settings.xml
- app/src/main/res/layout/activity_add_wallet.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Add About section to Settings

- app/src/main/java/bitcoin/wallet/BaseActivity.kt
- app/src/main/java/bitcoin/wallet/core/Interfaces.kt
- app/src/main/java/bitcoin/wallet/core/managers/AdapterManager.kt
- app/src/main/java/bitcoin/wallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/bitcoin/wallet/modules/backup/BackupInfoFragment.kt
- app/src/main/java/bitcoin/wallet/modules/guest/GuestActivity.kt
- app/src/main/java/bitcoin/wallet/modules/guest/GuestInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/guest/GuestModule.kt
- app/src/main/java/bitcoin/wallet/modules/guest/GuestViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/main/MainActivity.kt
- app/src/main/java/bitcoin/wallet/modules/pin/PinActivity.kt
- app/src/main/java/bitcoin/wallet/modules/restore/RestoreInteractor.kt
- app/src/main/java/bitcoin/wallet/modules/restore/RestoreModule.kt
- app/src/main/java/bitcoin/wallet/modules/restore/RestoreViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/bitcoin/wallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/bitcoin/wallet/ui/dialogs/BottomConfirmAlert.kt
Close #195 
Close #212
Clean old code related to handling User Authentication Exception
> Fix double auth screens

- app/src/main/java/bitcoin/wallet/core/App.kt
- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/core/EthereumAdapter.kt
- app/src/main/java/bitcoin/wallet/core/managers/AdapterManager.kt
- app/src/main/java/bitcoin/wallet/entities/TransactionRecord.kt
- app/src/test/java/bitcoin/wallet/modules/fulltransactioninfo/FullTransactionInfoInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/send/SendInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/transactions/TransactionsInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/wallet/WalletInteractorTest.kt
> Replace stub bitcoin kit 

- app/src/main/java/bitcoin/wallet/core/managers/NetworkManager.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletBalanceViewItem.kt
- app/src/main/java/bitcoin/wallet/modules/wallet/WalletFragment.kt
- app/src/main/res/layout/view_holder_coin.xml
> Show exchange rate in first screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/bitcoin/wallet/modules/pin/PinActivity.kt
- app/src/main/java/bitcoin/wallet/modules/pin/PinModule.kt
- app/src/main/java/bitcoin/wallet/modules/pin/PinPresenter.kt
- app/src/main/java/bitcoin/wallet/modules/pin/PinViewModel.kt
- app/src/main/java/bitcoin/wallet/modules/pin/pinSubModules/UnlockInteractor.kt
- app/src/main/res/anim/shake_pin_circles.xml
- app/src/main/res/layout/activity_pin.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/bitcoin/wallet/modules/pin/UnlockInteractorTest.kt
- app/src/test/java/bitcoin/wallet/modules/pin/UnlockPresenterTest.kt
> Shake and vibrate on wrong PIN entry

- app/src/main/java/bitcoin/wallet/core/BitcoinAdapter.kt
- app/src/main/java/bitcoin/wallet/core/managers/AdapterManager.kt
- app/src/main/java/bitcoin/wallet/entities/coins/bitcoinCash/BitcoinCash.kt
> Add Bitcoin Cash adapter

- app/src/main/java/io/horizontalsystems/bankwallet/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestorePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletViewModel.kt
- app/src/main/res/layout/activity_settings_security.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletModulePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/wallet/WalletInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/wallet/WalletPresenterTest.kt
Open PIN Set after Wallet Restoring
Hide Import Wallet(Restore) option in Settings
Disable display of FullTransactionInfo from Bottom Transaction Info view
Close #235 
Close #241 
Close #240
> Bug fixes and hiding some features

- app/build.gradle
- app/confs/wallet.properties
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LanguageManager.kt
> Show available languages by Configuration file

- app/src/main/res/layout/activity_about_settings.xml
- app/src/main/res/layout/activity_add_wallet.xml
- app/src/main/res/values/strings.xml
> Update texts 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- Remove hardcoded words
- Use MainNet networks
> Switch app to MainNet

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SystemInfoManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/EncryptionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/FingerprintAuthenticationDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/FingerprintUiHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guest/GuestActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/edit/EditPinPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/HudHelper.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/edit/EditPinPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractorTest.kt
Use standard Toast to show success and error alerts (#206)
> Fix memory leaks

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Capitalize first letter of Language in Settings

- app/confs/wallet.properties
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/StubStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/TextHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
- app/src/main/res/color/yellow_text_on_dark_color_selector.xml
- app/src/main/res/layout/fragment_wallet.xml
- app/src/main/res/layout/view_holder_coin.xml
- app/src/main/res/values/colors.xml
Apply new Syncing indicators on Wallets tab (#225)
Don't show fractions in the exchange rate for rates over 100$ (#250)
Close #225
Close #250
> Update wallets sync design 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewitems/AddressItem.kt
> Fix receive module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoPresenterTest.kt
> Fix TransactionInfo view

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/TransactionDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/TransactionRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletPresenter.kt
> Change storage to return Maybe instead of Single

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/TransactionRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
> Clear transactions and rates in database on Wallet unlink

- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
> Fix crashing Processing Transaction progress 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/res/drawable/text_grey_background_for_white_theme.xml
- app/src/main/res/layout/fragment_confirmation.xml
> Fix address field design in Send Confirmation dialog

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
> Show pending transactions as Shaded 

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- Get last block height from kit
- Set api keys for ethereum kit
Close #310
> Ethereum kit changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/res/layout/fragment_bottom_sheet_transaction_info.xml
- app/src/main/res/layout/view_transaction_info_item.xml
> Show both "from" and "to" fields in transaction info

- app/src/main/res/layout/activity_currency_switcher.xml
> Fix currency list not scrolling 

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PaymentRequestAddress.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
> Implement PaymentAddress parser

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
> Fix intent flags setting

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/res/layout/activity_currency_switcher.xml
> Fetch empty rates on network connect (#329)

- app/src/main/java/io/horizontalsystems/bankwallet/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupViewModel.kt
- Validate words before showing Terms Confirm dialog #327
- Prevent bypass Initial Backup session with app kill #331
Close #327
Close #331
> Fixes for BackupWords Confirmation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
> Fix send module

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
> Use standard rounding for coin value formatting

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
> Fix logic of showing Terms Confirm Dialog 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestorePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
- app/src/main/res/values/strings.xml
> Show proper errors in Restore Module 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletFragment.kt
> Fix "Double tap on send crashes app" 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/guest/GuestActivity.kt
> Guest module: several actions should not be triggered at once

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenter.kt
Fix fingerprint dialog open on button click, that was mistakenly removed with this pull request #363
> Fix fingerprint dialog show on button click

- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
> Fix app crashing while trying restoring ReceiveFragment 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/wallet/WalletViewModel.kt
- app/src/main/res/layout/fragment_wallet.xml
> Add ability to refresh/resync balances by appropriate swipe gesture

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/BottomConfirmAlert.kt
- app/src/main/res/color/button_red_bg_color_selector.xml
- app/src/main/res/drawable/button_red_background_12.xml
- app/src/main/res/layout/activity_settings_security.xml
> Use red color for "Unlink from this device" text

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SystemInfoManager.kt
> Fix showing app version in Settings tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsViewModel.kt
> Close base currency window when it is changed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupWordsFragment.kt
- build.gradle
> Fix Backup words list not showing words on Fragment restore

- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreWrapper.kt
> Increase authentication validity time by 30 minutes

- app/build.gradle
- app/confs/wallet.properties
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
> Enable ether

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/EncryptionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
> Clean storage on logout

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt
> Hide transaction from/to field when its empty 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/res/layout/activity_full_transaction_info.xml
- app/src/main/res/values/strings.xml
> Update Full Info

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CoinManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SecuredStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt
> Pass wallet id when creating bitcoin kit

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/TextHelper.kt
- app/src/main/res/color/stateful_button_grey_text_color.xml
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/values/colors.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
>  Disable paste button when clipboard is empty

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
> Fix rounding in ValueFormatter for Fiat values 

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Utils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/EncryptionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/AlertDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInfoFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/res/layout/activity_backup_words.xml
- app/src/main/res/layout/fragment_backup_words_confirm.xml
- app/src/main/res/layout/fragment_backup_words_info.xml
- app/src/main/res/layout/fragment_backup_words_show_words.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenterTest.kt
- In Backup and Restore pages check if user uses custom keyboard
- Refactor Backup Module
Close #451
> Show warning when user is using custom keyboard

- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreWrapper.kt
> Fix app crash on phone screen lock change 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
> Show total available balance minus fee

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/res/color/button_grey_50_bg_color_selector.xml
- app/src/main/res/color/numpad_button_background_selector.xml
- app/src/main/res/drawable/numpad_button_background.xml
- app/src/main/res/layout/activity_pin.xml
- app/src/main/res/layout/view_numpad_button.xml
- app/src/main/res/values/styles.xml
- Update PIN numpad design (#464)
- Use touchListener for handling numpad clicks (#457)
Close #464
Close #457
> Update PIN numpad

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/NumPadItemsAdapter.kt
- app/src/main/res/color/button_image_tint_color_selector.xml
- app/src/main/res/color/button_yellow_bg_color_selector.xml
- app/src/main/res/color/button_yellow_text_color_selector.xml
- app/src/main/res/color/stateful_button_text_color.xml
- app/src/main/res/drawable/address_background_themed.xml
- app/src/main/res/drawable/alert_background_themed.xml
- app/src/main/res/drawable/button_grey_background_4_themed.xml
- app/src/main/res/layout/activity_pin.xml
- app/src/main/res/layout/activity_unlock.xml
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/layout/fragment_confirmation.xml
- app/src/main/res/layout/view_numpad_button.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- Use custom numpad in Send Module
- Add dark theme for Send and Confirmation dialogs
- Fix app crash on resuming with Send Dialog opened
Close #475
Close #471
> Use custom numpad in Send Controller

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppCloseManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ManagePinPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenterTest.kt
> Close app in PIN unlock screen when Back button is pressed

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- Add button to send max. available balance in Send Module
- On 0 balance keep Send button disabled
- Close #396
>  Improvements and fix for SendModule

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
> Update fractions formatting for coin/fiat numbers

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
- app/src/main/res/layout/view_holder_transaction.xml
> Show currency sign smaller than value in Transactions Fragment

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionStatusWithTimeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
- app/src/main/res/color/stateful_tag_filter_button_border_bg_color.xml
- app/src/main/res/color/stateful_tag_filter_text_color_dark.xml
- app/src/main/res/drawable/stateful_tag_bg.xml
- app/src/main/res/drawable/status_progress_bar_grey_20_small.xml
- app/src/main/res/drawable/status_progress_bar_grey_small.xml
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_holder_filter.xml
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/layout/view_transaction_info_item.xml
- app/src/main/res/layout/view_transaction_info_status.xml
- app/src/main/res/layout/view_transaction_status.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Transactions tab design update

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatterTest.kt
- Add tests for value formatting
Close #498
> Fix rounding in ALL cases 

- app/confs/wallet.properties
> Enable Korean language

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenterTest.kt
> Hide transaction filters

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Fix crash on transactions list scrolling

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
> Remember the input type of when sending coins in local storage

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
Close #396
- Hide Max button on amount input
- Show 0 fee for 0 amount
- Fix BigDecimal compare with 0
> Apply ui changes to Send module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/ValueFormatter.kt
> Fix send confirmation fee formatting 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
> Fix Unlink

- app/confs/wallet.properties
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
Close #552
- Order currencies and localizations
> Add new currencies: TRY, KRW

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/StorableCoinsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/StorableCoinsRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Fix enable disable coins

- app/src/main/res/layout/view_holder_coin.xml
> Update coin amount positions and colors

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/WalletFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AuthManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guest/GuestInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreInteractor.kt
> Send newWallet flag to BitcoinKit when creating wallet

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
> Turned off stable ids for transactions list

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactory.kt
- app/src/main/res/anim/shake_edittext.xml
- app/src/main/res/layout/view_numpad_button.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactoryTest.kt
> Prevent user from entering more numbers than needed in Send controller

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/res/layout/fragment_wallet.xml
- app/src/main/res/layout/view_holder_add_coin.xml
- Fix none visible add coin button on balance screen (#581)
- Expand to full height Receive bottom dialog
Close #581
> Balance screen fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
> Fix sending coins in currency

- app/src/main/java/io/horizontalsystems/bankwallet/core/security/FingerprintAuthenticationDialogFragment.kt
> Fix crash in FingerprintAuthenticationDialogFragment

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/AnimationHelper.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactoryTest.kt
> Balance screen ui changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
> Prevent user from using none native keyboard for restoring words

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
> Handle no/expired rate in Send Module 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
> Remove clear method from eth adapter as it already handled by kit manager

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenterTest.kt
> Clear rx subscriptions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
> Use thread-safe hash-map and list for requestedTimestamps

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactory.kt
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactoryTest.kt
Close #625 
Close #627
- Fix Max button amount calculation
> Add support for ERC20 fee 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Pass last block date for syncing state

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
> Remove error hint when incorrect amount is changed

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Show fiat amounts less than 0.01 with less symbol (<)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
> Show fee for ERC20 transfers in ETH 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateSyncer.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactory.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactoryTest.kt
- Fix showing fees in Confirmation dialog when rates are not available while user sending Erc20 token
- Download all needed rates for Erc20 tokens
Close #674
> Send module fixes

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Show minus sign for coin values in Transactions 

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
> Change date format for transactions 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Change IPFS URL to global format

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
> Update sync progress when last block date changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactory.kt
- app/src/main/res/layout/fragment_confirmation.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/StateViewItemFactoryTest.kt
> Show coin or fiat amount as primary value in confirmation screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/res/values/styles.xml
> Change Pull down to refresh spinner colorscheme by theme 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ButtonWithProgressbarView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/HudHelper.kt
- app/src/main/res/color/yellow_button_text_color_selector.xml
- app/src/main/res/layout/fragment_confirmation.xml
- app/src/main/res/layout/view_button_with_progressbar.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- Handle send action errors (#667)
- Show progressbar when user clicks on Confirm button (#667)
- Show checkmark beside Send success message (#688)
Close #667
Close #688
> Handle sending and error states in Send Confirmation dialog

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
> Fix transaction send module validation for Erc20 tokens 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Apply changes to formatting coin/fiat amounts

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Coin.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsModule.kt
> Fix coin manager duplicate

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Don't show fiat value for coin wallet in balance screen when amount is 0

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
> Use Coin as default input in Send module when rate is not available 

- app/src/main/java/io/horizontalsystems/bankwallet/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenterTest.kt
> Make app cold start faster

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Show build number in settings 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/activity_dashboard.xml
> Enable swipe of tabs

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Correct erc20 tokens addresses and decimals 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateSyncer.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/LatestRate.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/LatestRateData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/RateManagerTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/RateSyncerTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenterTest.kt
- Request historical rates after failure
Close #738
> Add IPFS Requests Optimizations 

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/AddressParser.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/Utils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/AddressData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockchairProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/EthInputParserTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/utils/AddressParserTest.kt
> Move Address parser from Kit to App

- app/src/main/java/io/horizontalsystems/bankwallet/core/security/EncryptionManager.kt
> Add custom text for Authorization Required Screen 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsActivity.kt
- app/src/main/res/layout/view_holder_explorer_item.xml
- Show top, bottom shadows in FullTransactionInfo Provider Settings (#736)
- Show top back button in FullTransactionInfo
> Make ui fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
> Update Ethereum explorer URLs with new ones 

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkAvailabilityManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Rate.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- Fix exchange rate expired check
- Fix show latest rate on app resumed from background in Balance screen
Close #790
> Fix exchange rate bugs 

- app/src/main/res/layout/view_pin_page.xml
> Set PIN screen description text to have maximum 3 lines 

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Remove "t" suffix and show Test label in each screen 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
> Fix setting fiat values in transactions list on fast scroll

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/res/layout/fragment_confirmation.xml
> Fix Confirmation dialog resizing on show 

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- build.gradle
> When requesting rates from IPFS on error switch to fallback URL 

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/RateManagerTest.kt
> Use same retrofit clients for multiple Exchange Rate requests

- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactoryTest.kt
> Show both From and To addresses for transactions to yourself in TransactionInfo screen

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
> Apply new block-explorer for Ethereum Blockchain with new json structure

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
> Integrate FeeRateKit

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Fix exchange rates not displayed for pending transactions 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Display full exchange rate for amounts below 10 cents 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
>  Use viewLifecycleOwner in Fragments for viewModel liveData observers

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Fix showing fiat value with big delay on changing base currency 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
> Handle updated exchange rates on resume in Send Dialog 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ConfirmationFragment.kt
> Make Confirmation dialog always dismissible

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Add  Tether USD erc20 coin 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendBottomSheetFragment.kt
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
> Show Send dialog quicker 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/Pool.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionDiffCallback.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionItemDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
> Integrate EthereumKit/Erc20Kit, refactor kit adapters (#850)

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
> Remove eth.horizontalsystems.xyz from transaction info providers

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Show coin and fiat balances as dimmed on wallet sync 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/RateManagerTest.kt
> Show fiat amount on pending transaction without delay 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Set Default Coins

- app/src/main/res/layout/view_holder_add_coin.xml
> Increase the click area around ManageCoins button on Balance Tab 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsActivity.kt
> Trigger add/remove of coins on cell click in ManageCoins screen 

- app/src/main/res/layout/activity_dashboard.xml
- app/src/main/res/layout/fragment_balance.xml
- app/src/main/res/layout/fragment_bottom_sheet_pay.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/values/styles.xml
- Fix scroll in Balance/transactions pages
- Ui changes to overscroll effect
Close #885
> Fix scroll in Balance/Transactions page 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/HudHelper.kt
> Show "copied" toast for half a second duration 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Handle bottomsheet dialogs onBackpressed event 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/receive/ReceivePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/send/SendPresenterTest.kt
- Switch to Coin input on expired rate in Send dialog
- Check rate for freshness each minute in SendDialog (#863)
- Check freshness of exchange rates on Balance Page each minute (#863)
Close #863
> Update ui when exchange rate is expired

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/fragment_balance.xml
- app/src/main/res/layout/fragment_transactions.xml
> Hide toolbar title with animation on Balance and Transactions screens

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
Fetch rate from "ipfs-ext.horizontalsystems.xyz" firstly then fallback to "ipfs.io" (#890)
> Try fetching rate firstly from ipfs-ext node

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageCoinsActivity.kt
> Allow user adding and removing coins without delay

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/res/drawable/circle_shape_button_placeholder.xml
- app/src/main/res/drawable/circle_shape_placeholder.xml
- app/src/main/res/drawable/text_placeholder_background.xml
- app/src/main/res/layout/add_coin_placeholder.xml
- app/src/main/res/layout/fragment_balance.xml
- app/src/main/res/layout/view_holder_coin_placeholder.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractorTest.kt
- While loading coins in Balance Tab show placeholder (#912)
- Show as much placeholders as enabled coins (#912)
Close #912
> Show coins placeholders while loading coins in Balance tab 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/DashAdapter.kt
> Enable Segwit address in receive controller for Bitcoin 

- app/build.gradle
- app/src/main/assets/logback.xml
> Update EthereumKit and add logger slf4j 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
> Dim coin value while syncing

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AuthManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/SyncMode.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guest/GuestInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestorePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModeActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModeInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModeViewModel.kt
- app/src/main/res/layout/activity_sync_mode.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/restore/RestorePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModePresenterTest.kt
- Implement Wallet Restore layout (#918)
- Start BitcoinCoreKit with selected SyncMode (#918)
Close #918
> Implement restore sync mode options 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
> Set first timeout to 10 seconds when fetching exchange rates 

- app/src/main/res/values/strings.xml
> New description text for Restore Screen (#940)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactoryTest.kt
> Dim total balance based on coins with non zero balances

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockdozerBitcoinCashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/InsightResponse.kt
> Update BCH Full Transaction Info Providers

- app/src/main/java/io/horizontalsystems/bankwallet/lib/InputTextViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/WordsInputAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputTextView.kt
- app/src/main/res/layout/view_text_input.xml
> Restore wallet improvements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/SeekbarView.kt
> Reset fee seekbar on send dialog open

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/layout/view_holder_empty_screen.xml
> Fix scrolling in empty transactions list 

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
> Start kit after creating in EthereumKitManager 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
> Collapse BottomSheets(Receive, Send, TxInfo) on Activity restore 

- app/src/main/java/io/horizontalsystems/bankwallet/lib/InputTextViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/WordsInputAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/InputTextView.kt
- app/src/main/res/layout/view_text_input.xml
Reverted code that was providing autocomplete from the word list
Close #988
> Use keyboard suggestions instead of autocomplete text on restore 

- app/build.gradle
- update BitcoinKit to fix issues related to syncing and segwit transactions
- increment version to 0.6.2
> Release version 0.6.2

- app/build.gradle
> Fix Bitcoincore crash on disconnect 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreWalletActivity.kt
> Make Mnemonic words restore and backup confirm case insensitive 

- app/src/main/res/color/manage_coin_background_dark.xml
- app/src/main/res/drawable/light_gradient_background.xml
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/values/colors.xml
> Make color minor fixes

- app/src/main/AndroidManifest.xml
Fix app always opening MainActivity instead of resuming on previously opened activity
> Fix app resuming on app launcher icon click

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
> Disable Logger low level logs for Release and MainNet builds 

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/SettingsItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MultipleInputEditTextView.kt
- app/src/main/res/drawable/ic_manage_coins.xml
- app/src/main/res/layout/activity_settings_security.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/view_multiple_input_edit_text.xml
- app/src/main/res/layout/view_setting_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/edit/EditPinPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractorTest.kt
> Add Manage Coins item into Settings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
> Fix the issue with concurrent processing of balance datasource

- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/BottomConfirmAlert.kt
> Fix the potential issue with BottomConfirmAlert

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
> Prompt pin when disabling it 

- app/src/main/java/io/horizontalsystems/bankwallet/core/BitcoinBaseAdapter.kt
- Remove/Hide FROM (address)  field from TX controller for BTC and BTC forks
- Close #1061
> Remove/Hide FROM field from TX info bottom controller for BTC forks (#1061)

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PredefinedAccountType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/eos/BackupEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/TextHelper.kt
- app/src/main/res/values/strings.xml
* QR code image connection 
* Now using account texts from string resources
Close #1077
> Set custom size for QrCode bitmap image

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
- Fix  tx. progress bar update status in tx. details window
- Close #1073
> Fix transaction progress bar not updating in tx. details window (#1073)

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/PoolRepo.kt
> Remove transactions pool for unused coins 

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BinanceChainProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockchairProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockdozerBitcoinCashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BtcComProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/InsightDashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/InsightResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/ProviderResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoErrorFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoItemView.kt
- app/src/main/res/layout/fragment_full_transaction_info_error.xml
- app/src/main/res/layout/view_holder_full_transaction_item.xml
- app/src/main/res/layout/view_holder_full_transaction_source.xml
> Binance full transaction info

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateSyncer.kt
- Change fetch interval of RateSyncer  to 5 minutes (#1092).
- Close #1092
> Change fetch interval of xrates from 3 minutes to 5 (#1092).

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
> Use P2WPKHSH for change addresses in Bitcoin

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/PoolRepo.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsLoader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
> Do not clear pools when filtering transactions 

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
> Fix issue with wrong amount for non BNB

- app/src/main/res/layout/view_address.xml
> Fix AddressView layout to show also short addresses 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEosAdapter.kt
- app/src/main/res/layout/view_transaction_full_info_item.xml
> Fix EOS Full Transaction Memo field 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> Sort coins by selected sort type on cold start 

- app/build.gradle
- Fix Binance-Chain-kit balance bug
- Update dependency version for Binance-chain-kit
- Close #1125
> Fix bug (Binance coin stops updatting when balance become 0) in Binance-chain

- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LauncherActivity.kt
> Fix multiple splash screens on cold start 

- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageWalletsDialog.kt
> Fix app crash, when user adds new coin in ManageCoins screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/HudHelper.kt
- app/src/main/res/layout/fragment_backup_words.xml
- app/src/main/res/layout/fragment_backup_words_confirm.xml
- app/src/main/res/layout/view_holder_confirmation.xml
- app/src/main/res/values/strings.xml
> Change description in backup confirmation 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/res/layout/activity_backup_words.xml
- app/src/main/res/layout/fragment_backup_words.xml
- app/src/main/res/layout/fragment_backup_words_confirm.xml
- app/src/main/res/values/strings.xml
> Backup Confirmation Words focusability fix

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
> Fix EOS tokens "not syncing" when user adds them

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- Fix app database migration
- Update BitcoinKit to fix its migration error
> Make hotfixes for release update

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/BalanceSortDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSortType.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoProviderTest.kt
Update Balance page sorting
Close #1117
> Balance page sorting

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/AlertDialogFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/sendviews/confirmation/subviews/ConfirmationSendButtonView.kt
- app/src/main/res/layout/fragment_alert_dialog.xml
- app/src/main/res/layout/view_button_with_progressbar.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoProviderTest.kt
Update alert dialog design
Show Backup alert when use clicks on Receive button of wallet(in case its not backed up yet)
Close #1023
> Show backup alert when user clicks on Receive button

- app/src/main/res/values/strings.xml
> Change button Forward to Share in receive controller

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
> Don't dim total balance if coin rate is not available

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceivePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveViewModel.kt
- app/src/main/res/layout/view_bottom_sheet_receive.xml
- app/src/main/res/values/strings.xml
> Receive for EOS should show "Receive Account"

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountCleaner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainInteractor.kt
> Clear kits when account is deleted

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionBinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEthereumAdapter.kt
> Take fee coin code from FeeCoinProvider in full transaction info

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/res/values/strings.xml
> Update text for ManageKeys delete alert dialog

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- Add optional 'fee' parameter to TransactionRecord
- Add 'sentToSelf' flag to TransactionViewItem. It's true if all From and To addresses are mine
- Update BitcoinKit
- Fix typo in method names
Close #1174
> Tx info fee

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenterTest.kt
> Don't display alert badge in settings if wallet not backed up

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/dash/SendDashInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/dash/SendDashPresenter.kt
add presenter/interactor
implement ISendDashAdapter in DashAdapter
Close #1192
> Implement separate SendDash module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressPresenter.kt
> Set address to null if there is error in validation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractorTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenterTest.kt
- Show Backup alert badge in related settings menu
- Don't show alert badge at bottom navigation bar
Close #1023
> Revert partially commit "Removal of BacklupAlert badge"

- app/src/main/res/values/styles.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Fix app background 

- app/src/main/res/layout/view_confirmation_memo_item_view.xml
- app/src/main/res/layout/view_confirmation_primary_item_view.xml
- app/src/main/res/layout/view_confirmation_secondary_data_item_view.xml
> Replace hardcoded strings in Send Confirmation screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageWalletsDialog.kt
- app/src/main/res/layout/fragment_bottom_manage_keys.xml
- app/src/main/res/values/strings.xml
> Fix AddCoin alert string

- app/src/main/res/layout/view_confirmation_primary_item_view.xml
- app/src/main/res/layout/view_transaction_full_info_item.xml
- Fix AddressView layout for short content in FullTransactionInfo and SendConfirmation
Close #1217
> Fix AddressView layout for short content

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartIndicator.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/GridHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/models/ChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/res/layout/view_bottom_sheet_chart.xml
> Calculate chart/rate diff with latest rate

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageKeysDeleteAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageKeysDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageWalletsDialog.kt
- app/src/main/res/layout/fragment_bottom_delete.xml
- app/src/main/res/layout/fragment_bottom_manage_keys.xml
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_bottom_sheet_receive.xml
- app/src/main/res/layout/view_transaction_info_item.xml
> Add close button to bottom dialogs

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/eos/BackupEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LauncherActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/AboutSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/language/LanguageSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/syncmodule/SyncModeActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/welcome/WelcomeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ShadowlessToolbarView.kt
- app/src/main/res/layout/activity_full_transaction_info.xml
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/layout/view_shadowless_toolbar.xml
- Open WelcomeActivity without slide animation on Android 9
- Add close button to Chart dialog and refactor its layout
- Show Share and Close buttons for FullTransactionActivity at top bar
- Hide Share button in FullTxInfo for Eos
Close #1161
> Show close button on Chart and FullTransactionInfo 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
- app/src/main/res/values/strings.xml
- Add singular/plural forms for send duration times
- Update FeeRateKit, take durations from FeeRate in FeeRateProvider
Related to #1136
> Take actual duration from FeeRateKit

- app/src/main/res/values/strings.xml
> Add new keys for chart

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoState.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosGreymassProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosInfraProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosProviderResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoViewModel.kt
- Open Transactions with Wallet instead of Coin
- Select Eos action by receiver name in FullTransactionInfo
Close #1101
> Refactor Full transaction info to use Wallet

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Disable transition animation when starting MainActivity as new task

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountCleaner.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStorePresenter.kt
> Fix accounts clearing on KeyInvalidated exception

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
When the balance item state or rate is updated the list may be reordered. That is why we cannot update one specific item by position as we did before. I fixed the issue by updating all items in these cases.
Close #1238
> Fix the issue with sorting by value

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
> Use native p2pkh addresses for receive and change in BTC

- app/src/main/res/values/strings.xml
> Text changes in Send

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
- app/src/main/res/values/strings.xml
> Replace plural translations in "send fee module" with plain ones

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/values/strings.xml
> Chart improvements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSortType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/BalanceSortDialogFragment.kt
- app/src/main/res/values/strings.xml
> Add balance sorting by 24h growth change

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/FeeRateProviderFactory.kt
- Add fee rate provider for Erc20 coins
- Update Bitcoin kit
Close #1136
> Minor changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionStatusWithTimeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
> Fix progress filling in transaction status view 

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
> Show coin code instead of name in Send dialog title

- app/src/main/res/values/strings.xml
> Add restore module description

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosProviderResponse.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/ProviderResponse.kt
> Show all 'transfer' actions in EOS transactions full info

- app/src/main/res/layout/activity_restore.xml
- app/src/main/res/values/strings.xml
> Add Description to Restore screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
> Do not show fiat value in tx info as "null" if it is null

- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/GridHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
> Localize day of week and month of year grid column names in charts

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeView.kt
- app/src/main/res/layout/view_send_fee.xml
> Don't show fiat fee in Send Screen, if rate is expired

- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/GridHelper.kt
> For monthly chart type show day of month instead month name

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/res/layout/fragment_balance.xml
> Hide chart button if there are no coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/drawable/ic_incoming.xml
- app/src/main/res/drawable/ic_outgoing.xml
- app/src/main/res/layout/view_holder_transaction.xml
> Show transaction direction with arrows

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateSyncScheduler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- Rename class NetworkAvailabilityManager to ConnectivityManager
Close #1272
> Refresh latest exchange rates on pull to refresh

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/res/layout/view_holder_coin.xml
> Add invisible full height button to open charts in Balance Screen

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateStatsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageKeysDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageWalletsDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ConstraintLayoutWithHeader.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
- app/src/main/res/layout/constraint_layout_with_header.xml
- app/src/main/res/layout/fragment_bottom_manage_keys.xml
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/layout/view_bottom_sheet_receive.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Add subtitle to 
- transaction info view  
- receive view
- manage keys dialog
- manage wallets dialog
- rate chart fragment
Close #1249
> Add subtitles to bottom sheet dialogs

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionStatusWithTimeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoStatusView.kt
- app/src/main/res/layout/view_transaction_info_status.xml
- app/src/main/res/layout/view_transaction_status.xml
- store confirmations thresholds in AppConfigProvider
- set Binance confirmations threshold to 1
- show transaction status progress with 3 bars
Close #1316 
Close #1322
> Reduce confirmations threshold for Bitcoin, BitcoinCash and Dash to 3

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/ManageKeysDeleteAlert.kt
- app/src/main/res/layout/constraint_layout_with_header.xml
- app/src/main/res/layout/fragment_bottom_delete.xml
- app/src/main/res/layout/fragment_bottom_manage_keys.xml
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/layout/view_bottom_sheet_receive.xml
- Change style of subtitle texts in bottom dialogs
Close #1249
> Add subtitle to delete key bottom dialog

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/SendConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/SendConfirmationPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/subviews/ConfirmationSecondaryView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/FeeRatePrioritySelectorView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenterHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/TextHelper.kt
- move translations from presenter layer to view layer
Close #1332
> Fix string localizations in send fee submodule

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
> Set gas limit to 300000 for Digix Gold and 100000 for all other ERC20

- app/build.gradle
> Update Binance kit

- app/src/main/res/values/strings.xml
> Update create wallet description

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/res/layout/view_holder_coin.xml
> Handle visibility of fiat value in Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> In balance presenter sync stats only if stats mode is switched on

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
> Refactor RateList module

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsStorage.kt
> Remove price alert for coin when corresponding wallet is disabled

- app/build.gradle
- build.gradle
> Fix issue where confirmed transaction appears as pending

- app/build.gradle
> Update bitcoin-kit to apply setting nLockTime when sending transaction

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/res/values/strings.xml
> Eos restore

- app/src/main/java/io/horizontalsystems/bankwallet/entities/ChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- wrap chart points and diff into a data class ChartData
- pass ChartData inside BalanceItem and BalanceViewItem
Close #1364
> Refactor chart data in "balance module"

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateStatsManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateSyncScheduler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/res/layout/view_holder_coin.xml
- States are: No stats (Loading), Fetched and Error
- Change return type of INetworkManager.getRateStats to Single
Close #1298
> Add chart view states in balance tab & minor refactoring

- app/src/main/res/values/strings.xml
> Change account type titles in following format: [name] wallet

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsView.kt
- app/src/main/res/color/button_secondary_text_color_selector.xml
- app/src/main/res/drawable/button_secondary_background.xml
- app/src/main/res/layout/activity_alerts.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Notifications module additions

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
See details here https://stackoverflow.com/a/48123513/1073184
> Set layoutParams for CellView when using in ViewHolder

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/NotificationFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundPriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundRateAlertScheduler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/RatesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/EmojiHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/AlertNotification.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlertRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsInteractor.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/core/factories/NotificationFactoryTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertHandlerTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/utils/EmojiHelperTest.kt
> Implement Background Price Alert Manager

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/res/layout/fragment_balance.xml
- app/src/main/res/layout/view_holder_coin.xml
- Add margin bottom to coin item in Balance tab
- Refactor view ids in balance fragment
Close #1383
> Fix flicker in Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Add database migration for PriceAlertRecord table

- app/src/main/res/layout/activity_dashboard.xml
> Update bottom sheet dim color

- app/src/main/res/values/strings.xml
> Update backup intro subtitle text

- app/src/main/res/drawable/rates_gradient_dark.xml
- app/src/main/res/drawable/rates_gradient_light.xml
> Fix RateList bottom gradient on LockScreen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/res/layout/view_holder_coin.xml
> Normalize balance card paddings

- app/src/main/java/io/horizontalsystems/bankwallet/components/CellRightView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/components/CellView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/dialogs/PriceAlertStateSelectorDialog.kt
- app/src/main/res/drawable/ic_down.xml
- app/src/main/res/layout/activity_alerts.xml
- app/src/main/res/layout/fragment_alert_dialog_single_select.xml
- app/src/main/res/layout/view_cell.xml
- app/src/main/res/layout/view_cell_right.xml
> Replace spinner with a custom popup selector in Notifications

- app/src/main/res/values/strings.xml
> Change text for restore module

- app/build.gradle
> Fix using custom locale on old Androids

- app/src/main/res/layout/view_holder_coin.xml
> Add space around chart preview in balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/RequestCode.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestorePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/res/layout/activity_restore_eos.xml
- app/src/main/res/layout/activity_restore_words.xml
- app/src/main/res/layout/view_multiple_input_edit_text.xml
- app/src/main/res/values/strings.xml
> Add text to Restore pages

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RateDifferenceTextView.kt
- app/src/main/res/drawable/ic_down_red.xml
- app/src/main/res/drawable/ic_up_green.xml
- app/src/main/res/layout/view_holder_coin_rate.xml
- app/src/main/res/layout/view_rate_difference.xml
> Apply ui changes to LockScreen rate list

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/res/drawable/button_secondary_background.xml
- app/src/main/res/values/styles.xml
- Fix gradient for SecondaryButton background
- Fix home button click to close EosRestoreActivity
ref #1423, #1446
> Make small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/options/RestoreOptionsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/res/layout/activity_restore.xml
- app/src/main/res/layout/activity_restore_options.xml
- Adjust RestoreOption text paddings
- Use scrollable toolbar in RestoreOptionsActivity and RestoreActivity
- Fix clipped Restore on returning from RestoreWords page after showing 3rd party keyboard alert
ref #1404, #1440
> Restore pages refactoring

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppStatusManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppVersionManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SystemInfoManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/AppVersion.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/ReportProblemActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/ReportProblemModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/ReportProblemPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/ReportProblemRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
- app/src/main/res/layout/activity_app_status.xml
- app/src/main/res/layout/activity_report_problem.xml
- app/src/main/res/values/strings.xml
- show basic info about app and device
- add copy button
- add AppVersionManager for tracking app version history
- add AppStatusManager for gathering app status info
targeting #1374
> Add "app status" module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenter.kt
- app/src/main/res/layout/fragment_pin.xml
> Show fingerprint input on blank screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsPresenter.kt
- app/src/main/res/layout/activity_alerts.xml
- Sort coins by A-Z in Notifications screen
- Use scrollable toolbar in Notifications screen
ref #1451
> Notifications screen small fixes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RateDifferenceTextView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RotatingCircleProgressView.kt
- app/src/main/res/drawable/coin_icon_square.xml
- app/src/main/res/layout/view_holder_coin.xml
- app/src/main/res/layout/view_holder_coin_rate.xml
- app/src/main/res/values/strings.xml
> Change wallets design in Balance tab

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundPriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundRateAlertScheduler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsView.kt
- app/src/main/res/layout/activity_alerts.xml
- app/src/main/res/values/strings.xml
> Add notification alert switch

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
> Fix text scrolling for EditText in Restore

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- Catch exception in TransactionsFragment
- Catch exception when showing CustomKeyboard alert
ref #1463, #1468
> Fix crashes 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppStatusManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EosKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusActivity.kt
> Show wallets status and kits' status info in "app status" module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionBinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BinanceChainProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/ProviderResponse.kt
> Show memo field in FullTransactionInfo for Binance

- app/src/main/java/io/horizontalsystems/bankwallet/modules/reportproblem/appstatus/AppStatusActivity.kt
- app/src/main/res/layout/activity_app_status.xml
- app/src/main/res/menu/app_status_menu.xml
> Make app bar in app status page collapsible

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/res/layout/activity_restore_words.xml
- Allow entering only latin letters
- Allow entering only spaces and new lines
ref #1475
> Restrict user input in RestoreActivity with only allowed characters

- app/src/main/java/io/horizontalsystems/bankwallet/components/CellView.kt
- app/src/main/res/layout/view_cell.xml
> Set CellView height by subtitle existence

- app/build.gradle
> Update EthKit to get fix for duplicated transactions

- app/src/main/res/layout/activity_restore_words.xml
> Allow user to enter any character in Restore input

- app/src/main/res/values/strings.xml
> Minor text changes

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountCreator.kt
- app/src/main/res/layout/activity_restore_options.xml
- app/src/main/res/values/strings.xml
> Use bip49 derivation type for 12 words mnemonic account

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
> Hide fiat when value is 0 on BalanceTab

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
> Convert restore words to lowercase

- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/Utils.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/MultipleInputEditTextView.kt
> Show alert when custom keyboard is used for EosRestore

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/XRateManager.kt
> Add XRateManager for working with XRatesKit

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundRateAlertScheduler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertHandler.kt
> Fix latest rate update for PriceAlert notifications

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactoryTest.kt
- change presenter/view interaction so that presenter now sets view items to view, rather than view requesting view items from presenter
- use new XRatesKit
targeting #1400
> Refactor balance module

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartCurve.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartGrid.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/GridHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/models/ChartConfig.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceChartData.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/res/color/stateful_button_grey_color.xml
- app/src/main/res/drawable/button_steel_background.xml
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/layout/view_holder_coin.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> Sync rate charts from "x-rates-kit"

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
> Fix showing last update time on RateListPage

- app/build.gradle
> Update XRateKit to apply bug fix for historical rates

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
- app/src/main/res/values/strings.xml
> Add minimum remainder check for Erc20 tokens in SendModule

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
> Hide link and share button for horizontalsystems.xyz provider in fullTxInfo

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BackgroundPriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RateDifferenceTextView.kt
> Fix Holo token rates

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ShadowlessToolbarView.kt
> Update share button visibility on provider change in FullTransactionInfo

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/dash/SendDashHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/eos/SendEosHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsRouter.kt
- app/src/main/res/drawable/ic_experimental.xml
- app/src/main/res/layout/activity_bitcoin_hodling.xml
- app/src/main/res/layout/activity_experimental_features.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values/strings.xml
- add "Experimental Features" to main settings
- add "Bitcoin Hodling" settings to "Experimental Features"
- show lock time option in Send only if it is enabled 
- make "holderModule" optional in ISendHandler
- take enabled setting through ILocalStorage
ref #1369
> Hodler settings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> Run IInteractorDelegate methods sequentially in BalancePresenter

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
- app/src/main/res/values/strings.xml
> Add check for max limit when sending coins

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
> Fix concurrency issue for adapters initialization

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/res/values/strings.xml
> Show error details when sending failed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/MaxSupplyMap.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/values/strings.xml
> Show coin MaxSupply value in Chart dialog

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/SendConfirmationModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/SendConfirmationPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/subviews/ConfirmationPrimaryView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/subviews/ConfirmationSecondaryView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/hodler/SendHodlerFragment.kt
- app/src/main/res/layout/view_confirmation_primary_item_view.xml
- app/src/main/res/layout/view_confirmation_secondary_item_view.xml
- app/src/main/res/values/strings.xml
- add extension to LockTimeInterval for getting string resource id
ref #1369
> Add lock time info to send confirmation page

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressPresenter.kt
- app/src/main/res/values/strings.xml
> Hodler address validation

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/MaxSupplyMap.kt
> Add total supply for Populous and fix for Revain

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletStorage.kt
> Fix enabled wallets storage parameter coinId

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
> Prevent SendModule amount validation when value is 0

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreManager.kt
> Fix KeyStore validation

- app/build.gradle
- build.gradle
- new bitcoin-kit has api and send errors in status info
ref #1583
> Update bitcoin-kit 

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsPresenter.kt
> Add validation for words count in Restore

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
> Disable language setting on old Androids

- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/res/drawable/label_background.xml
- app/src/main/res/layout/view_holder_coin.xml
- app/src/main/res/values/styles.xml
> Show coin type labels on BalancePage

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
> Auto-scroll to top on new incoming transactions

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LockManager.kt
> Lock screen after unlock has expired

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemDiff.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/IconView.kt
- app/src/main/res/layout/view_holder_coin.xml
> Balance tab optimization

- app/src/main/res/layout/view_holder_coin.xml
> Fix the expand/collapse animation issue on balance cells

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SystemInfoManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletRemover.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemDiff.kt
> Optimize balance cell update

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/res/layout/view_holder_coin.xml
> Fix coin type label background

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
> Timelocked transactions

- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
> Display TimeLocked transaction's coin value correctly

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
> Rename key "TransactionInfo_LockTime" to "TransactionInfo_LockedUntil"

- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LanguageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/localehelper/LocaleHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
> Fix language switch

- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartCurve.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartGrid.kt
> Use "anti-aliasing-flag" in Canvas to smooth letters

- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartIndicator.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/res/drawable/button_green_background.xml
- app/src/main/res/values/colors.xml
> Update the "Remus" light and dark colors

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
> Check words count to avoid using BTC account in BNB and vice versa

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeView.kt
Ref #1658 
- Remove fee-rates listener implementation.
> Remove feerates listener implementation.

- app/build.gradle
- Upgrade Fee-Rates kit dependency to db55b0c commit (BTC-Core request parameters updated to 1-10-100 values).
> Upgrade FeeRate-Kit dependencies.

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ScaleHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/res/layout/view_bottom_sheet_chart.xml
> Rate chart improvements

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt
> Fix the issue with looping alert when user changes OS PIN

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
Ref #1664 
- Upgrade FeeRateKit dependencies
- Add BitcoinCore RPC url to config.
> Upgrade FeeRateKit dependencies

- app/build.gradle
> Update bitcoin-kit, fix synced until date in app status

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Update ethereum-kit, remove fee from EURS erc20 token

- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
> Change color styles

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
Ref #1680 
- Integrate Eth-Kit with tx error handling changes
> Integrate Eth-Kit with transaction error handling changes.

- app/src/main/res/values/styles.xml
> Fix color for style

- app/build.gradle
> Upgrade EthKit dependencies

- app/src/main/res/values/colors.xml
> Change colors

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionBitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
> Format time by system preference

- app/src/main/res/values/strings.xml
Ref #1689  
- Change title and subtitles text in Address format options view.
> Change address-format options text.

- app/src/main/res/values/strings.xml
> Remove text

- app/src/main/res/layout/view_holder_coin_setting_section_description.xml
> Change link color in CoinSettings screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CoinItemsAdapter.kt
> Show coin name as title and code as subtitle

- app/src/main/res/layout/activity_restore_words.xml
> Disable word suggestion on Restore screen

- app/src/main/res/layout/activity_restore_eos.xml
> Increase padding between inputs in Eos Restore

- app/src/main/java/io/horizontalsystems/bankwallet/modules/coinsettings/CoinSettingsPresenter.kt
- app/src/main/res/values/strings.xml
> Change text for description in Coin Settings

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PredefinedAccountType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coinsettings/CoinSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/coinsettings/CoinSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/lockscreen/LockScreenActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsModule.kt
- app/src/main/res/layout/view_holder_coin_setting_item.xml
- Replace Serializable with Parcelable in CoinType
- Optimize CoinSettings screen for smoother opening
ref #1719
> Optimize CoinSettings opening

- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartCurve.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartGrid.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/models/ChartConfig.kt
> Format low and high rate values

- app/build.gradle
- needed for showing app version code in settings and welcome pages
> Set is_release flag to false for hockey app builds

- app/build.gradle
Ref #1721 
- Update EOS-Kit dependencies with Block-Producer RPC url changes.
> Upgrade EOS-Kit dependencies.

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
> Correctly display error messages when sending coins

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ShadowlessToolbarView.kt
- app/src/main/res/color/stateful_text_button_jacob_color.xml
- app/src/main/res/layout/view_shadowless_toolbar.xml
> Remove stateful color from ShadowlessToolbarView

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorterTest.kt
> Improve coins sorting by balance

- app/build.gradle
Ref #1721 
- Upgrade EOS-Kit dependencies (With RPC url fixes.)
> Upgrade EOS-Kit dependencies (With RPC url fixes.)

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
> Remove some currencies

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinFragment.kt
> Fix fingerprint scanner dialog hide on cancel click

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/dataprovider/DataProviderSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BinanceChainProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockchairProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockdozerBitcoinCashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BtcComProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EosGreymassProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/InsightDashProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoErrorFragment.kt
- app/src/main/res/layout/fragment_full_transaction_info_error.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoPresenterTest.kt
ref #1731 
Refactor full transaction info providers
- add pingUrl to Provider interface. Use this url to ping and show whether provider is online. It is basically a method in block explorer API without any parameters (such as get first block, get node info, get price etc).
- show transaction not found error
> Correctly handle transaction not found error and offline error in Transaction full info

- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoInteractor.kt
> In tx full info page handle no internet connection

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
Ref #1751  
- Hide text "Loading" when sending DASH.
> Hide 'Loading' text when sending DASH.

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/res/drawable/coin_icon_square.xml
- app/src/main/res/drawable/stateful_rate_diff_background.xml
- app/src/main/res/layout/view_holder_coin.xml
> Remove chart from wallet view in Balance page

- app/build.gradle
Ref #1736 
- Upgrade BTC-Kit dependencies (with BCH initial sync fix).
> Upgrade BTC-Kit dependencies (with BCH initial sync fix).

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/CoinSpaceBitcoinCashProvider.kt
- remove blockdozer.com provider
ref #1764
> Add transaction full info provider coin.space for BCH

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
> Don't hide coin type label on sync

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- update fee rate labels when fee rates change
ref #1770
> Minor bug fix in send page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ManagePinPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/pin/unlock/UnlockPinPresenterTest.kt
> Fix crash with invalid index on Pin Fragment page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
> Add space between value and letter in RateChart

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransactionViewItemFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoViewModel.kt
- app/src/main/res/drawable/ic_doublespend.xml
- app/src/main/res/layout/activity_info.xml
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_holder_transaction.xml
- app/src/main/res/values/strings.xml
- show icon for double spend transactions in transactions tab
- show double spend info in transaction info bottom sheet
ref #1769
> Show double spend in transactions list and transaction info bottom sheet

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Fix crash in migration from version 12 to 13

- app/build.gradle
Ref #1790 
- Upgrade Eos-kit dependencies (fixed by lowering offset to 100).
> Upgrade Eos-kit dependencies (with offset fix).

- app/build.gradle
Ref #1790 
- Upgrade Eos-kit dependencies (with tx.fetch fix).
> Upgrade Eos-kit dependencies (with tx.fetch fix).

- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/DateHelper.kt
Ref #1787 
- Fix date locale-specific ordering format
> Fix date locale-specific ordering format.

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/lib/chartview/ChartCurve.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Refactor currency formatter

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceivePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewitems/AddressItem.kt
Ref #1791
- Add Bitcoin address format information to Receive-Tab
- Change Balance tab, syncing status date format
> Add bitcoin address format info

- app/src/main/java/io/horizontalsystems/bankwallet/core/security/KeyStoreManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStorePresenter.kt
> Fix keystore resetting on key invalidation

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Remove DAI and SAI token from rateManager filter. Add PPT and PGL

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt
- app/src/main/res/values/strings.xml
> Change text for address type in receive view

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateCoinMapper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/EmojiHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
> Disable chart opening for blocked coins

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/basecurrency/BaseCurrencySettingsActivity.kt
- app/src/main/res/layout/activity_currency_switcher.xml
- app/src/main/res/values/strings.xml
> Add info text to Base Currency screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
> Add fiat fee to transaction info screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/address/SendAddressView.kt
- app/src/main/res/layout/view_address_input.xml
ref #1830 
- use single EditText for address input
- fix bug with recursive address entering (enter address -> validate -> enter -> validate and so on)
- enable paste button even if clipboard is empty
> Refactor send address module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenter.kt
- sync amount and fee submodules when exchange rate changes and app returns from background
ref #1838
> Make exchange rate in Send module dynamic

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/ContactActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/appstatus/AppStatusActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/viewHelpers/HudHelper.kt
- increase toast showing duration from 500 ms to 800ms
ref #1836
> Show success message after wallet creation and restore

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartHelper.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartVolume.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartPoint.kt
> Show volume bars in ChartView

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsAlertDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsRouter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
> Rename CoinSettings to BlockchainSettings

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateFormatter.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve.kt
> Fix fiat formatting for top/low values in charts

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateFormatter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/utils/EmojiHelperTest.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve.kt
- uikit/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
> Update coin rates rounding logic

- app/build.gradle
> Increment version code to 22 and put api keys for releаse

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Disable EOSDT rates

- app/src/main/res/layout/activity_restore.xml
- app/src/main/res/values/strings.xml
> Update text in Restore Screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosModule.kt
- app/src/main/res/layout/activity_restore_eos.xml
- app/src/main/res/values/strings.xml
> Remove description text from EOS restore

- app/src/main/res/layout/activity_welcome.xml
- uikit/views/src/main/AndroidManifest.xml
> Use always dark background for WelcomeScreen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
> Fix Receive/RateChart fragments crash on restor

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
> Fix deprecation in ConnectivityManager

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/res/values/strings.xml
- Change texts in Settings > Experimental
- Remove unneeded code
ref #1882
> Change texts in Settings > Experimental page

- app/src/main/res/layout/view_holder_coin_manage_item.xml
- uikit/icons/src/main/res/drawable/ic_add.xml
- uikit/views/src/main/java/io/horizontalsystems/views/AlertDialogFragment.kt
- Fix crashing Eos Create alert, by reverting code
- Replace arrow with plus icon, in Manage Wallets
ref #1885, #1887
> Fixes in Manage wallets

- app/build.gradle
- Upgrade bitcoin-kit dependencies (with proxy options implemented).
> Upgrade bitcoin-kit dependencies (with proxy options implemented).

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetManager.kt
> Fix Tor connection logging

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/welcome/WelcomeActivity.kt
- app/src/main/res/layout/activity_settings_security.xml
- app/src/main/res/layout/activity_welcome.xml
> Hide Tor switch in Welcome and Settings

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/res/values/strings.xml
> Handle Binance Memo required error in Send

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/res/layout/view_bottom_sheet_chart.xml
- app/src/main/res/values/strings.xml
- components/chartview/build.gradle
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartVolume.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/GridHelper.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- components/views/src/main/res/drawable/stateful_button_jeremy_color.xml
- components/views/src/main/res/values/styles.xml
- core/src/main/java/io/horizontalsystems/core/helpers/DateHelper.kt
> Improve ChartView design

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/res/xml/network_security_config.xml
> Replace Btc feerate provider

- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Hud text alignment

- app/src/main/res/layout/activity_send.xml
- components/views/src/main/res/layout/view_shadowless_toolbar.xml
> Fix top padding in Send page

- app/src/main/res/layout/activity_welcome.xml
- app/src/main/res/values/strings.xml
> Fix title in Welcome Screen

- app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/res/values/strings.xml
> Localize Binance backend error

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
> In manage coins load accounts and wallets for cold start

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Add Bip Migration

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/BaseActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/eos/BackupEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/ContactActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/appstatus/AppStatusActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoItemView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
- Refactor HudHelper, remove usages of Application instance
- Check for third-party keyboard when entering eos active private key
- Update fee-rate-kit, remove context param from FeeRateKit constructor
- Remove usages of application context where possible.
- Increment version to 0.13.0.
ref #1910
> Minor refactoring

- app/build.gradle
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ru/strings.xml
- core/src/main/java/io/horizontalsystems/core/helpers/LocaleHelper.kt
> Fix custom language loading

- app/src/main/res/values/strings.xml
- components/pin/src/main/res/values/strings.xml
> TOR settings: change title and description

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorConnectionActivity.kt
- app/src/main/res/layout/activity_tor_connection.xml
- app/src/main/res/values/strings.xml
- Add localized strings for Tor status view.
- Fix tor status spinner.
- Upgrade NetKit dependencies
> Add localized strings for Tor status view

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NotificationManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorConnectionActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/torpage/TorPageActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/torpage/TorPageInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/torpage/TorPageModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/torpage/TorPagePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/torpage/TorPageView.kt
- app/src/main/res/layout/activity_tor_connection.xml
- app/src/main/res/values/strings.xml
> Show Tor notification alert when notifications are disabled

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsActivity.kt
- components/views/src/main/res/values/themes.xml
> Show dark background when app cold starts

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/cryptonews/CryptoNewsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/cryptonews/CryptoNewsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/cryptonews/CryptoNewsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/cryptonews/CryptoNewsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/cryptonews/CryptoNewsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/LockableNestedScrollView.kt
- app/src/main/res/layout/activity_rate_chart.xml
- app/src/main/res/layout/fragment_crypto_news.xml
- app/src/main/res/layout/view_holder_crypto_news.xml
- app/src/main/res/values/strings.xml
> Display latest coin news

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/FeeRateProviderFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FeeRateProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/FullTransactionInfoFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/BlockchairProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/MaxSupplyMap.kt
- app/src/main/res/xml/network_security_config.xml
> Integrate Litecoin

- app/src/main/res/values/strings.xml
> Settings -> About: Change text

- app/build.gradle
Ref #1969 
- Fix TOR process not terminating on App close event bug (Fix TOR stop method by correcting PS command's arguments and responses.).
> Fix TOR process not terminating on App close event bug.

- app/build.gradle
> Update libraries (appcompat, gson, …)

- app/src/main/res/layout/activity_rate_chart.xml
- app/src/main/res/layout/fragment_crypto_news.xml
- app/src/main/res/layout/view_holder_crypto_news.xml
> Crypto news

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/res/xml/network_security_config.xml
> Update bitcoin-kit and url of Litecoin full transaction info provider

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/MaxSupplyMap.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
> Show N/A in chart when market cap and circulation is 0

- app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettingslist/BlockchainSettingsListAdapter.kt
- app/src/main/res/values/strings.xml
> Make small text fixes for Coin and Account Managers

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoItemView.kt
- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- app/src/main/res/layout/view_address_input.xml
- app/src/main/res/layout/view_transaction_info_item.xml
- app/src/main/res/values/attrs.xml
Ref #1991 
- Correct Address Field and Share button margins in tx-info view.
- Correct size of the Paste and Take QRCode buttons in send view
> Correct Address Field and Share button margins in send,tx-info views.

- app/src/main/res/layout/view_address_input.xml
- Change paste button width to "wrap_content"
> Correct paste button width in Send view.

- app/src/main/res/layout/transaction_info_bottom_sheet.xml
- Set share button color  to leah in Tx-info view.
> Fix share button color (leah) in Tx-info view.

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateAppManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/rateapp/RateAppDialogFragment.kt
- app/src/main/res/layout/fragment_rate_app_dialog.xml
- app/src/main/res/values/strings.xml
Ref #1264 
- Implement RateApp module
- Create custom view (DialogFragment) for RateApp
> Implement RateApp module with Custom view

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
- app/src/main/res/layout/fragment_transactions.xml
> Display syncing spinner on Transactions tab when wallet is syncing

- app/src/main/res/drawable/circular_spinner.xml
- app/src/main/res/drawable/ic_spinner.xml
- app/src/main/res/layout/fragment_transactions.xml
> Make custom syncing spinner on Transactions tab to control its speed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroActivity.kt
- app/src/main/res/drawable/ic_knowledge.xml
- app/src/main/res/layout/activity_intro.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/scene_intro.xml
> Intro updates

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
Ref #2027 
- Disable xrates for SAI Coin (Do not show xrates)
> Disable xrates for SAI Coin.

- app/src/main/res/layout/view_holder_account.xml
> Fix left margin for icon in ManageKeys

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionDataSortingType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/hodler/SelectorDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsViewModel.kt
- app/src/main/res/layout/activity_settings_privacy.xml
- app/src/main/res/values/strings.xml
> Implement Transaction Sorting UI

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Hard code communication mode values for Eos and Binance

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CommunicationSettingsManager.kt
> Get/set communication settings for Erc20 using CoinType.Ethereum

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
> Don't show progress in text for ETH, EOS, Binance coins

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionDataSortingType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/res/values/strings.xml
> Show 3rd Transaction sorting option(Off) in UI

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
> Store hide balance option to persistent storage

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordDataSource.kt
> Refresh transaction pools when wallet adapters refreshed

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsActivity.kt
- app/src/main/res/layout/activity_settings_privacy.xml
- app/src/main/res/layout/view_holder_coin.xml
> Make UI fixes to Privacy page and Balance item

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ActivityLifecycleCallbacks.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorStatusInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorStatusModule.kt
Ref #1953 , #2036 
- Remove NetKit dependencies.
- Integrate TorKit
> Integrate TorKit (instead NetKit)

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/HorsysProvider.kt
- app/src/main/res/xml/network_security_config.xml
Ref #2021 
- Upgrade btc-kit deps
- Update btc-testnet API url.
> Upgrade btc-kit deps. Update btc-testnet API url.

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinHandler.kt
- app/src/main/res/layout/view_hodler_input.xml
- app/src/main/res/layout/view_send_fee.xml
> Reorder send components

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/lockscreen/LockScreenActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RatesInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RateDiffView.kt
- app/src/main/res/layout/view_holder_coin_list_source.xml
- app/src/main/res/layout/view_holder_coin_rate.xml
- app/src/main/res/layout/view_holder_coin_section_header_portfolio.xml
- app/src/main/res/layout/view_holder_coin_section_header_top_100.xml
- app/src/main/res/layout/view_holder_rate_list_spinner.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/color/stateful_expirable_rate_text_color.xml
> Show coins top 100 list on the Lockscreen

- app/build.gradle
Ref #2095 
- Upgrade TorKit dependencies (with "Native library extraction" error fix).
> Upgrade TorKit dependencies (with "Native library extraction" error fix).

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CommunicationSetting.kt
Ref #2045 
- Update ETH communication mode before Tor connection starts (Set ethereum communication mode to Infura)
> Update ETH communication mode before Tor connection starts

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
- app/src/main/res/layout/activity_dashboard.xml
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Hide balance page when app resumes with locked state

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
> Update chart points through message queue

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsAlertDialog.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsViewModel.kt
- app/src/main/res/values/strings.xml
Ref #2045 
- Show Notification Dialog when Tor updates Ethereum communication mode (When Infura set instead Infura)
> Show Notification when Tor updates Ethereum communication mode

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/res/layout/activity_rate_chart.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve.kt
> Fix lag when opening Chart

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
> Load rate chart when CryptoNews fragment already attached to an activity

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListView.kt
- app/src/main/res/drawable/pin_pager_circle.xml
- app/src/main/res/drawable/pin_pager_circle_selected.xml
- app/src/main/res/layout/activity_lockscreen.xml
- app/src/main/res/layout/fragment_rates.xml
- app/src/main/res/layout/view_holder_coin_section_header_portfolio.xml
- app/src/main/res/values/strings.xml
- core/src/main/java/io/horizontalsystems/core/helpers/DateHelper.kt
> Make small UI changes in Lockscreen page

- app/build.gradle
- components/pin/build.gradle
> Update bitcoin-kit and other dependencies

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ActivityLifecycleCallbacks.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorStatusInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorStatusModule.kt
Ref #2126 
- Replace NetKit with TorKit
- Update, refactor NetManager implementation to TorManager
- Update TorKit dependencies (with update on tor.so file names to libtor.so)
> Replace NetKit with TorKit

- app/build.gradle
- bitcoin-kit
- ethereum-kit
- hd-wallet-kit
ref #1864
> Update wallet kits

- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/ConfirmationDialog.kt
> Handle cancellation when clicking close, back, outside, swipe down

- app/build.gradle
- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
- components/pin/src/main/res/layout/view_pin_page.xml
> Center elements on PIN page

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsViewModel.kt
Ref #2142 
- Show/Hide Blockchain settings based on Wallet account origin (create/restore) or when it starts from Welcome screen.
> Show/Hide Blockchain settings based on Wallet account origin (create/restore).

- app/build.gradle
- app/src/main/res/layout/activity_tor_connection.xml
Ref #2141 
- Upgrade torkit dependencies (with tor status handling issues fixed)
- Correct Tor Connection activity button styling.
> Upgrade torkit dependencies

- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CoinItemsAdapter.kt
Ref #2160, #2162
- Replace onClick listener with onCheckedChange listener for switch component in coinitems adapter view.
> Fix bug in Switch component behavior in CoinItems view

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/res/layout/view_holder_coin_rate.xml
- components/views/src/main/res/color/stateful_lockscreen_coin_item_background_color.xml
- components/views/src/main/res/drawable/lockscreen_clickable_background.xml
> Highlight coin item on click in Lockscreen

- app/src/main/res/layout/activity_rate_chart.xml
> Fix chart onClickInfo positioning bug

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
> Don't show rate when its value is 0

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PredefinedAccountTypeManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysAdapter.kt
- app/src/main/res/layout/activity_backup.xml
- app/src/main/res/layout/activity_backup_words.xml
- app/src/main/res/layout/fragment_backup_words.xml
- app/src/main/res/layout/fragment_backup_words_confirm.xml
- app/src/main/res/layout/view_holder_account.xml
- app/src/main/res/menu/backup_words_menu.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/java/io/horizontalsystems/views/ManageAccountView.kt
- components/views/src/main/res/layout/view_manage_account_view.xml
- components/views/src/main/res/values/attrs.xml
> Manage wallets updates

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/res/layout/activity_rate_chart.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
> Fix chart flickering on load

- app/src/main/res/layout/view_holder_account.xml
> Show attention icon for Backup

- app/src/main/res/drawable/stateful_rate_diff_background.xml
- app/src/main/res/layout/view_holder_coin.xml
> Update price change block style

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/MaxSupplyMap.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
ref #2172 
Update xrates-kit, apply changes related to top markets: 
- remove loading of top markets in fragment
- load top markets in presenter onLoad and when portfolio market info updates
- pass CoinMarketCap API key when creating XRatesKit
> Update xrates kit

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsPresenter.kt
- app/src/main/res/layout/activity_settings_security.xml
- app/src/main/res/values/strings.xml
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinModule.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinView.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/NumPadItemsAdapter.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/PinManager.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/SecureStorage.kt
- components/pin/src/main/java/io/horizontalsystems/pin/unlock/UnlockPinInteractor.kt
- components/pin/src/main/java/io/horizontalsystems/pin/unlock/UnlockPinModule.kt
- components/pin/src/main/java/io/horizontalsystems/pin/unlock/UnlockPinPresenter.kt
- components/pin/src/main/res/values/strings.xml
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
Ref #2201 
- Enable all (including Weak (Face ID)) biometric authentication methods available and active in the System.
> Enable all available biometric auth. methods

- components/views/src/main/res/color/button_transparent_text_color.xml
> Add button on-press event styling to tx. filter buttons.

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ViewHolderCoin.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/views/SyncErrorDialog.kt
- app/src/main/res/layout/fragment_bottom_sync_error.xml
- app/src/main/res/values/strings.xml
> Implement Sync error interaction on Balance Page

- app/src/main/res/layout/activity_tor_connection.xml
- app/src/main/res/layout/view_holder_filter.xml
- components/views/src/main/res/drawable/button_transparent_background.xml
- components/views/src/main/res/values/styles.xml
> Correct Secondary transparent button styling (border, height).

- app/src/main/res/layout/view_holder_filter.xml
- components/views/src/main/res/values/styles.xml
> Fix/Update "secondary transparent button" styling

- components/views/src/main/res/values/styles.xml
> Update 'ButtonSecondary' style paddings (12db, 4.5dp).

- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysAdapter.kt
- app/src/main/res/layout/activity_address_format_settings.xml
- components/views/src/main/res/drawable/button_secondary_background.xml
Ref #2213 
- Update ''ButtonSecondary" style colors.
- Show/Hide address format settings based on Coin Derivation settings
> Show/Hide address format settings based on Coin Derivation settings

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalancePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/views/SyncErrorDialog.kt
> For SyncErrorDialog show Change Source option only for supporting coins

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BinanceKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EosKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/providers/EtherscanProvider.kt
> Fix refreshing of Erc20 transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ViewHolderCoin.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
> Prevent double clicks

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- components/views/src/main/java/io/horizontalsystems/views/SingleSwitchListener.kt
> Prevent fast switch change for SetPin

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
> Fix wrong connectivity state

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Disable API Restore option for Bitcoin Cash

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
> Reset lock icon

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionDetailsAdapter.kt
> Do not show attention icon for unlocked transaction

- app/src/main/res/layout/view_transaction_info_item.xml
> Set max width of address field

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt
> Update bitcoin kit, remove redundant database converters

- components/views/src/main/res/drawable/button_secondary_background.xml
> Fix ButtonSecondary color styling.

- app/build.gradle
Ref #2282 
- Update FeerateKit dependencies ( with feerate's lowpriorityduration to 10 hour for BTC change)
> Change feerate's lowpriorityduration to 10 hour for BTC

- components/pin/src/main/java/io/horizontalsystems/pin/core/SecureStorage.kt
- components/pin/src/main/java/io/horizontalsystems/pin/unlock/UnlockPinPresenter.kt
> Fix compatibility issues with old and new biometric auth.

- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsInteractor.kt
> Fix memory leak in Transactions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/BackupActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/eos/BackupEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/ContactActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/appstatus/AppStatusActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/view/CreateWalletActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/views/FullTransactionInfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/info/InfoActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/RestoreActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- components/pin/src/main/java/io/horizontalsystems/pin/PinFragment.kt
- components/views/src/main/res/values/styles.xml
- core/build.gradle
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
> Replace all toast alerts with Snackbar

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
> Validate EOS account in SendModule

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsPresenter.kt
> Optimize starting of ManageWallets and RestoreCoins activities 

- app/build.gradle
> Fix the issue with syncing status when internet is disconnected

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
> Migrate BCH sync mode in database

- app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addressformat/AddressFormatSettingsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/views/ManageWalletsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsActivity.kt
- app/src/main/res/values/strings.xml
> Fix Litecoin address prefix in Derivation description

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fa/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-ko/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tr/strings.xml
- app/src/main/res/values-zh/strings.xml
> Add localizations for address format info

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionBinanceAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionBitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/fulltransactioninfo/adapters/FullTransactionEthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenterHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeePresenterHelper.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionDetailsAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/RateDiffView.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Number formatter refactoring

- app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
- app/src/main/res/drawable/ic_qr_scanner_corner_rounding.xml
- app/src/main/res/layout/activity_qr_scanner.xml
- Make rounded corners
- Fix on BackPressed
- Fix cancel button covers system bottom navigation
ref #2269
> Add fixes for qr scanner

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
> Apply custom logic for coin value formatting in Balance

- app/src/main/res/layout/view_address_input.xml
- app/src/main/res/layout/view_button_proceed.xml
- app/src/main/res/layout/view_button_with_progressbar.xml
- app/src/main/res/layout/view_confirmation_primary_item_view.xml
- app/src/main/res/layout/view_confirmation_secondary_item_view.xml
- app/src/main/res/layout/view_send_fee.xml
- app/src/main/res/layout/view_send_memo.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/values/type.xml
- core/src/main/res/values/strings.xml
> Make UI fixes in Send Module

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/res/layout/view_hodler_input.xml
- app/src/main/res/layout/view_send_fee.xml
> Set Leah color for Tx speed and TimeLock in SendModule

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Fix balance tab issues

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateTopListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/TopListSortType.kt
- app/src/main/res/values/strings.xml
> Order by rank instead of market cap

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/transactionInfo/TransactionInfoView.kt
- app/src/main/res/layout/activity_send.xml
- core/src/main/java/io/horizontalsystems/core/helpers/HudHelper.kt
Ref #2268 
- Display snackbar on top Keyboard
- Hide snackbar when txInfo bottomSheet collapsed.
- Fix ***ConfirmationFragment rootView not found** error in SendActivity
> Fix snackbar display and sendActivity bugs

- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendView.kt
- Fix Erc20 token fee gas estimation
- Don's show old error in send confirm, on resending
ref #2300
> Fix Erc20 token send

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendActivity.kt
> Fix success message closing immediately when doing send operation

- components/views/src/main/res/values/styles.xml
> Update buttonSecondary left/end padding styling.

- app/build.gradle
> Fix high estimated gas from Incubed

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RandomProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsPresenter.kt
> Fix backup confirm not showing words higher than 12

- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/ViewHolderGuide.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlockViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideVisitorBlock.kt
- app/src/main/res/layout/view_holder_guide_image.xml
- app/src/main/res/layout/view_holder_guide_paragraph.xml
- app/src/main/res/layout/view_holder_guide_preview.xml
- components/icons/src/main/res/drawable/ic_placeholder.xml
> Guides additions

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
> Keep tabs in memory for fast switching

- app/src/main/java/io/horizontalsystems/bankwallet/modules/managecoins/ManageWalletsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restorecoins/RestoreCoinsPresenter.kt
> Remove delay when loading initial data

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AppStatusManager.kt
> LTC app status

- app/src/main/res/layout/fragment_rates.xml
- app/src/main/res/layout/view_holder_coin_list_source.xml
- app/src/main/res/layout/view_holder_date.xml
- app/src/main/res/layout/view_holder_title.xml
- components/views/src/main/res/color/stateful_lockscreen_coin_item_background_color.xml
> Set lock screen cells background color to ColorClaude

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
> Update SNX erc20 token contract

- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlockViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideContentAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideViewModel.kt
- app/src/main/res/layout/view_holder_guide_footer.xml
> Add footer to guide

- app/src/main/res/layout/fragment_rates.xml
- app/src/main/res/layout/view_holder_coin_list_source.xml
- app/src/main/res/layout/view_holder_date.xml
- app/src/main/res/layout/view_holder_title.xml
> Fix background colors for lock screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideActivity.kt
- app/src/main/res/layout/activity_guide.xml
- app/src/main/res/layout/fragment_guides.xml
- app/src/main/res/layout/view_holder_guide_footer.xml
- app/src/main/res/layout/view_holder_guide_paragraph.xml
- app/src/main/res/values/strings.xml
- components/views/src/main/res/values-night/themes.xml
- components/views/src/main/res/values/attrs.xml
- components/views/src/main/res/values/themes.xml
> Guide updates

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/CoinType.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumInteractor.kt
> Integrate dynamic gas limit calculation for Ethereum

- app/build.gradle
> Increase build version to 29

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatterTest.kt
> Do not show cents if value >= 1000 for fiats

- app/src/main/java/io/horizontalsystems/bankwallet/modules/contact/ContactActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/AboutSettingsActivity.kt
- app/src/main/res/layout/activity_about_settings.xml
> Apply collapsing toolbar layout for about screen

- app/src/appcenter/google-services.json
- app/src/apptestnet/google-services.json
- app/src/debug/google-services.json
- app/src/main/AndroidManifest.xml
- app/src/main/google-services.json
- app/src/main/java/io/horizontalsystems/bankwallet/core/fcm/MyFirebaseMessagingService.kt
> Handle Notification token refresh and add google-services.json for each build type

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/LoadStatus.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideViewModel.kt
- app/src/main/res/layout/activity_guide.xml
- app/src/main/res/values/strings.xml
> Guide handle error

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt
- app/src/test/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorterTest.kt
> Add title as last field for sorting wallets by balance

- app/src/main/res/layout/activity_dashboard.xml
> Fix not fully closing bottom sheet for new version of material design

- components/views/src/main/res/layout/view_settings_switch.xml
> Fix showing of switch with value setting

- app/src/main/java/io/horizontalsystems/bankwallet/entities/Guide.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideBlockViewHolder.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideContentAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideViewModel.kt
> Open links to guides in app

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/amount/SendAmountPresenterHelper.kt
> Max btn fiat

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateTopListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/fee/SendFeeFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/SelectorDialog.kt
- app/src/main/res/layout/view_send_fee.xml
- build.gradle
- Update gradle to 4.0.1
ref #2430
> Make ui fixes in Send screen

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
> Update shortening values

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/res/layout/activity_rate_chart.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/GridHelper.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
- Make UI fixes in Chart
- Add 2 weeks option
ref #2429
> Make fixes in Chart 

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideVisitorBlock.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guideview/GuideVisitorString.kt
> Guides relative urls

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
> Fix ConnectivityManager to provide correct network state

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
> Update Ethereum and Bitcoin Kits and improve connection manager

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ConnectivityManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EthereumKitManager.kt
> Subscribe to connectivity changes on app resume, and unsubscribe on app pause

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/bitcoinhodling/BitcoinHodlingActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- components/views/src/main/java/io/horizontalsystems/views/SettingsViewSwitch.kt
> Fix hiding notification controls

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/sendbutton/ProceedButtonView.kt
> Prevent double clicks for send and confirm buttons

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
> Hide alert icon in Charts, when notifications are disabled

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt
- Share OkHttpClient
- Use shared OkHttpClient in GuidesManager.kt
ref #2459
> Share OkHttpClient

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/addErc20token/AddErc20TokenViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewModel.kt
> Update ethereum-kit, apply API changes

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsActivity.kt
- components/pin/build.gradle
- components/pin/src/main/java/io/horizontalsystems/pin/PinComponent.kt
- components/pin/src/main/java/io/horizontalsystems/pin/core/PinManager.kt
- components/views/src/main/java/io/horizontalsystems/views/SettingsViewSwitch.kt
- components/views/src/main/res/layout/view_settings_switch.xml
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Show alert icon in Settings when Pin is not set

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/submodules/confirmation/ConfirmationFragment.kt
- Disable Send button on first click
-  Remove unused error dialog in ConfirmationFragment.kt
ref #2461
> Fix multiple clicks in Send Confirmation

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
> Fix 0 value Eth transaction shown on Erc20 token send

- app/src/main/java/io/horizontalsystems/bankwallet/core/fcm/MyFirebaseMessagingService.kt
- app/src/main/res/values/strings.xml
> Parse and show Trend Alert Notification

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
> Fix "Assertion Error: No TLS" in GuidesManager.kt

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
> Simplify code in GuidesManager.kt

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
> Move Eth empty transaction filter to Ethereum kit

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
> Fix reopening Settings tab on language change

- components/views/src/main/res/drawable/button_steel_background.xml
> Update gradient color for steel button

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesRepository.kt
- components/keystore/src/main/java/io/horizontalsystems/keystore/BaseKeyStoreActivity.kt
- Fix No TLS exception on Guides page
- Kill app on pause when NoSystemPinWarning is shown
ref #2459
> Fixing error with ssl initialization

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Update the CoinMarketCap's API key

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/FeePresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/FeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveViewModel.kt
> Add Clearable interface that is used to release resources

- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/SubscriptionJobDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/utils/RequestCode.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/PriceAlert.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/SubscriptionJob.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartView.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationMenu.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/bottommenu/BottomNotificationsMenuViewModel.kt
> Use coinId instead of coinCode in Alert Notifications

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionRecord.kt
> Fix Erc20 tokens sorting in transaction list

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/CoinInfoMap.kt
> Add AKRO - Erc20 token

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PriceAlertManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/PriceAlertsDao.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysInteractor.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/ManageKeysPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/managekeys/views/ManageKeysActivity.kt
> Unsubscribe from notification alerts on Wallet delete

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/ConfirmationPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
> Handle errors in swap confirmation module

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
> Don't show low priority fee for Ethereum/Erc20 tokens

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/GuidesManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LanguageManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/entities/Guide.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesRepository.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesViewModel.kt
- core/src/main/java/io/horizontalsystems/core/Interfaces.kt
> Add localization support to Guides

- app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ethereum/SendEthereumHandler.kt
> Don't request gas limit with invalid amount in SendModule

- app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/repository/UniswapRepository.kt
> Add "0x" to hash for Ethereum and Erc20 transactions

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateCoinMapper.kt
> Disable TrustSwap coin exchange rate

- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
> Fix empty chart bug

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt
> Show the rate chart correctly when switching to another chart periods

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartActivity.kt
> Auto-scroll rate chart buttons when switching time period

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/FeeService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/provider/UniswapFeeProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/service/UniswapService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
- app/src/main/res/layout/activity_swap.xml
- app/src/main/res/values/strings.xml
> Fix swap error

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapActivity.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
- app/src/main/res/drawable/ic_swap.xml
- app/src/main/res/layout/activity_swap.xml
- app/src/main/res/layout/fragment_swap_approve.xml
- app/src/main/res/layout/view_holder_balance_item.xml
- app/src/main/res/values/strings.xml
> Swap UI changes

- app/build.gradle
> Upgrade TorKit dependencies (With exit logic fixes)

- app/build.gradle
- app/src/main/res/xml/network_security_config.xml
Ref #2611 
- Upgrade feerate-kit dependencies
- Remove unused network security configs.
> Upgrade fee-services API url

- app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
- app/src/main/res/values/strings.xml
> Change coin name

- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionDataProviderManager.kt
> Remove HorsysBitcoinProvider in full transaction info

- docker/build-apk.sh
Ref #2597 
- Add bash script to build and sign APK via Docker container
> Add bash script that builds APK via Docker container

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/ConfirmationPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/model/Trade.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/provider/AllowanceProvider.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/service/UniswapService.kt
>  Get swap fee from TradeData

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/ConfirmationPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/SwapConfirmationFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapItemFormatter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/view/SwapViewModel.kt
- create SwapItemFormatter for formatting various items for swap and confirmation screens
- show execution price as price of getting coin in terms of paying coin
ref #2599
> Refactor formatting swap items

- app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt
- app/src/main/res/layout/activity_swap_info.xml
- app/src/main/res/layout/view_holder_balance_item.xml
- app/src/main/res/values/strings.xml
- fix color of swap button's icon for disabled state
- change Uniswap info text
ref #2596, #2604
> Minor swap ui changes

- app/build.gradle
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratechart/RateChartViewFactory.kt
- app/src/main/res/layout/fragment_rate_chart.xml
- app/src/main/res/values/strings.xml
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartDataFactory.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/GridHelper.kt
- components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt
> Adding daily chart

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/res/layout/fragment_settings_privacy.xml
- app/src/main/res/values/strings.xml
> Update Tor settings text/labels

- components/languageswitcher/src/main/java/io/horizontalsystems/languageswitcher/LanguageSwitcherFragment.kt
> Swap name and native-name labels in Language-Manager

- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/createwallet/CreateWalletViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/view/ManageWalletsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsModule.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsService.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreselectcoins/RestoreSelectCoinsViewModel.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/coinlist/CoinListBaseFragment.kt
- app/src/main/res/layout/manage_wallets_fragment.xml
- app/src/main/res/layout/view_holder_coin_manage_item.xml
- components/views/src/main/java/io/horizontalsystems/views/MultipleInputEditTextView.kt
> Restore module revision

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
> Disable bottom tabs swipe

- app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinFragment.kt
> Hide keyboard on closing SwapCoinSelect

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Correctly handle Tor state when internet connection updated

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/ViewHolderGuide.kt
- app/src/main/res/layout/fragment_backup_words_list.xml
- app/src/main/res/layout/view_holder_guide_preview.xml
- components/views/src/main/java/io/horizontalsystems/views/BackupWordView.kt
- components/views/src/main/res/layout/view_backup_word_text.xml
-  Backup word list: fix invalid margins between number and text
- Remove image placeholders in Guide list
ref #2639
> Make minor UI improvements

- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
This reverts commit 17388f49
ref #2572
> Revert "Disable bottom tabs swipe"

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/words/RestoreWordsFragment.kt
- core/src/main/java/io/horizontalsystems/core/helpers/KeyboardHelper.kt
> Automatically show keyboard when fragment displayed

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EosAdapter.kt
> Make EOS account name validation via regex

- app/build.gradle
- app/src/main/res/layout/view_holder_balance_item.xml
- build.gradle
- Fix swap button  hidden in first cell
- Fix balance elements paddings
- Update libraries
ref #2627, #2645
> Make UI fixes to Balance item cell

- app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EthereumAdapter.kt
- take from/to addresses from internal transaction if such exists
ref #2671
> Show correct from/to address in ethereum transaction

- app/build.gradle
> Show derivation in App Status

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
Gradually release memory on low memory system calls.
ref #2632
> Handle low memory system calls

- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/notifications/NotificationsViewModel.kt
- app/src/main/res/layout/fragment_notifications.xml
- app/src/main/res/layout/view_holder_balance_item.xml
- app/src/main/res/layout/view_holder_notification_coin_name.xml
- components/views/src/main/java/io/horizontalsystems/views/SettingsView.kt
> Show Deactivate All button disabled, when alerts are not selected

- app/src/main/res/values/strings.xml
> Correct text

- app/src/main/java/io/horizontalsystems/bankwallet/modules/guides/GuidesFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/NestedScrollableHost.kt
- app/src/main/res/layout/fragment_guides.xml
- app/src/main/res/layout/fragment_transactions.xml
> Fix filter tags scrolling

- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/CoinRatesHeaderAdapter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateListPresenter.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/RateTopListFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/ratelist/SourceAdapter.kt
- app/src/main/res/layout/view_holder_spinner.xml
> Load top coin rate list only when user navigates to this page

- app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt
- app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RateManager.kt
> Subscribe to tokens fee coin rates in RateManager

- app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/privacy/PrivacySettingsPresenter.kt
> Disable Incubed sync option for Ethereum

- app/src/main/java/io/horizontalsystems/bankwallet/modules/backup/words/BackupWordsConfirmFragment.kt
- app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/eos/RestoreEosFragment.kt
- app/src/main/res/layout/fragment_restore_eos.xml
- app/src/main/res/layout/fragment_restore_words.xml
- components/snackbar/src/main/res/layout/view_custom_snackbar.xml
- core/src/main/java/io/horizontalsystems/core/helpers/KeyboardHelper.kt
Ref #2584 
- Correct snackbar text styling
- Show snackbar on top of Keyboard
> Snackbar fixes
