horizontalsystems/unstoppable-wallet-android

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt
=> Fix filtering by blockchain

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt, app/src/main/res/navigation/main_graph.xml
=> Update Blockchain selector UI in MarketFilters module

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt
=> Show price change with different colors in Market Filters

app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionAdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Wallet.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/FilterCoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/res/drawable/icon_20_check_1.xml, app/src/main/res/drawable/icon_24_circle_coin.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Txs filtering by blockchain and coin

app/src/main/java/io/horizontalsystems/bankwallet/widgets/AppWidgetTheme.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetWorker.kt
=> Handle widget error cases

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsService.kt, app/src/main/res/values/strings.xml
=> Add NFT asset activity tab

app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/NftManager.kt
=> Fix nft assets and collections caching

app/src/main/AndroidManifest.xml, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetWorker.kt, app/src/main/res/navigation/main_graph.xml
=> Handle clicking on widgets

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Header.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
=> Swap coin name with code in cells

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, components/icons/src/main/res/drawable/currency_zar.xml
=> Add ZAR to base currencies

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
=> Make small ui fixes to Top NFT and NFT collection

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicService.kt, app/src/main/res/values/strings.xml
=> Add support for 15, 18, 21 mnemonic phrases and different languages

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/EnableCoinService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinTokensService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinTokensViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinsettings/CoinSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinsettings/CoinSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultipleDialog.kt, app/src/main/res/values/strings.xml
=> Make changes in CoinManager bottom sheet

app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftAssetItemsPricedWithCurrencyRepository.kt
- pass distinct coinUids list to xRateRepository
#5142
=> Fix bug in NftAssetItemsPricedWithCurrencyRepository

app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsFragment.kt
=> Add type filter to NFTAsset Activities list

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionAdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/TokenBalanceProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt
=> Add Avalanche-C chain

app/src/main/java/io/horizontalsystems/bankwallet/modules/info/TransactionDoubleSpendInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/TimeLockFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
=> Fix UI bugs

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/AppBar.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SearchBar.kt
=> Fix AppBar icons color

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinTokensViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt
=> Coinmanager small fixes

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsViewModel.kt, app/src/main/res/values/strings.xml
=> Minor improvements to NFT Asset activities tab

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
=> Add ability to reset filters in Transactions

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt
=> Use market capRank from MarketInfo instead of Coin

app/build.gradle
=> Update market-kit (order by relevance)

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyFragment.kt, build.gradle
=> Seed phrase bip39

app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_45_46.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
=> Get rid of logging `onTrimMemory`

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
=> Update BTC fee rates

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/TokenBalanceProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/CoinCategoryMarketDataChartService.kt
- Pass currency on fetching chart data for market category
- Rename parameter 'chain' to 'blockchain' in requests
#5183
=> Market kit small fixes

app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmLabelManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/TransactionDoubleSpendInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/ui/RequestCells.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/test/java/io/horizontalsystems/bankwallet/core/ExtensionsKtTest.kt
=> Shorten address and hex

app/src/main/res/values/strings.xml
=> Change WatchAddressModule title

app/src/main/res/values/strings.xml
=> Change Restore screen title

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt
=> Update blockchains ordering in restore and security setting

app/build.gradle
=> Update bitcoin kit (fix transaction init)

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BalanceHiddenManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/assets/NftCollectionAssetsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftAssetItemsPricedWithCurrencyRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collections/NftCollectionsViewModel.kt, app/src/main/res/values/strings.xml
- display ETH/BTC/BNB value next to total balance for NFTs
- add option to hide collections from balance
#4591
=> Improvements to NFTs screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt
=> Change icon size in Platform page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmCommonGasDataService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmRollupGasDataService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559FeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559GasPriceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/legacy/LegacyFeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/legacy/LegacyGasPriceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt
=> Optimism and Arbitrum

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WatchAddressBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt
=> Enable disabled blockchains in watch account

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoreblockchains/RestoreBlockchainsService.kt
=> Fix ordering in Restore blockchain List

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt
=> Fix showing alert for any non backed up wallet in Settings

app/src/appcenterdebug/res/mipmap-anydpi-v26/launcher_main.xml, app/src/debug/res/mipmap-anydpi-v26/launcher_main.xml, app/src/main/AndroidManifest.xml, app/src/main/res/drawable/launcher_1009_foreground.xml, app/src/main/res/drawable/launcher_debug_foreground.xml, app/src/main/res/drawable/launcher_main_appcenter_debug_foreground.xml, app/src/main/res/drawable/launcher_main_appcenter_release_foreground.xml, components/views/src/main/res/values-v31/themes.xml
=> Fix splash screen

app/build.gradle
=> Update market-kit, increment versionCode

RELEASE.md, docker/test.sh
- add step for testing 'reproducibility' to RELEASE.md
#5209
=> Add script for testing apk 'reproducibility'

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceXRateRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
=> Update market-kit, make `CoinPrice.diff` optional

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/unlinkaccount/UnlinkAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WalletConnectModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionList.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v1/WalletConnectListService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v1/WalletConnectListViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v2/WC2ListViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/ui/WCSessionCells.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version1/WC1Service.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt, app/src/main/res/values/strings.xml
- Add possibility to select chain in WalletConnect #5211 
- Show all chain sessions in WalletConnect list #5261 
- Delete redundant warning item in Wallet Unlink #5262
=> Enhancements & fixes

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddBep2TokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt
=> Fix fetching token info when adding custom token

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmAccountManager.kt
=> Catch exception in `EvmAccountManager.initialSync()`

app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicHelper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Keyboard.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Containers.kt
=> Word suggestions

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/FeePriceScale.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559FeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/legacy/LegacyFeeSettingsViewModel.kt
- Add nAvax to Evm fee settings
- Show small value for tips
#5272
=> Fix fee calculation for Evm blockchains

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/TokenBalanceProvider.kt
=> Fix bug in wallet restore, update url

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/res/values/strings.xml
=> Show zCash sync progress in terms of processed blocks

app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/res/values/strings.xml
=> Implement wordlist select by language in account create

app/src/main/java/io/horizontalsystems/bankwallet/core/NavController.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/PasscodeBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/showkey/ShowKeyFragment.kt, app/src/main/res/values/strings.xml
=> Recovery phrase UI

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusService.kt
=> Implement MarketKit sync info status

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt
=> Update auto-enabled blockchains by default

app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/recoveryphrase/RecoveryPhraseFragment.kt
=> Disallow screenshot

app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restore/restoremnemonic/RestoreMnemonicViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/res/values/strings.xml
=> Remove name field from Restore and Watch Address pages

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt, app/src/main/res/values/strings.xml
=> Disable wallet connect v2

app/src/main/java/io/horizontalsystems/bankwallet/entities/Wallet.kt
=> Uppercase balance cell labels

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v1/WalletConnectListViewModel.kt
=> Open the QR code scanner if there are no connections

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Keyboard.kt
=> Fix memory leak

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceSorter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt
=> Маке small fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
=> Fix long name display in balance card

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceNoAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
=> Align ScreenMessageWithAction center vertically

app/src/main/java/io/horizontalsystems/bankwallet/core/utils/T.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt, app/src/main/res/values/strings.xml
=> Tvl no coin

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt
=> Do not show edit button for coins like Dash, ZCash

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/NavController.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TermsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceNoAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/terms/TermsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/terms/TermsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/terms/TermsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HsCheckbox.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Show Terms when user clicks on Create/Restore button

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt
=> Bottom action button

app/src/main/java/io/horizontalsystems/bankwallet/modules/evmprivatekey/EvmPrivateKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/recoveryphrase/RecoveryPhraseFragment.kt, app/src/main/res/values/strings.xml
=> Update design for confirm copy alert bottom sheet

app/build.gradle
=> Update eth-kit (fix signing typed data)

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt
=> Update condition for ExternalContractCallTransactionRecord

app/src/main/res/values-fa/strings.xml
=> Fix translation

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
=> Fix swap amount input to allow dots

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveRouterViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapRevokeAndApproveScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapRevokeAndApproveViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt, app/src/main/res/values/strings.xml
=> Usdt revoke and allow

app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/assets/NftCollectionAssetsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsScreen.kt
=> Apply fixes in NFT image display

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/nft/EvmNftAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/nft/INftAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NftAdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt, app/src/main/res/values/strings.xml
=> Show Send button in NftAssetFragment when user possess it

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NftMetadataManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/INftProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaNftProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaService.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/NftDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/NftStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_48_49.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionValue.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftAssetBriefMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftAssetBriefMetadataRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftCollectionMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/NftMetadataService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt, app/src/main/res/drawable/icon_24_nft_placeholder.xml
=> Add NFT decorations to `transactions` module

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/assets/NftCollectionAssetsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/drawable/icon_24_flame.xml, app/src/main/res/values/strings.xml
=> Add NFT decorations to `transaction-info` module

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaNftProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewViewModel.kt, app/src/main/res/values/strings.xml
- Implement new design of cards
- Add new info about Royalty and Inception date
#5139
=> NFT collection page improvements

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/EnsResolverHolder.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt
=> Ens resolving fix

app/build.gradle
=> Fix dash sync

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt
=> Fix disappearing main screen content on pin set

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
=> Fix handling of spam transactions

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/nft/EvmNftAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/nft/INftAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NftMetadataManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/NftDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/NftStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip1155Screen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip1155ViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip721Screen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip721ViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/EvmKitWrapperHoldingViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement Send NFT

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NftMetadataManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsViewModel.kt
- cancel coroutine scope in NftHoldingsService
- change StateFlow to SharedFlow
=> Use Retrofit client without cache in OpenSeaService

app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveViewModel.kt
=> Fix crash `NoReceiverAdapter` in Receive module

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt
=> Handle UnsupportedOperationException in CoinFragment

app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ui/CoinScreenTitle.kt
=> Replace icon urls

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/showextendedkey/account/ShowExtendedKeyModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/showextendedkey/account/ShowExtendedKeyViewModel.kt
=> Fix restore/watch Litecoin by extended private/public key

app/src/main/java/io/horizontalsystems/bankwallet/modules/theme/ThemeService.kt
=> Remove redundant

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsRepository.kt, build.gradle
=> Implement changes in TopPlatform entity

app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
=> Fix camera indicator hiding after QRScanner close

app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
=> Fix QrScanner scan after permission allowed

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SplAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SolanaKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SolanaWalletManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WatchAddressBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAccountsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/horizontalsystems/bankwallet/core/utils/EvmAddressParserTest.kt
=> Solana Improvements

app/build.gradle
=> Update BitcoinKit to apply nullable block-height fix

app/src/main/java/io/horizontalsystems/bankwallet/modules/evmprivatekey/EvmPrivateKeyViewModel.kt
=> Fix display of Evm Private Key

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v2/WC2ListViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/requestlist/WC2RequestListService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2PingService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2SessionManager.kt
=> Integrate stable version 2 of Wallet Connect

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/ui/WCSessionCells.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionViewModel.kt
=> Wallet connect v2 additions

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/res/drawable/badge_circle_shape.xml, app/src/main/res/layout/view_bottom_navigation_badge_with_number.xml
=> Show counter badge for WalletConnect pending requests

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SplAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SolanaKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftUid.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
=> Minor improvements to Solana

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/v1/WalletConnectListViewModel.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/navigation/wallet_connect_graph.xml
=> Refactor and fix WalletConnect deeplinks handling

app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
=> Fix SendEvmConfirmation screen crash

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
- Implement new component `Universal`
#5510
=> Increase coin icon size to 32

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
=> Apply balance card small UI changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewMisc.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
=> Increase market item icons to 32px

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseTokenManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalBalance.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/DoubleText.kt
=> Update total balance view logic

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WC2RequestFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WC2RequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCSendEthereumTransactionRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/v1/WCSendEthereumTransactionRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/v2/WC2SendEthereumTransactionRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2SignMessageRequestScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2SignMessageRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2UnsupportedRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Request.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2SessionManager.kt, app/src/main/res/values/strings.xml
=> Wc2 handling requests

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PassphraseValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WordsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt, app/src/main/res/values/strings.xml
=> English only mnemonic

app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt
=> Apply swap confirmation changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Contracts.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/treasuries/CoinTreasuriesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ui/CoinScreenTitle.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionList.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/pairing/WC2PairingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/ui/SignScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/ui/RequestCells.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/ui/WCSessionCells.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v1/WCSessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/RequestCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSwapProviderSelectDialog.kt
=> Increase icon size to 32

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Links.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopNft.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip1155Screen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendEip721Screen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/BlockchainSettingsBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/PasscodeBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TorBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/pairing/WC2PairingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Cell.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ComposeUtils.kt
=> Make changes to small icon size and icon rounded corner radius

app/build.gradle, app/src/main/res/values/strings.xml
=> Add separate url for migration faq, add descriptions

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAccountsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
=> Fix bugs on balance page 

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAccountsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinplatforms/CoinTokensViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreblockchains/RestoreBlockchainsModule.kt
=> Fix BinanceKitManager crash when user activates not supported token

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LanguageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TestnetSettingsBlock.kt, core/src/main/java/io/horizontalsystems/core/Interfaces.kt
=> Disable Pro feature on Coin page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchKitHelper.kt
=> Update 1inch API to V5.0

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ModifierSectionItemBorder.kt
=> Wrap transaction sections with border

.github/workflows/ci-release.yml, .github/workflows/ci-version-branch.yml
It is required by maierj/fastlane-action v.3
=> Set the bundler-cache parameter to true

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService.kt
=> Determine test net badge in balance cell when adapters ready

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/pairing/WC2PairingsFragment.kt
=> Fix UI in `WC Paired dApps` page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt
=> Remove BSC websocket

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
=> Allow speed-up and cancel for EvmTransactionRecord

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt
=> Support only eip155 chains for ethereum kit chains

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewMetrics.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt
=> Fix click area

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinEditView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinSetView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinUnlockView.kt
=> Align text center in pin module

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/res/values/strings.xml
=> Separate Already added tokens in Add Token page

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt, app/src/main/res/values/strings.xml
=> Add `recommended` for 12 words option in CreateAccount

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
=> Disallow speedUp/cancel for incoming transactions

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/res/values/strings.xml
=> Request token from API when its token type is Unsupported

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
=> Clear focus when selecting swap amount percentage

app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinServiceFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddBep2TokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt
=> Enable showing custom test tokens in Send Confirmation

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/res/values/strings.xml
=> Implement new design in AddToken page

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt
=> Show Goerli prefix for Erc20 testnet tokens in AddToken

app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAccountsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Fix `Manage Wallets` icon show on Balance page

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt, app/src/main/res/values/strings.xml
=> Swap changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchSwapViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/ui/SwapPageViews.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Badge.kt, app/src/main/res/values/strings.xml
=> Swap minor changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/ui/SwapPageViews.kt
- move towards start (left) 10% if action button has a step label or circular progress
- otherwise just center
#5651
=> Change swap action button's title position

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coincard/SwapCoinCardViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/uniswap/UniswapFragment.kt
=> Hide swap amount percent suggestions when zero balance

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/CoinNotSupportedDialog.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreblockchains/RestoreBlockchainsModule.kt, app/src/main/res/values/strings.xml
=> Show different alerts for types of Unsupported tokens

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
=> Improve unsupported token alert logic

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt
=> Fix NullPointerException crash in WC2Service.kt

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/pairing/WCPairingsViewModel.kt
=> Zcash sdk update

README.md, RELEASE.md
=> Add section 'Supported Android Versions' in Readme

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/basecurrency/BaseCurrencySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ModifierSectionItemBorder.kt
=> Make fixes to transactions 

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt
=> Handle empty state of market metric charts

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt
=> Validate Solana address in Watch page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
=> Showing TX updates

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt
=> Update wallet connect v2 sdk

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetConfigurationActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetReceiver.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetState.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetWorker.kt, app/src/main/res/values/strings.xml
=> Makes fixes in Widget 

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt, app/src/main/res/values/strings.xml
=> Toggle markets tab

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/res/values/themes.xml
=> Fix displaying of settings badge when market tabs toggled

app/src/main/res/values/strings.xml
=> Change backup text

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetConfigurationActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetManager.kt
=> Handle markets tab disabled

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceNoAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroActivity.kt
- Change the text on the "Be Unstoppable" button to "Next"
- Clicking on button shows the next welcome screen
#5750
=> Welcome screen changes

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseTokenManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalBalance.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/holdings/NftHoldingsModule.kt
- Always show the fiat value on the title
- Show the value of the coin on the subtitle, and add a click toggle between BTC, ETH, and BNB coin values
#5765
=> Change total balance header behavior

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewPagerAdapter.kt
=> Return empty fragment when markets tab disabled

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/res/values/strings.xml
=> Use Blockchain selector in Add Token page

app/src/main/java/io/horizontalsystems/bankwallet/modules/info/BtcBlockchainTransactionInputsOutputsInfoFragment.kt
=> Fix Blockchain Settings information page

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinsettings/CoinSettingsViewModel.kt, app/src/main/res/values/strings.xml
=> Set default Bip to 84

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/BackupRequiredDialog.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCErrorNoAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version1/WC1Manager.kt, app/src/main/res/values/strings.xml
=>  Does not allow WalletConnect connection for not backed up account

app/src/main/res/values/strings.xml
=> Change Texts

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
- remove circular background
- show hidden state on the button, i.e. for hidden/unhidden states show corresponding icons
#5773
=> Modify FormsInputPassword hide/unhide button

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt
=> Add analytics data to the coin page

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
=> Default visibility

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NetworkManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/EvmSyncSource.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddBep2TokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddEvmTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt
=> Fetch token info from nodes

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt
=> Change rpc source for bsc and arbitrum

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsViewModel.kt
=> Remove testnet blockchains from watch

app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/btcblockchainsettings/BtcBlockchainSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/btcblockchainsettings/BtcBlockchainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/solananetwork/SolanaNetworkFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/solananetwork/SolanaNetworkViewModel.kt
=> Make blockchain network settings pages similar in design

app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/res/values/strings.xml
=> Add error highlight for watch xPubKey input

app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
=> Add 'Name' input to Watch screen

app/build.gradle
=> Update solana-kit, fix transaction parsing

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt
=> Disable coin info button for custom coins

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/blockchainselector/AddTokenBlockchainSelector.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/syncerror/SyncErrorDialog.kt
=> Fix Blockchain Selector in AddTokenFragment

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartPointsWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/details/CoinDetailsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt, app/src/main/res/values/strings.xml, components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartView.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/GridHelper.kt
=> Add charts interval 2y and All

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
=> Fix crash during Send fragment restore

app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartDataWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt
=> Handle case when first point value of charts is 0

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
=> Fix binding is null crash in MainFragment

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
=> Add Gnosis blockchain to AddToken page

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletActivator.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsViewModel.kt
- apply correct order in SelectBlockchains
- show separate BitcoinCash items for each type (type0, type145)
- don't show bip label for Dash
#5796
=> Watch Address module changes

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt
=> Do not send request prices if the coins list is empty

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/NftEventsProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaNftProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaService.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftCollectionMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftContractMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftEventMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Contracts.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/events/NftCollectionEventsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/overview/NftCollectionOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt, app/src/main/res/values/strings.xml
- add contract selector to Collection Events
#5658
=> Change NftEvents provider API to `reservoir.tools`

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
=> Set max line to 1 for mini chart header

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt
=> Add vibration when pin keys are pressed

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt
=> Fix text fitting in Market page

app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultipleDialog.kt
=> Set token icon size to 32 in bottom selector

app/src/main/java/io/horizontalsystems/bankwallet/modules/releasenotes/ReleaseNotesFragment.kt
=> Fix `WhatsNew` page layout

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressValidationException.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressInput.kt
=> Fix showing error of address

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/FaqManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmprivatekey/EvmPrivateKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/recoveryphrase/RecoveryPhraseFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/showextendedkey/account/ShowExtendedKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt
- Add info buttons to Key related pages
- Add info page to Wallet Connect
- Fix MarkdownFragment layout to fix content over Appbar
#5862
=> Add info buttons to open FAQ pages

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/amount/AmountValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinAmountService.kt
=> Remove amount send limit in 0.5 BTC

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt
=> Make naming changes in ConManager and contracts in Coin Page

app/build.gradle
=> Fix Arbitrum transactions fetch

app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/addrpc/AddRpcViewModel.kt, app/src/main/res/values/strings.xml
=> Disable non-secure urls for custom RPC sources

app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysFragment.kt
=> Fix authorized pages in ManageAccount

app/build.gradle
=> Update WalletKit to remove unsafe calls

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmSettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt
=> Don't show nonce settings when fixed nonce passed

app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt
=> Copy receive address by clicking QR-code

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LanguageManager.kt, core/src/main/java/io/horizontalsystems/core/helpers/LocaleHelper.kt
=> Fix fallback locale

app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559FeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/legacy/LegacyFeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmSettingsFragment.kt
=> Add warning/error highlights to inputs in Send Evm Settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/ui/SignScreen.kt
=> Handle invalid message type during WC sign

app/src/main/java/io/horizontalsystems/bankwallet/core/BaseFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/evmaddress/EvmAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/evmprivatekey/EvmPrivateKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/recoveryphrase/RecoveryPhraseFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinFragment.kt
=> Hide app screen in task manager

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
=> Handle IOException during chart network fetch

components/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve2.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/CurveAnimator.kt
=> Fix chart line width

app/build.gradle
=> Fix crash caused by OutOfMemory error during Dash sync

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt
=> Close wallet switch dialog on BackPress in MainFragment

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ChartBars.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MiniChartCard.kt
=> Implement bars type of charts

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
=> Specify alias for zcash sdk to distinguish accounts

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/CoinAnalyticsInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/ui/InfoBlocks.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Text.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add help info to Coin Analytics page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItemsEmpty.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/CoinAnalyticsInfoFragment.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement Coin Analytics Ranks module

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalBalance.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
=> Use short fiat formatting in Balance and Transactions

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/Mode.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/AddressScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/values/strings.xml
=> Implement saving address to Address Book from transaction info and send confirmation screens

app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartDataWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartUiState.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt
=> Chart additions

app/build.gradle
=> Fix SolanaKit sync after app resume

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ChooseContactFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ChooseContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/model/Contact.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactsViewModel.kt, app/src/main/res/values/strings.xml
=> Contacts module additions and improvements

components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartBars.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartMinimal.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/CurveAnimator.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/PointConverter.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt, components/chartview/src/main/res/layout/view_chart.xml
=> Fix edge bars drawing

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmLabelManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/TransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
=> Show contact name in transactions list

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt
=> Show volume data for Transactions count chart

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartFragment.kt
=> Coin analytics small fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/model/Contact.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactsViewModel.kt, app/src/main/res/values/strings.xml
- when restoring delete current state and restore backed-up contacts
- show warning message before restoring
- delete unused fields in backup file (modified_at, addresses[])
#5731
=> Refactor backup/restore contacts logic

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartPointsWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/CoinCategoryMarketDataChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/PlatformChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/CoinTvlChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/Chart.kt, components/chartview/src/main/res/layout/view_chart.xml
=> Charts additions

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SolanaKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
=> Add Solscan api key to fix transactions fetch

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartModule.kt, app/src/main/res/values/strings.xml
=> Add a header component with a description to the chart pages

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaAdapter.kt
=> Fix sending maximum Solana amount

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartModule.kt, app/src/main/res/values/strings.xml
=> Rank page changes

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartPointsWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartConfig.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartPoint.kt
=> Chart optimize

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/AddressScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/BlockchainSelectorScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt
=> Contacts: Minor UI enhancements

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaAdapter.kt
=> Leave Solana account rent amount when sending all balance

app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartModule.kt
=> Show overridden value in chart for Active Addresses

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt
=> Enable Cex Volume chart in Coin Analytics page

app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt
=> Start chart from 1 Month period for Dex Liquidity

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankViewModel.kt
=> Fix sorting in coin rank screens

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/blockchainselector/AddTokenBlockchainSelector.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/BlockchainSelectorScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt
=> Bug fixes: crash in SendFragment, UI bugs

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmAccountManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/nft/OpenSeaService.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftAssetMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/nft/NftContractMetadata.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetViewModel.kt
- add missing `OneInchUnknownSwapDecoration` handling
- fix api sync issues for `OpenSea` provider
=> Fix auto-enable tokens on restore/watch

app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt
=> Fix xPubKey validation in Watch Address module

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/majorholders/CoinMajorHoldersFragment.kt, app/src/main/res/values/strings.xml
=> Make small UI changes in CoinMajorHoldersFragment

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ChartBars.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartBars.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartCurve2.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/CurveAnimator.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/helpers/PointConverter.kt
=> Single point charts

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/CoinAnalyticsInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt, app/src/main/res/values/strings.xml
=> Implement analytics changes

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt
=> Coin analytic fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountAdvancedFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/RestoreAccountAdvancedFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyViewModel.kt
=> Pass name to Advanced screen in Create/Restore Account

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountAdvancedFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/RestoreAccountAdvancedFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestoreMnemonicViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyViewModel.kt
This reverts commit d6699b574f5c3c80a8d0ed8e35e53c1eb1bba793.
=> Revert "Pass name to Advanced screen in Create/Restore Account"

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/ECashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/FeeRateProviderFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountCleaner.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreblockchains/RestoreBlockchainsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt
=> Add support for eCash (XEC)

app/build.gradle, build.gradle
=> Fix crash on swap amount change by downgrading some libs

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt
- Update UnstoppableDomains SDK
#5926
=> Omit using Udn `isSupported` method in name resolve

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/enablecoin/coinsettings/CoinSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/publickeys/PublicKeysFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/publickeys/PublicKeysViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Taproot support

app/build.gradle, build.gradle, components/chartview/build.gradle, components/icons/build.gradle, core/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Upgrade gradle to 8.0

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/res/drawable/icon_32_flag_argentine.xml, app/src/main/res/drawable/icon_32_flag_norway.xml, app/src/main/res/drawable/icon_32_flag_philippine.xml
=> Add new base currencies: ARS, NOK, PHP

app/src/main/java/io/horizontalsystems/bankwallet/modules/releasenotes/ReleaseNotesFragment.kt
=> Add icon button names for accessibility

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/res/drawable/icon_32_flag_hungary.xml
=> Add Hungarian currency

app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/EvmCoinService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmCommonGasDataService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeCellViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmRollupGasDataService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/eip1559/Eip1559FeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/legacy/LegacyFeeSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionInfoOptionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/res/values/strings.xml
=> Fee surcharge update

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPasswordViewModel.kt
- Add timestamp field to Local Backup file
- Fix closing screen after adding custom token
#6139, #6142
=> Implement small fixes

app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/CautionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt, app/src/main/res/values/strings.xml
=> Make changes in showing Price Impact in Swap module

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsService.kt
=> Set to loading state before fetching coin analytics

app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/PassphraseValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPassword.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPasswordViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceNoAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importwallet/ImportWalletFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccounts/ManageAccountsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/RestoreAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsFragment.kt, app/src/main/res/values/strings.xml
- Remove Watch Account from Import page	 
- Fix navigation during Account restore/watch/create   
- Show Backup Json parse error with delay  
- Add new requirements to backup password validation
#6101
=> Make fixes in Create/Restore Account navigation

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewItemHelper.kt
=> Show price impact for less than 5% values

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapViewItemHelper.kt
=> Don't show small price impact values

app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/CautionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/uniswap/UniswapConfirmationModule.kt, app/src/main/res/values/strings.xml
=> Don't show alert for `Normal` price impact

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/zcashconfigure/ZcashConfigure.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/DoubleText.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SearchBar.kt
=> Show total balance centered

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EncryptDecryptManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPassword.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPasswordViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/terms/BackupLocalTerms.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalViewModel.kt, app/src/main/res/values/strings.xml
=> Implement fixes to Local backup modules

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt
=> Change blockchain orders

app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt
=> Don't show manual backup for EvmPrivateKey account type

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Trc20Adapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTronTokenBlockchainService.kt
=> Add AddToken service for Trc20 tokens

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
=> Fix bug in Zcash availableBalance calculation

app/src/main/java/io/horizontalsystems/bankwallet/modules/backupalert/BackupRecoveryPhraseDialog.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Forms.kt
=> Implement fixes to `local backup` module

app/src/main/java/io/horizontalsystems/bankwallet/core/ethereum/CautionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/res/values/strings.xml
=> Show execution reverted error message as is

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTronTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt
=> Show sanitized Eip712 message in WalletConnect sign requests

app/build.gradle
=> Update bitcoin-kit (litecoin checkpoints fix)

app/build.gradle
=> Update ethereum-kit (fix fetching transactions)

app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositCexFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositQrCodeScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectCoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectNetworkScreen.kt
=> Implement screen for. Deposit QrCode

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockoutManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockoutState.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinTopBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockViewModel.kt, app/src/main/res/values/strings.xml
=> Show attempts left on failed pin input

app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountEnterCexDataScreen.kt
=> Fix ImportCexAccount page for small screens

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SubscriptionManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt
=> Fix analytics subpages

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/AuthenticationCodeInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/EmailVerificationCodeInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexConfirmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexSecurityVerificationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexSelectNetworkScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement screens for Cex Withdraw

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt, app/src/main/res/values/strings.xml
=> Show BottomSheet warning on WC invalid URL

app/src/main/java/io/horizontalsystems/bankwallet/modules/importwallet/ImportWalletFragment.kt
=> Add field validation for Backup Restore json file

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt
=> Add BSC support for Uniswap V3

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalViewModel.kt
=> Implement Cex local backup/restore

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainModule.kt
=> Add Ethereum support for PancakeSwap V3

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CexAssetManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/ICexProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/CexAssetsDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_52_53.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexRepositoryWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectCexAssetViewModel.kt
=> Implement database storing for CexAssetRaw

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/TotalBalance.kt
- coming from background not hiding balance items
#6247
=> Fix bug in Balance Auto Hide

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexViewModel.kt
=> Fix bug in Balance Auto Hide for BalanceCexViewModel

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AccountFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/EnterCexDataBinanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/EnterCexDataCoinzixViewModel.kt
=> Implement default Cex account name

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Make header scrollable in Balance Tab

app/build.gradle
=> Set hcaptcha settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
=> Disable Transactions tab for Cex Account Type

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt
=> Disable Twitter tab in Coin page

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseTronAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Trc20Adapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronAdapter.kt
=> Make calls to tron-kit in IO thread

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/ICexProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/EnterCexDataBinanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountEnterCexDataScreen.kt, app/src/main/res/values/strings.xml
=> Make small fixes in CEX account restore

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositCexChooseAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectCoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexChooseAssetFragment.kt, app/src/main/res/navigation/main_graph.xml
=> Implement selecting coin for withdraw

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt
=> Show all chains in Coin page

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt
=> Show block explorer URL for all chains in Coin page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WCRequestChain.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCRequestModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/ui/SendEthScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/v1/WCSendEthereumTransactionRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/v2/WC2SendEthereumTransactionRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/WCSignMessageRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/ui/SignScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v1/WC1SignMessageRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signmessage/v2/WC2SignMessageRequestService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/v2/WC2SessionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Manager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Parser.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2Service.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/version2/WC2SessionManager.kt
- remove Chain & Address info from WC session screen
- add dAppName, Chain & Address info to WC request screens (sign, confirm tx)
- create evmKit when request is received
#6273
=> Add possibility to switch chains for WalletConnect V2

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CexAssetManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/ICexProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/DatabaseConverters.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/CoinzixCexApiService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositCexFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectNetworkScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/CexWithdrawVerificationViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexSecurityVerificationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexSelectNetworkScreen.kt
=> Coinzix withdraw & network changes

app/build.gradle
=> Update dashkit protocol version

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronViewModel.kt
=> Add logs to SendTronViewModel

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt
=> Fix restore from local file

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SubscriptionManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/support/PersonalSupportFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/support/PersonalSupportModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/support/PersonalSupportViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/support/PremiumFeatureWarningDialog.kt, app/src/main/res/drawable/ic_support_24.xml, app/src/main/res/drawable/ic_support_jacob_24.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement Personal Support

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/RecipientAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/oneinch/OneInchSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/ui/SwapSettingsComponents.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/settings/uniswap/UniswapSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/FormsInputAddress.kt
=> Fix Contact selection in HSAddressInput

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/subscription/ActivateSubscriptionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/subscription/ActivateSubscriptionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/subscription/SubscriptionInfoFragment.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Show SubscriptionInfo page in Coin Analytics page

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
=> Fix loading circular progress position

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressInput.kt
=> Fix watch address parsing job

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt
=> Make cex deposit always enabled

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HsSwitch.kt
See https://stackoverflow.com/a/75408239/2098878 for details
=> Remove switch component paddings

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/ICexProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/CoinzixCexApiService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coinzixverify/ui/CoinzixVerificationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/EnterCexDataCoinzixViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountEnterCexDataScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountEnterCexDataViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/ErrorDisplayDialogFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexConfirmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/TranslatableString.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Cex UI changes and bug fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPassword.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/terms/BackupLocalTerms.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/indicators/EmaSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/indicators/MacdSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/indicators/RsiSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/backupkey/BackupKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ui/SharedComponents.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/rooteddevice/RootedDeviceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/support/PersonalSupportFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/SwapApproveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/approve/confirmation/SwapApproveConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/BaseSwapConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/options/TransactionSpeedUpCancelFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/ui/WithdrawCexConfirmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/zcashconfigure/ZcashConfigure.kt
=> UI fixes changes

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SubscriptionManager.kt
=> Version backmerge

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/CoinzixCexApiService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositCexChooseAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/SelectCoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/withdrawcex/WithdrawCexChooseAssetFragment.kt
=> Close choose withdraw asset page after selected

app/src/main/java/io/horizontalsystems/bankwallet/core/Exceptions.kt
=> Fix gas limit estimation for fee less than base fee

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartIndicatorManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/technicalindicators/CoinIndicatorViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/technicalindicators/TechnicalIndicatorService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/technicalindicators/TechnicalIndicatorsDetailsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/technicalindicators/TechnicalIndicatorsDetailsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/technicalindicators/TechnicalIndicatorsDetailsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/info/CoinAnalyticsInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TechnicalIndicatorsChart.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Technical Indicators to Coin Analytics

app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountAdvanced.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/experimental/ExperimentalFeaturesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt
=> Rename Tor button to Enable/Disable

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/intro/IntroActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapCoinCardView.kt, build.gradle
=> Coin subpages lazyload

app/build.gradle
=> Update ethereum-kit (1inch swap fix)

app/build.gradle
=> Update SolanaKit to fix auto enabled account

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt
=> Analytics tab UI fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/donate/DonateFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/drawable/ic_heart_48.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Donate in Settings page

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt
=> Make text size smaller when indicators value can't fit screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/donate/DonateFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/drawable/ic_heart_jacob_48.xml
=> Change Donate into a button in Settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ChooseContactFragment.kt
=> Make Contacts Select screen scrollable

app/build.gradle
=> Update tron-kit (fix transaction tags)

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swaptokenselect/SwapTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectViewModel.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Balance swap

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenTransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Text.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add separate balance page for token

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/AddressFormatSelectScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/BchAddressTypeSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/DerivationSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectViewModel.kt
=> Receive UI

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt
=> Send close after success logic

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swaptokenselect/SwapTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectViewModel.kt, app/src/main/res/values/strings.xml
=> Common send swap

app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectViewModel.kt
=> Sort by balance descending in send/swap select token screens

app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt
=> Fix transaction filtering with spam transactions

app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt
=> Don't close QR scanner page when camera permission cancellation

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Wallet.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt
For EVM blockchains make single transaction source for base coin and its EIP20 tokens.
=> Fix issue with duplicate transactions

app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/address/ReceiveAddressFragment.kt, app/src/main/res/values/strings.xml
=> Add Share button to Receive screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/DraggableCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionList.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt
=> Fix the issue with swiping balance cards

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/indicators/EmaSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/createaccount/CreateAccountAdvanced.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/hodler/HSHodlerInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremenu/RestoreByMenu.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonicnonstandard/RestorePhraseNonStandardScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SelectorDialogCompose.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/values/strings.xml
=> Add subtitle to SelectorDialog items in Watch Address page

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt
=> Make small UI fixes in TokenBalanceScreen

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Theme.kt
=> Ignore the system fontSize setting

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexRepositoryWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceCexViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/BalanceForAccountCex.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/asset/CexAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/cex/asset/CexAssetViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositQrCodeScreen.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> CEX Balance Tab Updates

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectInitViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectInitViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreblockchains/RestoreBlockchainsService.kt
=> Common receive logic

app/src/main/java/io/horizontalsystems/bankwallet/core/utils/Utils.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/NetworkSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectViewModel.kt
Fixed by waiting for IReceiveAdapter to be ready for the newly enabled wallet before navigating to the Receive Screen.
#6574
=> Fix the issue with flicker on navigation to receive screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/FullCoinsProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/ReceiveTokenSelectViewModel.kt
=> Manage coins list logic

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receivemain/FullCoinsProvider.kt
=> Emit copy of items to ensure flow updating

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/FeeRateProvider.kt
=> Use halfHourFee as Bitcoin recommended fee

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactViewModel.kt
=> Fix jumping cursor during Contact editing

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
=> Fix showing Solana contact in Transactions page

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/WalletManager.kt
=> App launch tasks

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt, app/src/main/res/values/strings.xml
=> Add Numpad randomizer to Pin Unlock

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt
=> Improve code readability in Numpad random logic

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinUnlockView.kt
=> Don't show Numpad Randomizer in Set and Edit Pin

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt
=> Handle invalid Market Url error

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/EvmSyncSource.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/EvmNetworkViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmnetwork/addrpc/AddRpcViewModel.kt
=> Fix adding `wss` url as custom Rpc Source

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt
=> Handle different WC support states on Balance screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/dialogs/BackupRequiredDialog.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
=> Change Backup alert dialog text and buttons

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmAccountManager.kt
=> Fix token finding for Evm Chains

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/autolock/AutoLockIntervalsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/autolock/AutoLockIntervalsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/autolock/AutoLockModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/passcode/SecurityPasscodeSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/passcode/SecuritySettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/PasscodeBlock.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement auto-lock settings for Pin

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransaction.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransactionsProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceAdapterRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashViewModel.kt
=> Update zcash sdk to 2.0.0

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/autolock/AutoLockIntervalsFragment.kt
=> Fix text style in Auto-Lock intervals screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/PinDbStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/PinManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/set/PinSetModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/set/PinSetViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinTopBlock.kt, app/src/main/res/values/strings.xml, core/src/main/java/io/horizontalsystems/core/Interfaces.kt
=> Pin updates

app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreprivatekey/RestorePrivateKeyViewModel.kt
=> Add private key validation to RestorePrivateKey screen

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt
- Set fee to default 10_000
- Use ExistingWallet as walletInitMode when wallet has been already initialized
#6660
=> Update zcash-sdk to v 2.0.1

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenTransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
=> Hide transactions amount on balance hide

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseEvmAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseSolanaAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusViewModel.kt
=> Show status info for Evm, Solana, Binance chains

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt
=> Merge contacts when restoring from full backup

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt
=> Fix crash on Market tab disable

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartIndicatorSetting.kt
=> Add chart indicators to Full Backup

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EvmSyncSourceDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EvmSyncSourceStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/SelectBackupItemsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/SelectBackupItemsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restorelocal/RestoreLocalViewModel.kt, app/src/main/res/values/strings.xml
=> Backup changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPassword.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockManager.kt, core/src/main/java/io/horizontalsystems/core/Interfaces.kt
=> Fix Local Backup when Auto-Lock is enabled

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusViewModel.kt
=> Add Zcash status info to AppStatus

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt
=> Backup fixes

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
=> Add BirthdayHeight for Zec in AppStatus

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt
=> Update UnstoppableDomains library

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Show WalletManager for Watch accounts

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/tron/TronExternalContractCallTransactionRecord.kt
=> Improve transaction spam filter

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt
=> Make small fix in SpamManager

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendevmtransaction/SendEvmTransactionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchConfirmationModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/confirmation/oneinch/OneInchSendEvmTransactionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/oneinch/OneInchKitHelper.kt
Improve backup file validation logic.
#6552 
#6758
=> Update 1inch API 

app/build.gradle
=> Update 1inch API url

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/FilterBlockchainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionAdapterWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/res/drawable/ic_sort_24.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Spam filter enhancements

app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItemsEmpty.kt
=> Make changes in Balance Screen for watch account 

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinConfirm.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinNumpad.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinUnlockView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/unlock/PinUnlockViewModel.kt
=> Store Pin random enabled preference

app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectScreen.kt
=> Show donate addresses when user not having wallets

app/build.gradle
=> Update bitcoin-kit, get updated API urls

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
=> Update API sync mode to Blockchair API for BTC and BCH.

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/utils/AddressParser.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/AddressData.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressHandlerFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressParserModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressParserViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/send/SendNftModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt
=> Handle Uri from QrCode scanner in Balance screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/launcher/LaunchViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/asset/NftAssetFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/nft/collection/NftCollectionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt, app/src/main/res/navigation/main_graph.xml, build.gradle
=> Fix deeplinks handling

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenTransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/values/strings.xml
=> Make updates to spam transactions handling

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronViewModel.kt
=> Send bug fixes

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressHandlerFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
=> Ton integration

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonModule.kt
=> Ton additions

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonAmountService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonViewModel.kt
=> Handle ton fee

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/ECashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Address.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressHandlerFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressParserChain.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/BackupLocalModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsViewModel.kt, app/src/main/res/values/strings.xml
=> Add single address watch for BTC like blockchains and TON

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AccountManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AccountsStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_57_58.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/ActiveAccount.kt
=> Allow to have own active account on each level

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/res/values/strings.xml
=> Change texts in Transactions filter

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
=> Reset revealed card when list is updated

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/donate/DonateTokenSelectFragment.kt, app/src/main/res/values/strings.xml
=> Make small changes to Donate module

app/src/main/java/io/horizontalsystems/bankwallet/core/utils/ToncoinUriParser.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt
=> Handle Toncoin uri

app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/backupconfirmkey/BackupConfirmKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ui/SharedComponents.kt
=> Fix words centering in Recovery Phrase and Backup Verify

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt
=> Don't show syncing until text for sync mode `Blockchair`

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/PlatformChartService.kt
=> Change time intervals for Top Platforms chart

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/CoinOverviewScreen.kt
=> Fix market cap rank in Coin overview tab

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WCListFragment.kt
=> Fix opening WalletConnect from Settings page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/ECashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositCexFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/address/ReceiveAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/address/ReceiveAddressModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/address/ReceiveAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/usedaddress/UsedAddressesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/usedaddress/UsedAddressesViewItem.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement showing used external addresses for BTC, BCH, LTC, DASH, XEC

app/src/appcenterdebug/res/values/strings.xml, app/src/appcenterrelease/res/values/strings.xml, app/src/debug/res/values/strings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidget.kt, app/src/main/res/values/strings.xml
=> Add separate deeplink scheme for each build variant

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/PlatformChartService.kt
=> Add intervals based on start time for top platform charts

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt
Issue is reproducible for only some accounts
=> Fix the issue with creating TonKit

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketOverviewTopPlatforms.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/TopPairsBoardView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topnftcollections/TopNftCollectionsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatformsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt, app/src/main/res/drawable/ic_pairs_24.xml, app/src/main/res/drawable/ic_token_pairs.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Market top pairs

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TronKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTronTokenBlockchainService.kt
=> Fix syncing issues in Tron and Bitcoin

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SplAdapter.kt
- token auto enabling fixed
- pending transaction syncer added
#6954 #6868
=> Fix Solana token balance sync

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/TopPairsBoardView.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Typography.kt, build.gradle
=> Top market pairs

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Show Receive button with text

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/res/values/strings.xml
=> Add 5 years period to charts

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Fix Receive button color

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt, app/src/main/res/values/strings.xml
=> Advanced coin filtering

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CellUniversal.kt, app/src/main/res/values/strings.xml
=> Advanced filter subtitles

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationData.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/values/strings.xml
=> Add RBF enabling option to Send Bitcoin Settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveAddressScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewmodels/ReceiveAddressViewModel.kt, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values/strings.xml
=> Remove some alerts from Receive page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filtersresult/MarketFiltersResultsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformCoinsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/MarketTopCoinsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, build.gradle
=> Sync Api tags

app/build.gradle
=> Fix Avalanche transactions sync

app/src/main/java/io/horizontalsystems/bankwallet/modules/importcexaccount/ImportCexAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/RestoreAccountFragment.kt
=> Prevent screenshot taking during keys import

app/build.gradle
=> Fix Avalanche C transaction sync

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/detectors/DetectorsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/detectors/DetectorsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/detectors/DetectorsViewModel.kt
=> Make fixes in Smart Contract Analysis code

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/WalletConnectListViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/list/ui/WCSessionScreen.kt
=> Don't automatically open QrCode scanner in WalletConnect page

app/src/main/java/io/horizontalsystems/bankwallet/modules/lockscreen/LockScreenActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ConfirmPinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/EditDuressPinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/EditPinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/SetDuressPinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/SetPinFragment.kt
=> Disallow screenshots on Pin lock pages

app/src/main/java/io/horizontalsystems/bankwallet/modules/managewallets/ManageWalletsService.kt
=> Show Zec info button immediately after it was enabled

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt
=> Update logic for showing Coin protocol name

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusViewModel.kt
=> Add `Sync Mode` info to App Status

app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTronTokenBlockchainService.kt
=> Fix crash during address validation for Tron blockchain

app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SearchBar.kt
=> Make SearchBar hint a single line

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BaseTronAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewmodels/ReceiveAddressViewModel.kt
=> Fix updating of account active state for Tron

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/ViewModelUiState.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionAdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenTransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/SelectContactFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/SelectContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/ITransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionAdapterWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionRecordRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsUiState.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/cell/CellUniversal.kt, app/src/main/res/drawable/ic_user_24.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Transactions filter by address

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt
=> Fix Ecash transaction sync issue for Created accounts

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BinanceAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt
=> Filter by address tron

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCDelegate.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCSessionManager.kt
=> Show WC pending requests filtered by current active account

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
=> Replace Blockchair API with BlocksDecoded proxy

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/SearchBar.kt
=> Add clear button to search in Market Overview screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/SelectContactFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/SelectContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/SelectContactFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/SelectContactViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/InfoErrorMessageDefault.kt, app/src/main/res/drawable/icon_paper_contract_24.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Transactions filter by contact

app/build.gradle
=> Fix crash during Solana initial sync

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TransactionAdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/FilterCoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
=> Show all engaged transaction tokens in Filters

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/ContactsViewModel.kt
=> Add clear text button to Search in Contacts screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceViewModel.kt
=> Fix checking for backup state in Token Balance page

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashTransactionsProvider.kt, app/src/main/res/values/strings.xml
=> Implement filtering txs by contact in ZCash

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt
=> Remove NFT button from Balance screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt
=> Show Receive button with text, when no swap button

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusViewModel.kt
=> Fix crash in App Status page

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/values/strings.xml
=> Add Company Telegram and Twitter links to Settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/ranks/CoinRankViewModel.kt
=> Fix crash in Coin Ranks page

app/build.gradle
=> Update Ethereum Rpc url

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/bitcoin/BitcoinOutgoingTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/Composables.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add RBF speedUp/cancel screens

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsFilterFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt
=> Include suspicious filter to filters base configuration

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
=> RBF changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/SwapMainFragment.kt
- case when fragments not being restored should be debugged separately
#7069
=> Remove toast messages iin SendFragment and SwapMainFragment

app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/FiatService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/SwapSelectProviderFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/SwapSelectProviderViewModel.kt, app/src/main/res/values/strings.xml
- Show fiat amount in Quote Providers
- Fix showing selected provider on first open
- Fix coin price in FiatService
=> Make fixes in Swap Quote Providers

app/src/main/java/io/horizontalsystems/bankwallet/modules/swap/coinselect/SelectSwapCoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/FiatService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/SwapFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/swapxxx/SwapQuoteService.kt
=> Swap additions

app/src/main/java/io/horizontalsystems/bankwallet/entities/TransactionValue.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
=> Update Transaction Info design

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceCache.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/resendbitcoin/ResendBitcoinViewModel.kt, app/src/main/res/values/strings.xml
=> ResendBitcoin module improvements

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmViewModel.kt
=> Execute sending in background thread

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveTokenSelectScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewmodels/DerivationSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoreblockchains/RestoreBlockchainsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectScreen.kt, app/src/main/res/values/strings.xml
=> Implement minor changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/EvmBlockchainHelper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ISwapQuote.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapV3Provider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/OneInchProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceEvm.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionSettings.kt
=> Swap refactoring

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionFilterService.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
=> Make small fixes in Transactions

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ISwapFinalQuote.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ISwapQuote.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapV3Provider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/OneInchProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/ISendTransactionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceEvm.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataField.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataFieldAllowance.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataFieldNonce.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataFieldRecipient.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataFieldRecipientExtended.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ui/DataFieldSlippage.kt
=> Show transaction nonce if not default in swap confirm

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapQuoteService.kt
=> Add timeout for fetching quotes

app/build.gradle
=> Fix evm duplicate txs issue

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseTokenManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/CexAssetManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NftMetadataManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/EvmLabelProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/BlockchainSettingsStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/EvmSyncSourceStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppIconService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/LaunchScreenService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/theme/ThemeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCSessionManager.kt
=> Optimize Application start time

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapSelectProviderFragment.kt, app/src/main/res/values/strings.xml
=> Remove fee info warning text in swap provider selector page

app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItem.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/TransactionInfoCells.kt
- Make toggle price button work
- Show YouGet swap value as red when we have recipient
#7202
=> Make small fixes in transaction info

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
=> Remove CryptoCompare Api key

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt
=> Change options order in Market Filters

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmIncomingTransactionRecord.kt
=> Mark as spam when incoming transaction has 0 coin value

app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultiple.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/extensions/BottomSheetSelectorMultipleDialog.kt
For some reason val `selected` is not re-inited when the keys selectedIndexes, items are changed. Using `config.uuid` resolves it. Note if we pass `config.uuid` as uuid parameter then `selected` also will not re-inited when uuid is changed.
#7280
=> Fix the weird issue with selected states in compose

app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/selectblockchains/SelectBlockchainsViewModel.kt
=> Show blockchain select screen with unselected items during Watch Account

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt
=> Replace Btc.com with Blockchair.com as explorer url

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt
- show fee in transaction info
#7031
=> Fix solana transactions sync and send

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/CoinViewFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/coinmarkets/CoinMarketsViewModel.kt
=> Remove rates from Coin Markets

app/build.gradle
=> Fix parsing memo in bitcoin based blockchains

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt
- Issues not shown in some coins
- Change blockchains sorting
#7308
=> Fix small issues in Coin Page

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt, app/src/main/res/values/strings.xml
=> Fix coin issues counters

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt
=> Don't show alert in Telegram and Twitter menu options

app/src/main/java/io/horizontalsystems/bankwallet/core/MarketKitExtensions.kt
=> Move Solana after Toncoin in blockchains list order

app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/KeyAccountInfoFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyFragment.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add info button to Account Extended Key

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceFactory.kt
=> Add SendTransactionService creation for all evm blockchains

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceFactory.kt
=> Merge master

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/res/values/strings.xml
- Make Twitter, Telegram icons yellow color
#7287
=> Reorganize items in Settings

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlChartService.kt
=> Make fixes for reported bugs

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionViewModel.kt
=> Enable more Evm chains for WalletConnect

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TonAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivityViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appstatus/AppStatusViewModel.kt
=> Ton app status

app/src/main/java/io/horizontalsystems/bankwallet/modules/confirm/ConfirmTransactionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCSessionManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WCRequestFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WCRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signtransaction/WCSignEthereumTransactionRequestScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/signtransaction/WCSignEthereumTransactionRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionViewModel.kt
=> Implement WalletConnect ETH transaction signing

app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AdapterFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/AdapterManager.kt
=> Handle exception on adapter creation

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/password/BackupLocalPasswordViewModel.kt
- do not lowercase token addresses
- add date time to backup file name
#7408
=> Fix bug in BackupProvider

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveAddressScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/helpers/TextHelper.kt
=> Update QR code generation

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionViewModel.kt, app/src/main/res/values/strings.xml
=> Add wallet connect session validation

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
=> Update zcash-sdk to 2.1.1

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCDelegate.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/WCWalletRequestHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionViewModel.kt
`wallet_addEthereumChain`, `wallet_switchEthereumChain`
#7395
=> Implement WalletConnect methods

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronConfirmationScreen.kt, app/src/main/res/values/strings.xml
=> Remove Tron inactive address warning in Send

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/OneInchProvider.kt
=> Add 1inch partner fee

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/WCRequestViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/session/WCSessionViewModel.kt
=> WalletConnect fixes

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt, app/src/main/res/values/strings.xml
=> Add setting to hide balance tab buttons

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/SolanaAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaViewModel.kt, core/src/main/res/layout/view_custom_snackbar.xml
- Show message from RPC Error when sending SOL/SPL
- Increment custom snackbar's max lines to 4
#7339
=> Check SOL balance when sending SPL

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/ButtonSecondary.kt
=> Block explorer dash

app/src/main/java/io/horizontalsystems/bankwallet/modules/releasenotes/ReleaseNotesFragment.kt, app/src/main/res/values/strings.xml
=> Highlight social media links

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt, app/src/main/res/values/strings.xml
=> Apply new ui for tab settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketSignalsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/InfoText.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add signals description page for watchlist

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/Types.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/TopCoins.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/GlobalMarketRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/MetricChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/MarketCell.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Implement Etf page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/zcash/ZcashAdapter.kt
=> Zcash updates

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Extensions.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/MarketOverviewModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsScreen.kt
=> Handle alternative image url for TopPairs

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt, app/src/main/res/values/strings.xml
=> Update About screen UI

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BaseTokenManager.kt
=> Remove BNB as conversion base token

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformViewModel.kt
=> Update sorting in Platform page

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt
=> Fix updating sorting type in BalanceViewModel

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacyScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacyViewModel.kt, app/src/main/res/values/strings.xml, core/src/main/java/io/horizontalsystems/core/CoreApp.kt
=> Implement turning on/off UI event logs

app/src/main/java/io/horizontalsystems/bankwallet/modules/backuplocal/fullbackup/BackupProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceModule.kt
=> Add new fields to local backup file

app/build.gradle, app/src/main/res/values/attrs.xml
=> Enable Leakcanary to track memory leaks

app/src/main/java/io/horizontalsystems/bankwallet/widgets/MarketWidgetRepository.kt
=> Show MarketCap as subtitle in Widget

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt
=> Fix updating MarketFilters on Blockchain select

app/build.gradle
=> Fix News in Markets

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt
=> Apply marquee for MetricsBoard

app/build.gradle
=> Update bitcoin-kit checkpoints and market-kit coins initial list

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/utxoexpert/UtxoExpertModeScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/utxoexpert/UtxoExpertModeViewModel.kt, app/src/main/res/values/strings.xml
=> Update UtxoExpertMode page

app/src/main/java/io/horizontalsystems/bankwallet/modules/walletconnect/request/sendtransaction/WCSendEthereumTransactionRequestViewModel.kt
=> Add '0x' prefix to transactionHash in WC send transaction response

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddSolanaTokenBlockchainService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/addtoken/AddTokenService.kt
=> Enable adding custom Solana tokens

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TonKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tonconnect/TonConnectNewViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tonconnect/TonConnectSendRequestViewModel.kt
=> Ton status info

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketViewModel.kt, app/src/main/res/values/strings.xml
=> Markets total cards

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/settings/SendEvmNonceService.kt
=> Fix HTTP exception crash during Evm Send

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topcoins/TopCoins.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/toppairs/TopPairsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/topplatforms/TopPlatforms.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/HSSwipeRefresh.kt
=> Show pull to refresh under sorting buttons in Markets

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/BtcBlockchainManager.kt
=> Enable Blockchair sync mode for Litecoin

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/evmfee/EvmCommonGasDataService.kt
=> Improve fee estimation logic for insufficient balance case

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/backupalert/BackupAlert.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/overview/ui/MarketsHorizontalCards.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/qrscanner/QRScannerActivity.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/binance/SendBinanceConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashConfirmationScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Theme.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HsBottomNavigation.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HsIconButton.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/HsTextButton.kt, build.gradle, components/chartview/build.gradle, gradle/wrapper/gradle-wrapper.properties
- Setup compile SDK to 35
- Gradle to 8.9
=> Update libraries to latest

app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinBaseAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/BitcoinCashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/DashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/ECashAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/LitecoinAdapter.kt
=> Set confirmation threshold to 1 for Bitcoin like chains

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionViewModel.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/Subscription.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/SubscriptionService.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-google-play/src/main/java/io/horizontalsystems/subscriptions/googleplay/SubscriptionServiceGooglePlay.kt
=> Subscriptions

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersBottomSheets.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/values/strings.xml
=> Market filters minor changes

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/PremiumBanner.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/PremiumSubscribedScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/UiElements.kt, app/src/main/res/values/strings.xml
=> Adjust premium banner colors for light theme

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TorBlock.kt
=> Wrap Tor connection into paid action

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/ui/Components.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/favorites/MarketFavoritesMenuService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/subscription/SubscriptionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionChoosePlanViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/SelectSubscriptionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/UiElements.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceDev.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceInitializer.kt
=> Dev subscription testing

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/subscription/SubscriptionFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/subscription/SubscriptionViewModel.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/SubscriptionService.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceDev.kt, subscriptions-google-play/src/main/java/io/horizontalsystems/subscriptions/googleplay/SubscriptionServiceGooglePlay.kt
=> Show active Subscription name in settings

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/TorManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/about/AboutFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/tor/SecurityTorSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/tor/SecurityTorSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TorBlock.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tor/TorConnectionViewModel.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Update Privacy settings and move it to MainSettings page

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmEnterAddressScreen.kt, app/src/main/res/values/strings.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, subscriptions-core/build.gradle, subscriptions-dev/build.gradle, subscriptions-google-play/build.gradle
=> Implement Address check UI for new Send

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/BlockchainsSelectorFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/SectorsSelectorFragment.kt, app/src/main/res/values/strings.xml
=> Apply UX changes to Sectors/Blockchains selectors in MarketFilters

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/AddressSecurityCheckerChain.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/SpamAddressDetector.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressSecurityCheckerFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamAddressManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/SpamAddressDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/SpamAddressStorage.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_60_61.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/SpamAddress.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/SpamScanState.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmIncomingTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt
- implement it for spam detection
#7450
=> Add address security checker

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/ChainalysisAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressSecurityCheckerFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt
=> Add Chainalysis address check

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt
=> Add token to watchlist from search page

app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt
=> Update share ui stats by premium user state

app/src/main/res/drawable/launcher_main_monochrome.xml, app/src/main/res/mipmap-anydpi-v26/launcher_main.xml
=> feat: monochrome icon

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/PremiumBanner.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionChoosePlanViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/SelectSubscriptionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/UiElements.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Text.kt, app/src/main/res/values/strings.xml, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/Subscription.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/SubscriptionService.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceDev.kt, subscriptions-google-play/src/main/java/io/horizontalsystems/subscriptions/googleplay/SubscriptionServiceGooglePlay.kt
=> User subscription plans

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/vipsupport/VipSupportBottomSheet.kt
=> Fix image color in Vip BottomSheet

app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressValidatorFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt, app/src/main/res/values/strings.xml
=> Add address validation to EnterAddress screen in Send

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt
=> Show recent contact in send address screen

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/category/MarketCategoryFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/platform/MarketPlatformFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/tvl/TvlViewItemFactory.kt
=> Add fixes in Market screens for `No connection` cases

app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/analytics/CoinAnalyticsViewModel.kt
=> Set technical advice as first block in coin analytics

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/address/AddressCheckManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/AddressChecker.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/ChainalysisAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/Eip20AddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/HashDitAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt, app/src/main/res/values/strings.xml
=> Add address black list validators

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/fee/FeeCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/fee/HSFeeInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonFeeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonViewModel.kt
=> Fix crashes

app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacyViewModel.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceDev.kt
=> Stats manager init fix

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/HSAddressCell.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/AddressRiskyBottomSheetAlert.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/SendEvmScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/solana/SendSolanaScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/ton/SendTonScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/tron/SendTronScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/zcash/SendZCashScreen.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Show risky address alert in Send

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt
=> Add new sync sources for BSC

app/build.gradle
=> Fix issue with duplicate sums of txs of Tron

app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionModel.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/IPaidAction.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt
=> Remove PrivacyMode from paid actions

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt
=> Make small UI changes for Send address input

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/FormsInputAddress.kt, app/src/main/res/values/strings.xml
=> Redesign address error

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/AddressEnterBottomSheet.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/res/values/strings.xml
=> Send address UI updates

app/build.gradle
=> Add Polygon RPC service to prevent error 429

app/src/main/java/io/horizontalsystems/bankwallet/core/address/Eip20AddressValidator.kt
=> Fix send Trc20 crash

app/build.gradle
=> Fix ecash transaction send with memo

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/evm/confirmation/SendEvmConfirmationViewModel.kt
=> Fix saving Evm address in Recent

app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/ui/SelectSubscriptionScreen.kt
=> Hide testimonials in Premium Purchase screen

subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-google-play/src/main/java/io/horizontalsystems/subscriptions/googleplay/SubscriptionServiceGooglePlay.kt
=> Subscriptions config

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/markdown/MarkdownFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinConfirm.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinSetView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/ui/PinUnlockView.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/releasenotes/ReleaseNotesFragment.kt
=> Fix content ovelapping top statusbar

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/drawable/ic_question_24.xml, app/src/main/res/values/strings.xml
=> Add Crypto Quiz setting with corresponding icon

app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/ContactsRepository.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/model/Contact.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt
=> Fix getting contact addresses by blockchain

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonic/RestorePhraseScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/restoreaccount/restoremnemonicnonstandard/RestorePhraseNonStandardScreen.kt
=> Fix suggestions bar for phrase restore input

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionsViewModel.kt, app/src/main/res/values/strings.xml
=> Add setting to enable/disable amount rounding

app/src/main/java/io/horizontalsystems/bankwallet/core/BaseComposeFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/address/IAddressHandler.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/viewmodel/AddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/SelectContactViewModel.kt
=> Stellar contacts

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAssetAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/StellarTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/StellarAccountManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/activatetoken/ActivateTokenFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/confirm/ConfirmTransactionScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/depositcex/DepositAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ActivateTokenViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveAddressScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveTokenActivationRequired.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewmodels/ReceiveAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionViewItemFactoryHelper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Stellar additions

app/build.gradle
=> Upgrade Etherscan to v2

app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ui/ReceiveAddressScreen.kt
=> Change buttons order in Receive

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAssetAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressValidatorFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/amount/SendAmountService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressValidator.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/stellar/SendStellarAddressService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/stellar/SendStellarMinimumAmountService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/stellar/SendStellarModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/stellar/SendStellarViewModel.kt, app/src/main/res/values/strings.xml
=> Stellar create account

app/build.gradle
=> Create account when sending XLM if required

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressValidatorFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/CoinAddressCheck.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/ui/CheckAddressInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/addresschecker/AddressCheckFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/addresschecker/AddressCheckerFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/addresschecker/ui/AddressCheckBlockchainSelector.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/addresschecker/ui/AddressCheckTokenSelector.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/res/drawable/ic_radar_24.xml, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Add Address checker to Settings

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAssetAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/stellar/SendStellarModule.kt
=> Set max sendable amount for stellar

app/src/main/AndroidManifest.xml, app/src/main/java/io/horizontalsystems/bankwallet/core/utils/AddressUriParser.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt
=> Add crypto URI scheme support

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/CoinAddressCheck.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/ui/CheckAddressInput.kt
=> Improve error showing by design in AddressChecker

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt, app/src/main/res/values/strings.xml
=> Add info text for BalanceTab to App Settings

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersModule.kt, app/src/main/res/values/strings.xml
=> Add new periods (2Y, 3Y, 4Y, 5Y) to the market filters

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/appearance/AppearanceFragment.kt
=> Remove icons from language an currency menu items in settings

app/src/main/java/io/horizontalsystems/bankwallet/modules/address/AddressInputModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseUniswapV3Provider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/OneInchProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/ThorChainProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/settings/SwapSettingRecipient.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/settings/ui/SwapSettingsComponents.kt
=> Add recipient address setting for thorchain swap

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/Typography.kt
=> UI updates

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/settings/SwapSettingRecipient.kt
=> Swap setting recipient

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewItemFactory.kt, app/src/main/res/values/strings.xml
=> Show assets list in locked info

app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/ActionCompletedDelegate.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/DonationShowManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/RecentAddressManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressViewModel.kt
=> Show donate banner after send with 30 days interval

app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/terms/TermsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/watchaddress/WatchAddressFragment.kt
=> Rename buttons in Watch and Terms screens

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/App.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/Eip20Adapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/StellarTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/TronTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/address/AddressChecker.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/StellarTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/factories/TransferEventFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmBlockchainManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SpamManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/AppDatabase.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/SpamAddressDao.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/storage/migrations/Migration_64_65.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/SpamScanState.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/tron/TronExternalContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactions/TransactionViewItemFactory.kt
=> Refactor phishing detection, add check for Tron and Stellar 

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/StatsManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/Types.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartPointsWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/EarnScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/EarnViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultChartFormatter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultViewModel.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Vaults.fyi tab to Markets

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/MarketKitWrapper.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/Types.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt, app/src/main/res/values/strings.xml
- Add Stellar to Blockchain selector 
- Add Gold and SP 500 outperformed options
#8124, #8234
=> Make updates to Market filters

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/SolanaKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/SwapHelper.kt
=> Fetch solana address statically

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/AllBridgeProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/EvmSwapHelper.kt
=> Allbridge proxy

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersViewModel.kt, build.gradle
=>  Set default coin list to Top100 in Marlet Filters

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/EvmTransactionConverter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ApproveTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ContractCreationTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmIncomingTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmOutgoingTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/EvmTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/ExternalContractCallTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/SwapTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/transactionrecords/evm/UnknownSwapTransactionRecord.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/AbstractSendTransactionService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceBtc.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceEvm.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceSolana.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceStellar.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/sendtransaction/SendTransactionServiceTron.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/transactionInfo/TransactionInfoViewItemFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/usersubscription/BuySubscriptionModel.kt, app/src/main/res/values/strings.xml, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/IPaidAction.kt, subscriptions-core/src/main/java/io/horizontalsystems/subscriptions/core/UserSubscriptionManager.kt, subscriptions-dev/src/main/java/io/horizontalsystems/subscriptions/dev/SubscriptionServiceDev.kt
=> Mev protection

app/src/main/java/io/horizontalsystems/bankwallet/core/managers/NumberRounding.kt, app/src/test/java/io/horizontalsystems/bankwallet/core/managers/NumberRoundingTest.kt
=> Update number rounding strategy

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/main/MainSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/Header.kt, app/src/main/res/values/strings.xml
=> Add F-Droid support link

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmKitManager.kt
=> Pass source tag to merkle

app/src/main/java/io/horizontalsystems/bankwallet/core/providers/AppConfigProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/PrivacyViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/SecuritySettingsFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/security/ui/TorBlock.kt, app/src/main/res/drawable/icon_nym_vpn_24.xml, app/src/main/res/values/strings.xml
=> Add Nym VPN link to Privacy Settings page

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/EarnScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/EarnViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/VaultBlockchainsSelectorFragment.kt
- Show premium banner when chain is selected
- Update percent calculation
#7946
=> Make small fixes in Earn tab

app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/AbstractChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/chart/ChartViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/CoinOverviewChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/Chart.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/coin/overview/ui/ChartHelper.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/EarnViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultChartFormatter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultChartService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/earn/vault/VaultViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/metricchart/ProChartService.kt, app/src/main/res/values/strings.xml, components/chartview/src/main/java/io/horizontalsystems/chartview/ChartData.kt, components/chartview/src/main/java/io/horizontalsystems/chartview/models/ChartPoint.kt
=> Make fixes in Vaults 

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/res/values/strings.xml
=> Make small fixes for Balance page

app/src/main/java/io/horizontalsystems/bankwallet/modules/eip20revoke/Eip20RevokeConfirmViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/SwapHelper.kt
=> Add support for USDT TRC20 token revocation

app/build.gradle
=> Fix getting tokens with empty code in popular list

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/SendBitcoinViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsViewModel.kt
=> Make fixes in Advanced settings for Send

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/bitcoin/advanced/SendBtcAdvancedSettingsScreen.kt, app/src/main/res/values/strings.xml
=> Update transaction settings description to include coin type

app/src/main/java/io/horizontalsystems/bankwallet/modules/market/MarketScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/etf/EtfViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/filters/MarketFiltersFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/metricspage/MetricsPageChartService.kt, app/src/main/res/values/strings.xml
=> Markets small fixes

app/build.gradle
=> Fix incorrect marking merkleio txs as failed

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/modules/blockchainsettings/BlockchainSettingsService.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/viewmodels/ReceiveAddressViewModel.kt
=> Enhancenments

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/MoneroAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/MoneroTransactionsAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/ReceiveFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/monero/MoneroSubaddressesFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/monero/MoneroSubaddressesScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/monero/ReceiveMoneroAddressViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/receive/monero/ReceiveMoneroScreen.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Monero subaddresses

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/MoneroAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/stats/Types.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/privatekeys/PrivateKeysViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/publickeys/PublicKeysFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/publickeys/PublicKeysModule.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/publickeys/PublicKeysViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showextendedkey/ShowExtendedKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showmonerokey/ShowMoneroKeyFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/showmonerokey/ShowMoneroKeyModule.kt, app/src/main/res/navigation/main_graph.xml, app/src/main/res/values/strings.xml
=> Add Monero keys to Private/Public Keys screens

app/src/main/java/io/horizontalsystems/bankwallet/core/factories/AddressParserFactory.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/AddressUri.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/memo/HSMemoInput.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/SendFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/address/EnterAddressFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/monero/SendMoneroScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/sendtokenselect/SendTokenSelectFragment.kt
=> Handle Monero URI Scheme

app/src/main/java/io/horizontalsystems/bankwallet/modules/amount/AmountInputModeViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/SwapViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/xrate/XRateService.kt
=> Disable fiat input for expired rate in Send/Swap

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/EvmSyncSourceManager.kt
=> Fix etherscan V2 migration for transactions

app/src/main/java/io/horizontalsystems/bankwallet/core/Interfaces.kt, app/src/main/java/io/horizontalsystems/bankwallet/core/managers/LocalStorageManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/BalanceViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/manageaccount/ManageAccountViewModel.kt
=> Update showing non-recommended/non-standard cautions

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivityViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockManager.kt
=> Fix showing pin for users without pin set

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListComponents.kt, app/src/main/java/io/horizontalsystems/bankwallet/ui/compose/components/CoinListOrderable.kt, app/src/main/java/io/horizontalsystems/bankwallet/uiv3/components/controls/HSCellButton.kt
=> Add HSCellButton to use in draggable cards

app/src/main/java/io/horizontalsystems/bankwallet/uiv3/components/menu/MenuGroup.kt
=> Set the dialog menu width to 240dp

app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/ISwapQuote.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/BaseThorChainProvider.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/multiswap/providers/MayaProvider.kt
=> Thorchain swaps

app/build.gradle, app/src/main/java/io/horizontalsystems/bankwallet/core/adapters/MoneroAdapter.kt, app/src/main/java/io/horizontalsystems/bankwallet/entities/Account.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/send/monero/SendMoneroModule.kt
=> Monero minor fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/contacts/screen/ContactsScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/market/search/MarketSearchFragment.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/tokenselect/TokenSelectScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/uiv3/components/ButtonsGroup.kt
=> Small UI fixes

app/src/main/java/io/horizontalsystems/bankwallet/modules/send/monero/SendMoneroViewModel.kt
=> Disable send button when fee is null

app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/token/TokenBalanceScreen.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceCard.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceForAccount.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/balance/ui/BalanceItems.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/PinComponent.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/pin/core/LockManager.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/language/LanguageSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/settings/privacy/tor/SecurityTorSettingsViewModel.kt, app/src/main/java/io/horizontalsystems/bankwallet/modules/theme/ThemeService.kt, app/src/main/java/io/horizontalsystems/bankwallet/uiv3/components/cards/CardsElementAmountText.kt, app/src/main/res/drawable/ic_scan_24.xml, app/src/main/res/values/strings.xml
=> Pass pin unlock on setting change

app/src/main/java/io/horizontalsystems/bankwallet/modules/main/MainActivity.kt
=> Don't show biometric prompt when system changes theme
